#ifndef OPS_H
#define OPS_H

// Standard includes
#include <stddef.h>
#include <stdint.h>

// Cipher includes
#include "config/default.h"

/*-----------------------------------------------------------------------------------------------------
 *                                                                                                Types
 *---------------------------------------------------------------------------------------------------*/

/**
 * @brief Operations supported by the daemon
 */
typedef enum {
    CIPHER_OPS_TYPE_RPC,
    CIPHER_OPS_TYPE_EVENT,
    CIPHER_OPS_TYPE_STREAM,

    CIPHER_OPS_TYPE_MAX,
} cipher_ops_type_t;

/*-----------------------------------------------------------------------------------------------------
 *                                                                                                  RPC
 *---------------------------------------------------------------------------------------------------*/

/**
 * @brief Errors that a remote RPC call can return
 */
typedef enum {
    CIPHER_RPC_ERR_OK,              /*!< RPC executed correctly */
    CIPHER_RPC_ERR_TIMEOUT,         /*!< Remote host didn't respond before required timeout */
    CIPHER_RPC_ERR_CONN_LOST,       /*!< Connection lost with remote host on interface */
    CIPHER_RPC_ERR_NOT_FOUND,       /*!< RPC is not available on remote host */
    CIPHER_RPC_ERR_NOT_IMPLEMENTED, /*!< RPC is not implemented in remote host */

    CIPHER_RPC_ERR_MAX,
} cipher_rpc_err_t;

/**
 * @brief Passed by the user to monitor a remote RPC request
 */
typedef struct {
    uint16_t device_id;      /*!< Remote host ID where you want to execute the RPC */
    uint16_t timeout_ms;     /*!< How long the daemon should wait for a remote host to answer */
    cipher_rpc_err_t *error; /*!< Buffer to store error flag */
} cipher_rpc_info_t;

/**
 * @brief Function signature called when an RPC needs to be ran in the localhost
 */
typedef cipher_rpc_err_t (*rpc_handler_func)(void *request, void *response);

/**
 * @brief Used by daemon's RPC thread to execute a localhost handler
 */
typedef struct {
    size_t request_size;       /*!< Size of RPC request struct */
    size_t response_size;      /*!< Size of RPC response struct */
    rpc_handler_func handler;  /*!< Localhost autogenerated RPC handler (not user's) */
    bool supports_parallelism; /*!< Indicates if the handler supports parallel instances */
} cipher_ops_rpc_t;

/**
 * @brief Returns a string version of the RPC err enum
 *
 * @param err The error you want a string for
 * @return char* The error as a string
 */
char *cipher_rpc_err_str(cipher_rpc_err_t err);

/*-----------------------------------------------------------------------------------------------------
 *                                                                                                Event
 *---------------------------------------------------------------------------------------------------*/
typedef struct {
} cipher_ops_event_t;

/*-----------------------------------------------------------------------------------------------------
 *                                                                                               Stream
 *---------------------------------------------------------------------------------------------------*/
typedef struct {
} cipher_ops_stream_t;

/*-----------------------------------------------------------------------------------------------------
 *                                                                                                Entry
 *---------------------------------------------------------------------------------------------------*/

/**
 * @brief Used to hold ops instance info for a service
 */
typedef struct {
    uint8_t id;
    cipher_ops_type_t type;
    char name[CONFIG_CIPHER_NAME_LEN];
    union {
        cipher_ops_rpc_t rpc;
        cipher_ops_event_t event;
        cipher_ops_stream_t stream;
    } op;
} cipher_ops_entry_t;

#endif