services:
  alpha-manufacturing:
    image: containers.ad.corekinect.com/manufacturing-alpha:latest
    pull_policy: always
    env_file:
      - ../.env
    volumes:
      - ../assets:/app/assets
      - ../logs:/app/logs
