# Concord service account + cluster-wide bindings
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: concord-super-admin-binding
  labels:
    app.kubernetes.io/part-of: concord
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: concord-super-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: concord-admins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: concord-api-system-monitor-binding
  labels:
    app.kubernetes.io/part-of: concord
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: concord-api-system-monitor
subjects:
  - kind: ServiceAccount
    name: concord-api
    namespace: staging
  - kind: ServiceAccount
    name: concord-api
    namespace: production
