# Iface library
CONFIG_NOCACHE_MEMORY=y
CONFIG_CK_IFACE_LIB_UART=y
CONFIG_CK_IFACE_NUM_PACKET_BUFFERS=40
CONFIG_CK_IFACE_UART_STACK_HEAP_SIZE=5000
CONFIG_CK_IFACE_RECV_RING_BUFER_SIZE=5000
# CONFIG_CK_IFACE_NUM_UART_SOCKETS=2

# Logging
CONFIG_SOC_SERIES_STM32F4X=y
CONFIG_LOG=y
# CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BACKEND_SHOW_COLOR=y
CONFIG_POLL=y

CONFIG_CK_IFACE_UART_STACK_THREAD_STACK_SIZE=10000
CONFIG_CK_IFACE_UART_STACK_THREAD_PRIORITY=7

# System
CONFIG_NEWLIB_LIBC=y
CONFIG_MAIN_STACK_SIZE=10000

# iface library
CONFIG_CK_IFACE_LIB_UART=y
CONFIG_CK_IFACE_LIB_ASSEMBLER_DEBUG_LEVEL=3
# CONFIG_CK_IFACE_RECV_CB_BUFFER_SIZE=128

# Networking config
# CONFIG_NETWORKING=n
# CONFIG_NET_CONFIG_AUTO_INIT=y
# CONFIG_NET_CONFIG_SETTINGS=y
# CONFIG_NET_IPV4=y
# CONFIG_NET_DHCPV4=y
# CONFIG_NET_CONFIG_NEED_IPV4=y
# CONFIG_DNS_RESOLVER=y

# Thread-Aware debugging
# CONFIG_THREAD_MONITOR=y
# CONFIG_INIT_STACKS=y
# CONFIG_DEBUG_THREAD_INFO=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_NAME=y

# Disable code for debuggin
# CONFIG_DEBUG_OPTIMIZATIONS=y
# CONFIG_EXCEPTION_STACK_TRACE=y
# CONFIG_DEBUG_INFO=y

CONFIG_CK_IFACE_LIB_UART=y

# Enable entropy generator for stm32f4 chip
CONFIG_ENTROPY_GENERATOR=y
CONFIG_ENTROPY_STM32_RNG=y

CONFIG_RING_BUFFER=y

# CONFIG_NOCACHE_MEMORY=y

#config the DMA
CONFIG_DMA=y


# enable pin controller
CONFIG_PINCTRL=y

# CONFIG_SERIAL=y
# CONFIG_UART_INTERRUPT_DRIVEN=y

# CONFIG_OPENOCD=y