# cipher + iface
CONFIG_CK_IFACE_LIB_SOCKETS=y
CONFIG_CK_CIPHER_LIB=y
CONFIG_CK_CIPHER_CLIENT_IFACE_COUNT=1
CONFIG_CK_CIPHER_SERVER_IFACE_COUNT=1

# net core
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_NET_DHCPV4=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_CONNECTION_MANAGER=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_MGMT_EVENT_INFO=y
CONFIG_NET_MAX_CONTEXTS=24
CONFIG_NET_MAX_CONN=24
CONFIG_NET_TCP_TIME_WAIT_DELAY=250

# --- MCUboot A/B + DFU: write firmware to the secondary slot, request a swap ---
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_IMG_MANAGER=y
CONFIG_MCUBOOT_IMG_MANAGER=y
CONFIG_STREAM_FLASH=y
CONFIG_IMG_ERASE_PROGRESSIVELY=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_REBOOT=y

# logging
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_PRINTK=y
CONFIG_CK_CIPHER_IFACE_LOG_LEVEL=1
CONFIG_CK_CIPHER_SD_LOG_LEVEL=1
CONFIG_CK_CIPHER_STREAM_LOG_LEVEL=3
CONFIG_CK_CIPHER_DAEMON_LOG_LEVEL=3
