apiVersion: v1
kind: ConfigMap
metadata:
  name: concord-config
  labels:
    {{- include "concord.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
