{{- if and .Values.httpApi.enabled .Values.httpApi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.httpApi.serviceAccount.name }}
  labels:
    {{- include "concord.labels" . | nindent 4 }}
    {{- include "concord.httpApi.selectorLabels" . | nindent 4 }}
{{- end }}
