{{- if .Values.resourceQuotas.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: concord-resource-quota
  labels:
    {{- include "concord.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuotas.cpu | quote }}
    requests.memory: {{ .Values.resourceQuotas.memory | quote }}
    limits.cpu: {{ .Values.resourceQuotas.cpu | quote }}
    limits.memory: {{ .Values.resourceQuotas.memory | quote }}
{{- end }}
