apiVersion: 1
datasources:
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: false

- name: InfluxDB
  type: influxdb
  access: proxy
  orgId: 1
  url: http://influxdb:8086
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    version: Flux
    organization: concord
    defaultBucket: metrics
  secureJsonData:
    token: concord-influxdb-dev-token
