apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    {{- include "shared-nats.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.clientPort }}
      targetPort: client
      protocol: TCP
      name: client
    - port: {{ .Values.service.monitorPort }}
      targetPort: monitor
      protocol: TCP
      name: monitor
  selector:
    {{- include "shared-nats.selectorLabels" . | nindent 4 }}
