apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "shared-nats.fullname" . }}
  labels:
    {{- include "shared-nats.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "shared-nats.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "shared-nats.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shared-nats.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nats
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-c"
            - "/etc/nats/nats.conf"
          ports:
            - name: client
              containerPort: 4222
              protocol: TCP
            - name: monitor
              containerPort: 8222
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitor
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitor
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /etc/nats
            {{- if and .Values.jetstream.enabled .Values.jetstream.storage.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "shared-nats.fullname" . }}-config
  {{- if and .Values.jetstream.enabled .Values.jetstream.storage.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.jetstream.storage.storageClass }}
        storageClassName: {{ .Values.jetstream.storage.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.jetstream.storage.size }}
  {{- end }}
