syntax = "proto3";

package cluster_test;

service ClusterTest {
  // Performs a health check to ensure the test is at least running.
  rpc HealthCheck(HealthCheckRequest) returns (HealthCheckResponse) {}

  // Executes a test on a standalone board.
  rpc Execute(ExecuteRequest) returns (stream ExecuteResponse) {}
}

// HealthCheck
message HealthCheckRequest {}
message HealthCheckResponse {}

message StepInfo {
  int32 sequence = 1;
  string name = 2;
  string description = 3;
}
  
message TestInfo {
  string uuid = 1;
  string name = 2;
  string description = 3;
  repeated StepInfo steps = 4;
}

message TestStepResult {
  // User populated fields
  string execError = 2;             // Exec error 
  bool success = 3; 
  string detailedResult = 4;    // Optionally include detailed logs or results of the step.
  
  // Application populated fields
  int32 runnerId = 5; 
  int32 progressPercentage = 6; // Progress of the test execution as a whole.
  string timestamp = 7;         // Timestamp of the update, useful for logs and tracking.
}

// Messages for executing tests on panel boards
message ExecuteRequest {
  string config = 1;            // The UUID of the test we want to run in this cluster
}

message ExecuteResponse {
  repeated TestStepResult results = 3;
}