syntax = "proto3";

package cluster_test;

service ClusterTest {
  // Performs a health check to ensure the test is at least running.
  rpc HealthCheck(HealthCheckRequest) returns (HealthCheckResponse) {}

  // Executes a test on a standalone board.
  rpc ExecuteTest(ExecuteTestRequest) returns (stream ExecuteTestResponse) {}
}

// HealthCheck
message HealthCheckRequest {}
message HealthCheckResponse {}

message StepInfo {
  int32 sequence = 1;
  string name = 2;
  string description = 3;
}
  
message TestInfo {
  string uuid = 1;
  string name = 2;
  string description = 3;
  repeated StepInfo steps = 4;
}

message TestStepResult {
  // User populated fields
  bool execOk = 1;
  string error = 2;
  bool success = 3; 
  string detailedResult = 4;    // Optionally include detailed logs or results of the step.
  
  // Application populated fields
  int32 runnerId = 5; 
  int32 progressPercentage = 6; // Progress of the test execution as a whole.
  string timestamp = 7;         // Timestamp of the update, useful for logs and tracking.
}

// Messages for executing tests on panel boards
message ExecuteTestRequest {
  string testId = 1;
  repeated int32 runnerIds = 2; // Specifies which boards in the panel to test. Empty means test all.
}

message ExecuteTestResponse {
  string instance = 1;
  int32 sequence = 2;
  repeated TestStepResult results = 3;
}