"""Component base class: typed pin access over immutable PinSpecs.

A Component subclass declares its identity and pins at class level
(generated by the ingestion factory, or hand-written for tests/simple
parts). Instantiating it creates per-instance `Pin` objects that carry
mutable net state.
"""

from __future__ import annotations

import keyword
import re
from dataclasses import dataclass, field

from .model import (
    ElectricalType,
    FootprintRef,
    PinRole,
    PinSpec,
    SourcingInfo,
    UnitDef,
    UnitStrategy,
)
from .net import Net


def sanitize_pin_name(name: str) -> str:
    """Deterministic pin-name → Python-identifier mapping.

    Rules (mirrored by codegen): non-alphanumerics become underscores,
    a leading digit gets a `V` prefix (3V3 → V3V3), Python keywords get
    a trailing underscore.
    """
    ident = re.sub(r"[^0-9A-Za-z_]", "_", name)
    if ident and ident[0].isdigit():
        ident = "V" + ident
    if keyword.iskeyword(ident):
        ident += "_"
    return ident


@dataclass(eq=False)
class Pin:
    """Runtime pin: an instance-bound view of a PinSpec plus net state."""

    spec: PinSpec
    owner: "Component"
    net: Net | None = field(default=None)

    @property
    def pad(self) -> str:
        return self.spec.pad

    @property
    def name(self) -> str:
        return self.spec.name

    @property
    def etype(self) -> ElectricalType:
        return self.spec.etype

    @property
    def role(self) -> PinRole:
        return self.spec.role

    @property
    def owner_ref(self) -> str:
        return self.owner.ref or type(self.owner).__name__

    def __repr__(self) -> str:
        return f"Pin({self.owner_ref}.{self.name} pad={self.pad})"


class Component:
    """Base class for all typed components.

    Class-level declaration (subclasses set these):
        part_name         human part name; defaults from lib_id
        lib_id            "Library:Part" KiCad symbol id
        reference_prefix  "U", "C", "R", ...
        description       one-line description
        footprint         FootprintRef | None
        sourcing          SourcingInfo
        datasheet         URL
        model_3d          resolved 3D asset path ("" if none)
        unit_strategy     UnitStrategy.SINGLE | EXPLICIT
        unit_plan         tuple[UnitDef, ...] (EXPLICIT only)
        orientation_hint  "" | "hub"  (layout: bidirectional pin side)
        _PIN_SPECS        tuple[PinSpec, ...]
    """

    part_name: str = ""
    lib_id: str = ""
    reference_prefix: str = "U"
    description: str = ""
    footprint: FootprintRef | None = None
    sourcing: SourcingInfo = SourcingInfo()
    datasheet: str = ""
    model_3d: str = ""
    unit_strategy: UnitStrategy = UnitStrategy.SINGLE
    unit_plan: tuple[UnitDef, ...] = ()
    orientation_hint: str = ""
    _PIN_SPECS: tuple[PinSpec, ...] = ()

    def __init_subclass__(cls, **kwargs) -> None:
        super().__init_subclass__(**kwargs)
        if not cls._PIN_SPECS:
            return  # abstract intermediate classes are fine
        pads = [s.pad for s in cls._PIN_SPECS]
        if len(pads) != len(set(pads)):
            dupes = sorted({p for p in pads if pads.count(p) > 1})
            raise TypeError(f"{cls.__name__}: duplicate pads {dupes}")
        if cls.unit_strategy is UnitStrategy.EXPLICIT:
            plan_pads = [p for u in cls.unit_plan for p in u.pads]
            if sorted(plan_pads) != sorted(pads):
                missing = set(pads) - set(plan_pads)
                extra = set(plan_pads) - set(pads)
                raise TypeError(
                    f"{cls.__name__}: unit_plan must cover every pad exactly "
                    f"once (missing={sorted(missing)}, unknown={sorted(extra)})"
                )
        if not cls.part_name:
            cls.part_name = cls.lib_id.split(":")[-1] if cls.lib_id else cls.__name__

    def __init__(self) -> None:
        self.ref: str = ""  # assigned by Design.add()
        self._pins_by_pad: dict[str, Pin] = {
            spec.pad: Pin(spec=spec, owner=self) for spec in self._PIN_SPECS
        }
        # name → pads (a name may repeat: GND on many pads)
        self._pads_by_name: dict[str, list[str]] = {}
        for spec in self._PIN_SPECS:
            self._pads_by_name.setdefault(spec.name, []).append(spec.pad)
        self._pads_by_ident: dict[str, list[str]] = {}
        for name, name_pads in self._pads_by_name.items():
            self._pads_by_ident.setdefault(sanitize_pin_name(name), []).extend(name_pads)

    # ── pin access ──────────────────────────────────────────────────────────

    @property
    def pins(self) -> tuple[Pin, ...]:
        return tuple(self._pins_by_pad.values())

    def _pin(self, pad: str) -> Pin:
        return self._pins_by_pad[pad]

    def _pins_named(self, name: str) -> tuple[Pin, ...]:
        return tuple(self._pins_by_pad[p] for p in self._pads_by_name.get(name, ()))

    def pin(self, key: str) -> Pin:
        """Look up a single pin by name or pad. Raises on ambiguity."""
        pads = self._pads_by_name.get(key)
        if pads is None and key in self._pins_by_pad:
            return self._pins_by_pad[key]
        if pads is None:
            raise KeyError(f"{type(self).__name__}: no pin named or numbered {key!r}")
        if len(pads) > 1:
            raise KeyError(
                f"{type(self).__name__}: pin name {key!r} matches pads {pads}; "
                f"use pins_named() or a pad number"
            )
        return self._pins_by_pad[pads[0]]

    def pins_named(self, name: str) -> tuple[Pin, ...]:
        return self._pins_named(name)

    def gpio(self, n: int) -> Pin:
        """MCU helper: pin by logical GPIO number."""
        for p in self.pins:
            if p.spec.gpio == n:
                return p
        raise KeyError(f"{type(self).__name__}: no GPIO {n}")

    def __getattr__(self, ident: str) -> Pin | tuple[Pin, ...]:
        # Dynamic sanitized-name accessors (codegen adds explicit properties
        # on generated classes; this makes hand-written classes ergonomic too).
        if ident.startswith("_"):
            raise AttributeError(ident)
        pads = self.__dict__.get("_pads_by_ident", {}).get(ident)
        if not pads:
            raise AttributeError(f"{type(self).__name__} has no pin {ident!r}")
        if len(pads) == 1:
            return self._pins_by_pad[pads[0]]
        return tuple(self._pins_by_pad[p] for p in pads)

    # ── units ───────────────────────────────────────────────────────────────

    def units(self) -> tuple[UnitDef, ...]:
        """Effective unit plan (SINGLE strategy synthesizes one unit)."""
        if self.unit_strategy is UnitStrategy.EXPLICIT:
            return self.unit_plan
        return (UnitDef(name=self.part_name or type(self).__name__,
                        pads=tuple(s.pad for s in self._PIN_SPECS)),)

    def unit_of(self, pad: str) -> int:
        """1-based unit id containing the given pad."""
        for i, u in enumerate(self.units(), start=1):
            if pad in u.pads:
                return i
        raise KeyError(f"pad {pad!r} not in any unit")

    def __repr__(self) -> str:
        return f"{type(self).__name__}(ref={self.ref or '?'})"
