name: on-push

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: on-push-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  check:
    name: affected-check
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gophersys/base:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Run affected-check
        env:
          NX_BASE: origin/main~1
        run: bash .ci/ctl.sh affected-check
