/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_MTIB_CS_PI_PB_H_INCLUDED
#define PB_MTIB_CS_PI_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Gpio */
typedef enum _Gpio {
    Gpio_GPIO_0 = 0,
    Gpio_GPIO_1 = 1,
    Gpio_GPIO_2 = 2,
    Gpio_GPIO_3 = 3,
    Gpio_GPIO_4 = 4,
    Gpio_GPIO_5 = 5,
    Gpio_GPIO_6 = 6
} Gpio;

typedef enum _GpioType {
    GpioType_GPIO_INPUT = 0,
    GpioType_GPIO_OUTPUT = 1
} GpioType;

typedef enum _GpioResistorConfig {
    GpioResistorConfig_GPIO_RESISTOR_PULL_UP = 0,
    GpioResistorConfig_GPIO_RESISTOR_PULL_DOWN = 1
} GpioResistorConfig;

/* Adc */
typedef enum _AdcChannel {
    AdcChannel_ADC_CHANNEL_0 = 0,
    AdcChannel_ADC_CHANNEL_1 = 1,
    AdcChannel_ADC_CHANNEL_2 = 2,
    AdcChannel_ADC_CHANNEL_3 = 3,
    AdcChannel_ADC_CHANNEL_4 = 4,
    AdcChannel_ADC_CHANNEL_5 = 5,
    AdcChannel_ADC_CHANNEL_6 = 6,
    AdcChannel_ADC_CHANNEL_7 = 7
} AdcChannel;

/* Uart */
typedef enum _UartPort {
    UartPort_UART_PORT_0 = 0,
    UartPort_UART_PORT_1 = 1
} UartPort;

typedef enum _UartBaudRate {
    UartBaudRate_UART_BAUDRATE_9600 = 0,
    UartBaudRate_UART_BAUDRATE_115200 = 1,
    UartBaudRate_UART_BAUDRATE_576000 = 2,
    UartBaudRate_UART_BAUDRATE_921600 = 3
} UartBaudRate;

/* Struct definitions */
typedef struct _GpioConfigRequest {
    Gpio gpio;
    GpioType type;
    GpioResistorConfig resistor;
} GpioConfigRequest;

typedef struct _GpioConfigResponse {
    bool success;
    pb_callback_t error;
} GpioConfigResponse;

typedef struct _GpioWriteRequest {
    Gpio gpio;
    bool state;
} GpioWriteRequest;

typedef struct _GpioWriteResponse {
    bool success;
    pb_callback_t error;
} GpioWriteResponse;

typedef struct _GpioReadRequest {
    Gpio gpio;
} GpioReadRequest;

typedef struct _GpioReadResponse {
    bool success;
    pb_callback_t error;
    bool state;
} GpioReadResponse;

typedef struct _AdcReadRequest {
    AdcChannel channel;
    int32_t delayMs;
} AdcReadRequest;

typedef struct _AdcReadResponse {
    bool success;
    pb_callback_t error;
    double voltage;
} AdcReadResponse;

typedef struct _AdcReadAllRequest {
    int32_t delayMs;
} AdcReadAllRequest;

typedef struct _AdcReadAllResponse {
    bool success;
    pb_callback_t error;
    pb_callback_t voltage;
} AdcReadAllResponse;

typedef struct _UartConfigRequest {
    UartPort port;
    UartBaudRate baud;
    bool enable;
} UartConfigRequest;

typedef struct _UartConfigResponse {
    bool success;
    pb_callback_t error;
} UartConfigResponse;

typedef struct _UartStreamRequest {
    pb_callback_t data;
} UartStreamRequest;

typedef struct _UartStreamResponse {
    pb_callback_t data;
    bool success; /* Indicates if the read was successful */
    pb_callback_t error;
} UartStreamResponse;

/* Firmware Update */
typedef struct _ListFwFilesRequest {
    char dummy_field;
} ListFwFilesRequest;

typedef struct _FwFileInfo {
    pb_callback_t name;
    int64_t size_kb;
    pb_callback_t sha256_digest;
} FwFileInfo;

typedef struct _ListFwFilesResponse {
    pb_callback_t files;
} ListFwFilesResponse;

typedef struct _UploadFwFileRequest {
    pb_callback_t filename;
    pb_callback_t content;
} UploadFwFileRequest;

typedef struct _UploadFwFileResponse {
    bool success;
    pb_callback_t error;
    pb_callback_t sha256_digest;
} UploadFwFileResponse;

typedef struct _DeleteFwFileRequest {
    pb_callback_t filename;
} DeleteFwFileRequest;

typedef struct _DeleteFwFileResponse {
    bool success;
    pb_callback_t error;
} DeleteFwFileResponse;

/* J Links */
typedef struct _ListJLinksRequest {
    char dummy_field;
} ListJLinksRequest;

typedef struct _JLinkInfo {
    pb_callback_t serialNumber;
    int32_t usbPort;
} JLinkInfo;

typedef struct _ListJLinksResponse {
    bool success;
    pb_callback_t error;
    pb_callback_t jlink;
} ListJLinksResponse;

/* Flash HEX files */
typedef struct _FlashHexFileRequest {
    pb_callback_t fileName;
    bool has_jlink;
    JLinkInfo jlink;
    bool isModemFw;
} FlashHexFileRequest;

typedef struct _FlashHexFileResponse {
    bool success;
    pb_callback_t error;
    int32_t timeMs;
} FlashHexFileResponse;

/* Dut */
typedef struct _DutPowerEnableRequest {
    bool enable;
} DutPowerEnableRequest;

typedef struct _DutPowerEnableResponse {
    bool success;
    pb_callback_t error;
} DutPowerEnableResponse;

typedef struct _DutVoltageSetRequest {
    double voltage;
} DutVoltageSetRequest;

typedef struct _DutVoltageSetResponse {
    bool success;
    pb_callback_t error;
} DutVoltageSetResponse;

typedef struct _DutCurrentReadRequest {
    char dummy_field;
} DutCurrentReadRequest;

typedef struct _DutCurrentReadResponse {
    bool success;
    pb_callback_t error;
    int32_t current_ma;
} DutCurrentReadResponse;

typedef struct _DutVoltageReadRequest {
    char dummy_field;
} DutVoltageReadRequest;

typedef struct _DutVoltageReadResponse {
    bool success;
    pb_callback_t error;
    int32_t voltage_mv;
} DutVoltageReadResponse;

typedef struct _DutPowerReadRequest {
    char dummy_field;
} DutPowerReadRequest;

typedef struct _DutPowerReadResponse {
    bool success;
    pb_callback_t error;
    int32_t power_mw;
} DutPowerReadResponse;

/* Sensors */
typedef struct _AltimeterReadRequest {
    char dummy_field;
} AltimeterReadRequest;

typedef struct _AltimeterReadResponse {
    bool success;
    pb_callback_t error;
    double temperature_f;
    double pressure_hg;
    double altitude_ft;
} AltimeterReadResponse;

typedef struct _AccelReadRequest {
    char dummy_field;
} AccelReadRequest;

typedef struct _AccelReadResponse {
    bool success;
    pb_callback_t error;
    double x;
    double y;
    double z;
} AccelReadResponse;

typedef struct _AccelReadMaxRequest {
    char dummy_field;
} AccelReadMaxRequest;

typedef struct _AccelReadMaxResponse {
    bool success;
    pb_callback_t error;
    double max;
} AccelReadMaxResponse;

typedef struct _EepromReadRequest {
    int32_t address;
    int32_t len;
} EepromReadRequest;

typedef struct _EepromReadResponse {
    bool success;
    pb_callback_t error;
    pb_callback_t data;
} EepromReadResponse;

typedef struct _EepromWriteRequest {
    pb_callback_t buffer;
    int32_t address;
    int32_t len;
} EepromWriteRequest;

typedef struct _EepromWriteResponse {
    bool success;
    pb_callback_t error;
} EepromWriteResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Gpio_MIN Gpio_GPIO_0
#define _Gpio_MAX Gpio_GPIO_6
#define _Gpio_ARRAYSIZE ((Gpio)(Gpio_GPIO_6+1))

#define _GpioType_MIN GpioType_GPIO_INPUT
#define _GpioType_MAX GpioType_GPIO_OUTPUT
#define _GpioType_ARRAYSIZE ((GpioType)(GpioType_GPIO_OUTPUT+1))

#define _GpioResistorConfig_MIN GpioResistorConfig_GPIO_RESISTOR_PULL_UP
#define _GpioResistorConfig_MAX GpioResistorConfig_GPIO_RESISTOR_PULL_DOWN
#define _GpioResistorConfig_ARRAYSIZE ((GpioResistorConfig)(GpioResistorConfig_GPIO_RESISTOR_PULL_DOWN+1))

#define _AdcChannel_MIN AdcChannel_ADC_CHANNEL_0
#define _AdcChannel_MAX AdcChannel_ADC_CHANNEL_7
#define _AdcChannel_ARRAYSIZE ((AdcChannel)(AdcChannel_ADC_CHANNEL_7+1))

#define _UartPort_MIN UartPort_UART_PORT_0
#define _UartPort_MAX UartPort_UART_PORT_1
#define _UartPort_ARRAYSIZE ((UartPort)(UartPort_UART_PORT_1+1))

#define _UartBaudRate_MIN UartBaudRate_UART_BAUDRATE_9600
#define _UartBaudRate_MAX UartBaudRate_UART_BAUDRATE_921600
#define _UartBaudRate_ARRAYSIZE ((UartBaudRate)(UartBaudRate_UART_BAUDRATE_921600+1))

#define GpioConfigRequest_gpio_ENUMTYPE Gpio
#define GpioConfigRequest_type_ENUMTYPE GpioType
#define GpioConfigRequest_resistor_ENUMTYPE GpioResistorConfig


#define GpioWriteRequest_gpio_ENUMTYPE Gpio


#define GpioReadRequest_gpio_ENUMTYPE Gpio


#define AdcReadRequest_channel_ENUMTYPE AdcChannel




#define UartConfigRequest_port_ENUMTYPE UartPort
#define UartConfigRequest_baud_ENUMTYPE UartBaudRate





































/* Initializer values for message structs */
#define GpioConfigRequest_init_default           {_Gpio_MIN, _GpioType_MIN, _GpioResistorConfig_MIN}
#define GpioConfigResponse_init_default          {0, {{NULL}, NULL}}
#define GpioWriteRequest_init_default            {_Gpio_MIN, 0}
#define GpioWriteResponse_init_default           {0, {{NULL}, NULL}}
#define GpioReadRequest_init_default             {_Gpio_MIN}
#define GpioReadResponse_init_default            {0, {{NULL}, NULL}, 0}
#define AdcReadRequest_init_default              {_AdcChannel_MIN, 0}
#define AdcReadResponse_init_default             {0, {{NULL}, NULL}, 0}
#define AdcReadAllRequest_init_default           {0}
#define AdcReadAllResponse_init_default          {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define UartConfigRequest_init_default           {_UartPort_MIN, _UartBaudRate_MIN, 0}
#define UartConfigResponse_init_default          {0, {{NULL}, NULL}}
#define UartStreamRequest_init_default           {{{NULL}, NULL}}
#define UartStreamResponse_init_default          {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define ListFwFilesRequest_init_default          {0}
#define FwFileInfo_init_default                  {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define ListFwFilesResponse_init_default         {{{NULL}, NULL}}
#define UploadFwFileRequest_init_default         {{{NULL}, NULL}, {{NULL}, NULL}}
#define UploadFwFileResponse_init_default        {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define DeleteFwFileRequest_init_default         {{{NULL}, NULL}}
#define DeleteFwFileResponse_init_default        {0, {{NULL}, NULL}}
#define ListJLinksRequest_init_default           {0}
#define JLinkInfo_init_default                   {{{NULL}, NULL}, 0}
#define ListJLinksResponse_init_default          {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define FlashHexFileRequest_init_default         {{{NULL}, NULL}, false, JLinkInfo_init_default, 0}
#define FlashHexFileResponse_init_default        {0, {{NULL}, NULL}, 0}
#define DutPowerEnableRequest_init_default       {0}
#define DutPowerEnableResponse_init_default      {0, {{NULL}, NULL}}
#define DutVoltageSetRequest_init_default        {0}
#define DutVoltageSetResponse_init_default       {0, {{NULL}, NULL}}
#define DutCurrentReadRequest_init_default       {0}
#define DutCurrentReadResponse_init_default      {0, {{NULL}, NULL}, 0}
#define DutVoltageReadRequest_init_default       {0}
#define DutVoltageReadResponse_init_default      {0, {{NULL}, NULL}, 0}
#define DutPowerReadRequest_init_default         {0}
#define DutPowerReadResponse_init_default        {0, {{NULL}, NULL}, 0}
#define AltimeterReadRequest_init_default        {0}
#define AltimeterReadResponse_init_default       {0, {{NULL}, NULL}, 0, 0, 0}
#define AccelReadRequest_init_default            {0}
#define AccelReadResponse_init_default           {0, {{NULL}, NULL}, 0, 0, 0}
#define AccelReadMaxRequest_init_default         {0}
#define AccelReadMaxResponse_init_default        {0, {{NULL}, NULL}, 0}
#define EepromReadRequest_init_default           {0, 0}
#define EepromReadResponse_init_default          {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define EepromWriteRequest_init_default          {{{NULL}, NULL}, 0, 0}
#define EepromWriteResponse_init_default         {0, {{NULL}, NULL}}
#define GpioConfigRequest_init_zero              {_Gpio_MIN, _GpioType_MIN, _GpioResistorConfig_MIN}
#define GpioConfigResponse_init_zero             {0, {{NULL}, NULL}}
#define GpioWriteRequest_init_zero               {_Gpio_MIN, 0}
#define GpioWriteResponse_init_zero              {0, {{NULL}, NULL}}
#define GpioReadRequest_init_zero                {_Gpio_MIN}
#define GpioReadResponse_init_zero               {0, {{NULL}, NULL}, 0}
#define AdcReadRequest_init_zero                 {_AdcChannel_MIN, 0}
#define AdcReadResponse_init_zero                {0, {{NULL}, NULL}, 0}
#define AdcReadAllRequest_init_zero              {0}
#define AdcReadAllResponse_init_zero             {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define UartConfigRequest_init_zero              {_UartPort_MIN, _UartBaudRate_MIN, 0}
#define UartConfigResponse_init_zero             {0, {{NULL}, NULL}}
#define UartStreamRequest_init_zero              {{{NULL}, NULL}}
#define UartStreamResponse_init_zero             {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define ListFwFilesRequest_init_zero             {0}
#define FwFileInfo_init_zero                     {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define ListFwFilesResponse_init_zero            {{{NULL}, NULL}}
#define UploadFwFileRequest_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}}
#define UploadFwFileResponse_init_zero           {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define DeleteFwFileRequest_init_zero            {{{NULL}, NULL}}
#define DeleteFwFileResponse_init_zero           {0, {{NULL}, NULL}}
#define ListJLinksRequest_init_zero              {0}
#define JLinkInfo_init_zero                      {{{NULL}, NULL}, 0}
#define ListJLinksResponse_init_zero             {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define FlashHexFileRequest_init_zero            {{{NULL}, NULL}, false, JLinkInfo_init_zero, 0}
#define FlashHexFileResponse_init_zero           {0, {{NULL}, NULL}, 0}
#define DutPowerEnableRequest_init_zero          {0}
#define DutPowerEnableResponse_init_zero         {0, {{NULL}, NULL}}
#define DutVoltageSetRequest_init_zero           {0}
#define DutVoltageSetResponse_init_zero          {0, {{NULL}, NULL}}
#define DutCurrentReadRequest_init_zero          {0}
#define DutCurrentReadResponse_init_zero         {0, {{NULL}, NULL}, 0}
#define DutVoltageReadRequest_init_zero          {0}
#define DutVoltageReadResponse_init_zero         {0, {{NULL}, NULL}, 0}
#define DutPowerReadRequest_init_zero            {0}
#define DutPowerReadResponse_init_zero           {0, {{NULL}, NULL}, 0}
#define AltimeterReadRequest_init_zero           {0}
#define AltimeterReadResponse_init_zero          {0, {{NULL}, NULL}, 0, 0, 0}
#define AccelReadRequest_init_zero               {0}
#define AccelReadResponse_init_zero              {0, {{NULL}, NULL}, 0, 0, 0}
#define AccelReadMaxRequest_init_zero            {0}
#define AccelReadMaxResponse_init_zero           {0, {{NULL}, NULL}, 0}
#define EepromReadRequest_init_zero              {0, 0}
#define EepromReadResponse_init_zero             {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define EepromWriteRequest_init_zero             {{{NULL}, NULL}, 0, 0}
#define EepromWriteResponse_init_zero            {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define GpioConfigRequest_gpio_tag               1
#define GpioConfigRequest_type_tag               2
#define GpioConfigRequest_resistor_tag           3
#define GpioConfigResponse_success_tag           1
#define GpioConfigResponse_error_tag             2
#define GpioWriteRequest_gpio_tag                1
#define GpioWriteRequest_state_tag               2
#define GpioWriteResponse_success_tag            1
#define GpioWriteResponse_error_tag              2
#define GpioReadRequest_gpio_tag                 1
#define GpioReadResponse_success_tag             1
#define GpioReadResponse_error_tag               2
#define GpioReadResponse_state_tag               3
#define AdcReadRequest_channel_tag               1
#define AdcReadRequest_delayMs_tag               2
#define AdcReadResponse_success_tag              1
#define AdcReadResponse_error_tag                2
#define AdcReadResponse_voltage_tag              3
#define AdcReadAllRequest_delayMs_tag            1
#define AdcReadAllResponse_success_tag           1
#define AdcReadAllResponse_error_tag             2
#define AdcReadAllResponse_voltage_tag           3
#define UartConfigRequest_port_tag               1
#define UartConfigRequest_baud_tag               2
#define UartConfigRequest_enable_tag             3
#define UartConfigResponse_success_tag           1
#define UartConfigResponse_error_tag             2
#define UartStreamRequest_data_tag               1
#define UartStreamResponse_data_tag              1
#define UartStreamResponse_success_tag           2
#define UartStreamResponse_error_tag             3
#define FwFileInfo_name_tag                      1
#define FwFileInfo_size_kb_tag                   2
#define FwFileInfo_sha256_digest_tag             3
#define ListFwFilesResponse_files_tag            1
#define UploadFwFileRequest_filename_tag         1
#define UploadFwFileRequest_content_tag          2
#define UploadFwFileResponse_success_tag         1
#define UploadFwFileResponse_error_tag           2
#define UploadFwFileResponse_sha256_digest_tag   3
#define DeleteFwFileRequest_filename_tag         1
#define DeleteFwFileResponse_success_tag         1
#define DeleteFwFileResponse_error_tag           2
#define JLinkInfo_serialNumber_tag               1
#define JLinkInfo_usbPort_tag                    2
#define ListJLinksResponse_success_tag           1
#define ListJLinksResponse_error_tag             2
#define ListJLinksResponse_jlink_tag             3
#define FlashHexFileRequest_fileName_tag         1
#define FlashHexFileRequest_jlink_tag            2
#define FlashHexFileRequest_isModemFw_tag        3
#define FlashHexFileResponse_success_tag         1
#define FlashHexFileResponse_error_tag           2
#define FlashHexFileResponse_timeMs_tag          3
#define DutPowerEnableRequest_enable_tag         1
#define DutPowerEnableResponse_success_tag       1
#define DutPowerEnableResponse_error_tag         2
#define DutVoltageSetRequest_voltage_tag         1
#define DutVoltageSetResponse_success_tag        1
#define DutVoltageSetResponse_error_tag          2
#define DutCurrentReadResponse_success_tag       1
#define DutCurrentReadResponse_error_tag         2
#define DutCurrentReadResponse_current_ma_tag    3
#define DutVoltageReadResponse_success_tag       1
#define DutVoltageReadResponse_error_tag         2
#define DutVoltageReadResponse_voltage_mv_tag    3
#define DutPowerReadResponse_success_tag         1
#define DutPowerReadResponse_error_tag           2
#define DutPowerReadResponse_power_mw_tag        3
#define AltimeterReadResponse_success_tag        1
#define AltimeterReadResponse_error_tag          2
#define AltimeterReadResponse_temperature_f_tag  3
#define AltimeterReadResponse_pressure_hg_tag    4
#define AltimeterReadResponse_altitude_ft_tag    5
#define AccelReadResponse_success_tag            1
#define AccelReadResponse_error_tag              2
#define AccelReadResponse_x_tag                  3
#define AccelReadResponse_y_tag                  4
#define AccelReadResponse_z_tag                  5
#define AccelReadMaxResponse_success_tag         1
#define AccelReadMaxResponse_error_tag           2
#define AccelReadMaxResponse_max_tag             3
#define EepromReadRequest_address_tag            2
#define EepromReadRequest_len_tag                3
#define EepromReadResponse_success_tag           1
#define EepromReadResponse_error_tag             2
#define EepromReadResponse_data_tag              3
#define EepromWriteRequest_buffer_tag            1
#define EepromWriteRequest_address_tag           2
#define EepromWriteRequest_len_tag               3
#define EepromWriteResponse_success_tag          1
#define EepromWriteResponse_error_tag            2

/* Struct field encoding specification for nanopb */
#define GpioConfigRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    gpio,              1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2) \
X(a, STATIC,   SINGULAR, UENUM,    resistor,          3)
#define GpioConfigRequest_CALLBACK NULL
#define GpioConfigRequest_DEFAULT NULL

#define GpioConfigResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2)
#define GpioConfigResponse_CALLBACK pb_default_field_callback
#define GpioConfigResponse_DEFAULT NULL

#define GpioWriteRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    gpio,              1) \
X(a, STATIC,   SINGULAR, BOOL,     state,             2)
#define GpioWriteRequest_CALLBACK NULL
#define GpioWriteRequest_DEFAULT NULL

#define GpioWriteResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2)
#define GpioWriteResponse_CALLBACK pb_default_field_callback
#define GpioWriteResponse_DEFAULT NULL

#define GpioReadRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    gpio,              1)
#define GpioReadRequest_CALLBACK NULL
#define GpioReadRequest_DEFAULT NULL

#define GpioReadResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, STATIC,   SINGULAR, BOOL,     state,             3)
#define GpioReadResponse_CALLBACK pb_default_field_callback
#define GpioReadResponse_DEFAULT NULL

#define AdcReadRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    channel,           1) \
X(a, STATIC,   SINGULAR, INT32,    delayMs,           2)
#define AdcReadRequest_CALLBACK NULL
#define AdcReadRequest_DEFAULT NULL

#define AdcReadResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, STATIC,   SINGULAR, DOUBLE,   voltage,           3)
#define AdcReadResponse_CALLBACK pb_default_field_callback
#define AdcReadResponse_DEFAULT NULL

#define AdcReadAllRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    delayMs,           1)
#define AdcReadAllRequest_CALLBACK NULL
#define AdcReadAllRequest_DEFAULT NULL

#define AdcReadAllResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, CALLBACK, REPEATED, DOUBLE,   voltage,           3)
#define AdcReadAllResponse_CALLBACK pb_default_field_callback
#define AdcReadAllResponse_DEFAULT NULL

#define UartConfigRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    port,              1) \
X(a, STATIC,   SINGULAR, UENUM,    baud,              2) \
X(a, STATIC,   SINGULAR, BOOL,     enable,            3)
#define UartConfigRequest_CALLBACK NULL
#define UartConfigRequest_DEFAULT NULL

#define UartConfigResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2)
#define UartConfigResponse_CALLBACK pb_default_field_callback
#define UartConfigResponse_DEFAULT NULL

#define UartStreamRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              1)
#define UartStreamRequest_CALLBACK pb_default_field_callback
#define UartStreamRequest_DEFAULT NULL

#define UartStreamResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2) \
X(a, CALLBACK, SINGULAR, STRING,   error,             3)
#define UartStreamResponse_CALLBACK pb_default_field_callback
#define UartStreamResponse_DEFAULT NULL

#define ListFwFilesRequest_FIELDLIST(X, a) \

#define ListFwFilesRequest_CALLBACK NULL
#define ListFwFilesRequest_DEFAULT NULL

#define FwFileInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, INT64,    size_kb,           2) \
X(a, CALLBACK, SINGULAR, STRING,   sha256_digest,     3)
#define FwFileInfo_CALLBACK pb_default_field_callback
#define FwFileInfo_DEFAULT NULL

#define ListFwFilesResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  files,             1)
#define ListFwFilesResponse_CALLBACK pb_default_field_callback
#define ListFwFilesResponse_DEFAULT NULL
#define ListFwFilesResponse_files_MSGTYPE FwFileInfo

#define UploadFwFileRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   filename,          1) \
X(a, CALLBACK, SINGULAR, BYTES,    content,           2)
#define UploadFwFileRequest_CALLBACK pb_default_field_callback
#define UploadFwFileRequest_DEFAULT NULL

#define UploadFwFileResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, CALLBACK, SINGULAR, STRING,   sha256_digest,     3)
#define UploadFwFileResponse_CALLBACK pb_default_field_callback
#define UploadFwFileResponse_DEFAULT NULL

#define DeleteFwFileRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   filename,          1)
#define DeleteFwFileRequest_CALLBACK pb_default_field_callback
#define DeleteFwFileRequest_DEFAULT NULL

#define DeleteFwFileResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2)
#define DeleteFwFileResponse_CALLBACK pb_default_field_callback
#define DeleteFwFileResponse_DEFAULT NULL

#define ListJLinksRequest_FIELDLIST(X, a) \

#define ListJLinksRequest_CALLBACK NULL
#define ListJLinksRequest_DEFAULT NULL

#define JLinkInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   serialNumber,      1) \
X(a, STATIC,   SINGULAR, INT32,    usbPort,           2)
#define JLinkInfo_CALLBACK pb_default_field_callback
#define JLinkInfo_DEFAULT NULL

#define ListJLinksResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, CALLBACK, REPEATED, MESSAGE,  jlink,             3)
#define ListJLinksResponse_CALLBACK pb_default_field_callback
#define ListJLinksResponse_DEFAULT NULL
#define ListJLinksResponse_jlink_MSGTYPE JLinkInfo

#define FlashHexFileRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   fileName,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  jlink,             2) \
X(a, STATIC,   SINGULAR, BOOL,     isModemFw,         3)
#define FlashHexFileRequest_CALLBACK pb_default_field_callback
#define FlashHexFileRequest_DEFAULT NULL
#define FlashHexFileRequest_jlink_MSGTYPE JLinkInfo

#define FlashHexFileResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, STATIC,   SINGULAR, INT32,    timeMs,            3)
#define FlashHexFileResponse_CALLBACK pb_default_field_callback
#define FlashHexFileResponse_DEFAULT NULL

#define DutPowerEnableRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enable,            1)
#define DutPowerEnableRequest_CALLBACK NULL
#define DutPowerEnableRequest_DEFAULT NULL

#define DutPowerEnableResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2)
#define DutPowerEnableResponse_CALLBACK pb_default_field_callback
#define DutPowerEnableResponse_DEFAULT NULL

#define DutVoltageSetRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   voltage,           1)
#define DutVoltageSetRequest_CALLBACK NULL
#define DutVoltageSetRequest_DEFAULT NULL

#define DutVoltageSetResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2)
#define DutVoltageSetResponse_CALLBACK pb_default_field_callback
#define DutVoltageSetResponse_DEFAULT NULL

#define DutCurrentReadRequest_FIELDLIST(X, a) \

#define DutCurrentReadRequest_CALLBACK NULL
#define DutCurrentReadRequest_DEFAULT NULL

#define DutCurrentReadResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, STATIC,   SINGULAR, INT32,    current_ma,        3)
#define DutCurrentReadResponse_CALLBACK pb_default_field_callback
#define DutCurrentReadResponse_DEFAULT NULL

#define DutVoltageReadRequest_FIELDLIST(X, a) \

#define DutVoltageReadRequest_CALLBACK NULL
#define DutVoltageReadRequest_DEFAULT NULL

#define DutVoltageReadResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, STATIC,   SINGULAR, INT32,    voltage_mv,        3)
#define DutVoltageReadResponse_CALLBACK pb_default_field_callback
#define DutVoltageReadResponse_DEFAULT NULL

#define DutPowerReadRequest_FIELDLIST(X, a) \

#define DutPowerReadRequest_CALLBACK NULL
#define DutPowerReadRequest_DEFAULT NULL

#define DutPowerReadResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, STATIC,   SINGULAR, INT32,    power_mw,          3)
#define DutPowerReadResponse_CALLBACK pb_default_field_callback
#define DutPowerReadResponse_DEFAULT NULL

#define AltimeterReadRequest_FIELDLIST(X, a) \

#define AltimeterReadRequest_CALLBACK NULL
#define AltimeterReadRequest_DEFAULT NULL

#define AltimeterReadResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, STATIC,   SINGULAR, DOUBLE,   temperature_f,     3) \
X(a, STATIC,   SINGULAR, DOUBLE,   pressure_hg,       4) \
X(a, STATIC,   SINGULAR, DOUBLE,   altitude_ft,       5)
#define AltimeterReadResponse_CALLBACK pb_default_field_callback
#define AltimeterReadResponse_DEFAULT NULL

#define AccelReadRequest_FIELDLIST(X, a) \

#define AccelReadRequest_CALLBACK NULL
#define AccelReadRequest_DEFAULT NULL

#define AccelReadResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, STATIC,   SINGULAR, DOUBLE,   x,                 3) \
X(a, STATIC,   SINGULAR, DOUBLE,   y,                 4) \
X(a, STATIC,   SINGULAR, DOUBLE,   z,                 5)
#define AccelReadResponse_CALLBACK pb_default_field_callback
#define AccelReadResponse_DEFAULT NULL

#define AccelReadMaxRequest_FIELDLIST(X, a) \

#define AccelReadMaxRequest_CALLBACK NULL
#define AccelReadMaxRequest_DEFAULT NULL

#define AccelReadMaxResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, STATIC,   SINGULAR, DOUBLE,   max,               3)
#define AccelReadMaxResponse_CALLBACK pb_default_field_callback
#define AccelReadMaxResponse_DEFAULT NULL

#define EepromReadRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    address,           2) \
X(a, STATIC,   SINGULAR, INT32,    len,               3)
#define EepromReadRequest_CALLBACK NULL
#define EepromReadRequest_DEFAULT NULL

#define EepromReadResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              3)
#define EepromReadResponse_CALLBACK pb_default_field_callback
#define EepromReadResponse_DEFAULT NULL

#define EepromWriteRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    buffer,            1) \
X(a, STATIC,   SINGULAR, INT32,    address,           2) \
X(a, STATIC,   SINGULAR, INT32,    len,               3)
#define EepromWriteRequest_CALLBACK pb_default_field_callback
#define EepromWriteRequest_DEFAULT NULL

#define EepromWriteResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2)
#define EepromWriteResponse_CALLBACK pb_default_field_callback
#define EepromWriteResponse_DEFAULT NULL

extern const pb_msgdesc_t GpioConfigRequest_msg;
extern const pb_msgdesc_t GpioConfigResponse_msg;
extern const pb_msgdesc_t GpioWriteRequest_msg;
extern const pb_msgdesc_t GpioWriteResponse_msg;
extern const pb_msgdesc_t GpioReadRequest_msg;
extern const pb_msgdesc_t GpioReadResponse_msg;
extern const pb_msgdesc_t AdcReadRequest_msg;
extern const pb_msgdesc_t AdcReadResponse_msg;
extern const pb_msgdesc_t AdcReadAllRequest_msg;
extern const pb_msgdesc_t AdcReadAllResponse_msg;
extern const pb_msgdesc_t UartConfigRequest_msg;
extern const pb_msgdesc_t UartConfigResponse_msg;
extern const pb_msgdesc_t UartStreamRequest_msg;
extern const pb_msgdesc_t UartStreamResponse_msg;
extern const pb_msgdesc_t ListFwFilesRequest_msg;
extern const pb_msgdesc_t FwFileInfo_msg;
extern const pb_msgdesc_t ListFwFilesResponse_msg;
extern const pb_msgdesc_t UploadFwFileRequest_msg;
extern const pb_msgdesc_t UploadFwFileResponse_msg;
extern const pb_msgdesc_t DeleteFwFileRequest_msg;
extern const pb_msgdesc_t DeleteFwFileResponse_msg;
extern const pb_msgdesc_t ListJLinksRequest_msg;
extern const pb_msgdesc_t JLinkInfo_msg;
extern const pb_msgdesc_t ListJLinksResponse_msg;
extern const pb_msgdesc_t FlashHexFileRequest_msg;
extern const pb_msgdesc_t FlashHexFileResponse_msg;
extern const pb_msgdesc_t DutPowerEnableRequest_msg;
extern const pb_msgdesc_t DutPowerEnableResponse_msg;
extern const pb_msgdesc_t DutVoltageSetRequest_msg;
extern const pb_msgdesc_t DutVoltageSetResponse_msg;
extern const pb_msgdesc_t DutCurrentReadRequest_msg;
extern const pb_msgdesc_t DutCurrentReadResponse_msg;
extern const pb_msgdesc_t DutVoltageReadRequest_msg;
extern const pb_msgdesc_t DutVoltageReadResponse_msg;
extern const pb_msgdesc_t DutPowerReadRequest_msg;
extern const pb_msgdesc_t DutPowerReadResponse_msg;
extern const pb_msgdesc_t AltimeterReadRequest_msg;
extern const pb_msgdesc_t AltimeterReadResponse_msg;
extern const pb_msgdesc_t AccelReadRequest_msg;
extern const pb_msgdesc_t AccelReadResponse_msg;
extern const pb_msgdesc_t AccelReadMaxRequest_msg;
extern const pb_msgdesc_t AccelReadMaxResponse_msg;
extern const pb_msgdesc_t EepromReadRequest_msg;
extern const pb_msgdesc_t EepromReadResponse_msg;
extern const pb_msgdesc_t EepromWriteRequest_msg;
extern const pb_msgdesc_t EepromWriteResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GpioConfigRequest_fields &GpioConfigRequest_msg
#define GpioConfigResponse_fields &GpioConfigResponse_msg
#define GpioWriteRequest_fields &GpioWriteRequest_msg
#define GpioWriteResponse_fields &GpioWriteResponse_msg
#define GpioReadRequest_fields &GpioReadRequest_msg
#define GpioReadResponse_fields &GpioReadResponse_msg
#define AdcReadRequest_fields &AdcReadRequest_msg
#define AdcReadResponse_fields &AdcReadResponse_msg
#define AdcReadAllRequest_fields &AdcReadAllRequest_msg
#define AdcReadAllResponse_fields &AdcReadAllResponse_msg
#define UartConfigRequest_fields &UartConfigRequest_msg
#define UartConfigResponse_fields &UartConfigResponse_msg
#define UartStreamRequest_fields &UartStreamRequest_msg
#define UartStreamResponse_fields &UartStreamResponse_msg
#define ListFwFilesRequest_fields &ListFwFilesRequest_msg
#define FwFileInfo_fields &FwFileInfo_msg
#define ListFwFilesResponse_fields &ListFwFilesResponse_msg
#define UploadFwFileRequest_fields &UploadFwFileRequest_msg
#define UploadFwFileResponse_fields &UploadFwFileResponse_msg
#define DeleteFwFileRequest_fields &DeleteFwFileRequest_msg
#define DeleteFwFileResponse_fields &DeleteFwFileResponse_msg
#define ListJLinksRequest_fields &ListJLinksRequest_msg
#define JLinkInfo_fields &JLinkInfo_msg
#define ListJLinksResponse_fields &ListJLinksResponse_msg
#define FlashHexFileRequest_fields &FlashHexFileRequest_msg
#define FlashHexFileResponse_fields &FlashHexFileResponse_msg
#define DutPowerEnableRequest_fields &DutPowerEnableRequest_msg
#define DutPowerEnableResponse_fields &DutPowerEnableResponse_msg
#define DutVoltageSetRequest_fields &DutVoltageSetRequest_msg
#define DutVoltageSetResponse_fields &DutVoltageSetResponse_msg
#define DutCurrentReadRequest_fields &DutCurrentReadRequest_msg
#define DutCurrentReadResponse_fields &DutCurrentReadResponse_msg
#define DutVoltageReadRequest_fields &DutVoltageReadRequest_msg
#define DutVoltageReadResponse_fields &DutVoltageReadResponse_msg
#define DutPowerReadRequest_fields &DutPowerReadRequest_msg
#define DutPowerReadResponse_fields &DutPowerReadResponse_msg
#define AltimeterReadRequest_fields &AltimeterReadRequest_msg
#define AltimeterReadResponse_fields &AltimeterReadResponse_msg
#define AccelReadRequest_fields &AccelReadRequest_msg
#define AccelReadResponse_fields &AccelReadResponse_msg
#define AccelReadMaxRequest_fields &AccelReadMaxRequest_msg
#define AccelReadMaxResponse_fields &AccelReadMaxResponse_msg
#define EepromReadRequest_fields &EepromReadRequest_msg
#define EepromReadResponse_fields &EepromReadResponse_msg
#define EepromWriteRequest_fields &EepromWriteRequest_msg
#define EepromWriteResponse_fields &EepromWriteResponse_msg

/* Maximum encoded size of messages (where known) */
/* GpioConfigResponse_size depends on runtime parameters */
/* GpioWriteResponse_size depends on runtime parameters */
/* GpioReadResponse_size depends on runtime parameters */
/* AdcReadResponse_size depends on runtime parameters */
/* AdcReadAllResponse_size depends on runtime parameters */
/* UartConfigResponse_size depends on runtime parameters */
/* UartStreamRequest_size depends on runtime parameters */
/* UartStreamResponse_size depends on runtime parameters */
/* FwFileInfo_size depends on runtime parameters */
/* ListFwFilesResponse_size depends on runtime parameters */
/* UploadFwFileRequest_size depends on runtime parameters */
/* UploadFwFileResponse_size depends on runtime parameters */
/* DeleteFwFileRequest_size depends on runtime parameters */
/* DeleteFwFileResponse_size depends on runtime parameters */
/* JLinkInfo_size depends on runtime parameters */
/* ListJLinksResponse_size depends on runtime parameters */
/* FlashHexFileRequest_size depends on runtime parameters */
/* FlashHexFileResponse_size depends on runtime parameters */
/* DutPowerEnableResponse_size depends on runtime parameters */
/* DutVoltageSetResponse_size depends on runtime parameters */
/* DutCurrentReadResponse_size depends on runtime parameters */
/* DutVoltageReadResponse_size depends on runtime parameters */
/* DutPowerReadResponse_size depends on runtime parameters */
/* AltimeterReadResponse_size depends on runtime parameters */
/* AccelReadResponse_size depends on runtime parameters */
/* AccelReadMaxResponse_size depends on runtime parameters */
/* EepromReadResponse_size depends on runtime parameters */
/* EepromWriteRequest_size depends on runtime parameters */
/* EepromWriteResponse_size depends on runtime parameters */
#define AccelReadMaxRequest_size                 0
#define AccelReadRequest_size                    0
#define AdcReadAllRequest_size                   11
#define AdcReadRequest_size                      13
#define AltimeterReadRequest_size                0
#define DutCurrentReadRequest_size               0
#define DutPowerEnableRequest_size               2
#define DutPowerReadRequest_size                 0
#define DutVoltageReadRequest_size               0
#define DutVoltageSetRequest_size                9
#define EepromReadRequest_size                   22
#define GpioConfigRequest_size                   6
#define GpioReadRequest_size                     2
#define GpioWriteRequest_size                    4
#define ListFwFilesRequest_size                  0
#define ListJLinksRequest_size                   0
#define UartConfigRequest_size                   6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
