"""V2 Protocol type imports.

All gRPC message types and enums are imported from the generated protobuf modules.
"""

# All V2 message types and enums
from protocols.mtib_v2.mtib_v2_pb2 import (
    # Common types
    Empty,
    Timestamp,
    Error,
    Response,
    # Device & Target Management
    Architecture,
    TargetDevice,
    ListTargetsResponse,
    # Debug Probe
    DebugProbeType,
    DebugState,
    DebugProbe,
    ListProbesResponse,
    DebugConnectRequest,
    DebugConnectResponse,
    DebugDisconnectRequest,
    DebugStatusRequest,
    DebugStatusResponse,
    DebugHaltRequest,
    DebugResumeRequest,
    DebugStepRequest,
    DebugResetRequest,
    RegisterValue,
    ReadRegistersRequest,
    ReadRegistersResponse,
    WriteRegisterRequest,
    ReadMemoryRequest,
    ReadMemoryResponse,
    WriteMemoryRequest,
    BreakpointType,
    SetBreakpointRequest,
    SetBreakpointResponse,
    ClearBreakpointRequest,
    WatchpointMode,
    SetWatchpointRequest,
    SetWatchpointResponse,
    StackFrame,
    BacktraceRequest,
    BacktraceResponse,
    # Flash Programming
    FlashInfoRequest,
    FlashRegion,
    FlashInfoResponse,
    FlashEraseRequest,
    FlashWriteRequest,
    FlashWriteResponse,
    FlashProgramRequest,
    FlashProgramResponse,
    # RTT
    RttStartRequest,
    RttStartResponse,
    RttStopRequest,
    RttStreamRequest,
    RttStreamResponse,
    # SWO
    SwoStartRequest,
    SwoStreamResponse,
    # UART
    Parity,
    StopBits,
    FlowControl,
    UartConfig,
    UartOpenRequest,
    UartOpenResponse,
    UartCloseRequest,
    UartStreamRequest,
    UartStreamResponse,
    # Power
    PowerChannel,
    PowerConfig,
    PowerEnableRequest,
    PowerDisableRequest,
    PowerStatusRequest,
    PowerStatusResponse,
    PowerSample,
    PowerStreamRequest,
    PowerStreamResponse,
    PowerMeasureRequest,
    PowerMeasureResponse,
    # Logic Analyzer
    LogicChannelConfig,
    LogicCaptureConfig,
    LogicCaptureStartRequest,
    LogicCaptureStartResponse,
    LogicCaptureStatusRequest,
    LogicCaptureStatusResponse,
    LogicCaptureStopRequest,
    Protocol,
    I2cDecoderConfig,
    SpiDecoderConfig,
    UartDecoderConfig,
    AddDecoderRequest,
    AddDecoderResponse,
    I2cTransaction,
    SpiTransaction,
    DecodedData,
    GetDecodedDataRequest,
    GetDecodedDataResponse,
    # GPIO
    GpioDirection,
    GpioPull,
    GpioConfigRequest,
    GpioWriteRequest,
    GpioReadRequest,
    GpioReadResponse,
    GpioWatchRequest,
    GpioEventResponse,
    # I2C Master
    I2cConfig,
    I2cTransferRequest,
    I2cTransferResponse,
    I2cScanRequest,
    I2cScanResponse,
    # SPI Master
    SpiConfig,
    SpiTransferRequest,
    SpiTransferResponse,
    # CAN Bus
    CanConfig,
    CanFrame,
    CanSendRequest,
    CanReceiveResponse,
    CanFilterConfig,
    CanSetFilterRequest,
    # BLE
    BleDevice,
    BleScanRequest,
    BleScanResponse,
    BleConnectRequest,
    BleConnectResponse,
    BleDisconnectRequest,
    BleService,
    BleCharacteristic,
    BleDiscoverServicesRequest,
    BleDiscoverServicesResponse,
    BleReadRequest,
    BleReadResponse,
    BleWriteRequest,
    BleNotificationResponse,
    # Zephyr
    ZephyrShellRequest,
    ZephyrShellResponse,
    ZephyrLogLevel,
    ZephyrLogEntry,
    ZephyrLogStreamRequest,
    ZephyrLogStreamResponse,
    ZephyrDevicetreeRequest,
    ZephyrDevicetreeNode,
    ZephyrDevicetreeResponse,
    ZephyrThread,
    ZephyrThreadsRequest,
    ZephyrThreadsResponse,
    # Test Orchestration
    TestResult,
    TwisterRunRequest,
    TwisterRunResponse,
    # File Management
    FileInfo,
    ListFilesRequest,
    ListFilesResponse,
    UploadFileRequest,
    UploadFileResponse,
    DownloadFileRequest,
    DownloadFileResponse,
    DeleteFileRequest,
    # Health/System
    HealthCheckRequest,
    HealthCheckResponse,
    SystemInfoRequest,
    SystemInfoResponse,
    # Observability
    ObservabilityAdcReading,
    ObservabilityPowerReading,
    ObservabilityGpioState,
    ObservabilityUartStatus,
    ObservabilitySystemMetrics,
    ObservabilityClientInfo,
    ObservabilitySnapshot,
    ObservabilityStreamRequest,
    ObservabilityStreamResponse,
)

# gRPC service types
from protocols.mtib_v2.mtib_v2_pb2_grpc import MtibV2Servicer, MtibV2Stub
