# V2 Protocol types
from protocols.mtib_v2.mtib_v2_pb2 import (
    # Common types
    Empty,
    Timestamp,
    Response,
    # Health/System
    HealthCheckRequest,
    HealthCheckResponse,
    SystemInfoRequest,
    SystemInfoResponse,
    # GPIO types
    GpioDirection,
    GpioPull,
    GpioConfigRequest,
    GpioWriteRequest,
    GpioReadRequest,
    GpioReadResponse,
    # Power types
    PowerChannel,
    PowerConfig,
    PowerEnableRequest,
    PowerDisableRequest,
    PowerStatusRequest,
    PowerStatusResponse,
    PowerSample,
    PowerStreamRequest,
    PowerStreamResponse,
    PowerMeasureRequest,
    PowerMeasureResponse,
    # UART types
    Parity,
    StopBits,
    FlowControl,
    UartConfig,
    UartOpenRequest,
    UartOpenResponse,
    UartCloseRequest,
    UartStreamRequest,
    UartStreamResponse,
    # File types
    FileInfo,
    ListFilesRequest,
    ListFilesResponse,
    UploadFileRequest,
    UploadFileResponse,
    DownloadFileRequest,
    DownloadFileResponse,
    DeleteFileRequest,
)

# Import gRPC service types from V2
from protocols.mtib_v2.mtib_v2_pb2_grpc import MtibV2Servicer, MtibV2Stub

# Legacy V1 types - for backward compatibility during migration
# These will be removed as handlers are migrated to V2
from protocols.mtib.mtib_pb2 import (
    AccelReadResponse,
    AdcReadAllResponse,
    AdcReadRequest,
    AdcReadResponse,
    AltimeterReadResponse,
    DeleteFwFileRequest as DeleteFwFileRequestV1,
    DeleteFwFileResponse,
    DutPowerReadResponse,
    DutPowerRequest,
    DutPowerResponse,
    EnableAppProtectRequest,
    EnableAppProtectResponse,
    FlashFwFileRequest,
    FlashFwFileResponse,
    FwFileInfo,
    GetMotionStatusResponse,
    GpioConfigRequest as GpioConfigRequestV1,
    GpioConfigResponse,
    GpioReadRequest as GpioReadRequestV1,
    GpioReadResponse as GpioReadResponseV1,
    GpioResistorConfig,
    GpioWriteRequest as GpioWriteRequestV1,
    GpioWriteResponse,
    HealthCheckResponse as HealthCheckResponseV1,
    HostType,
    ListFwFilesResponse,
    ListProgrammersResponse,
    EraseFlashRequest,
    EraseFlashResponse,
    MotionHomeResponse,
    MotionStartRequest,
    MotionStartResponse,
    MotionStatus,
    MotionStopResponse,
    Programmer,
    ProgrammerType,
    UartStreamRequest as UartStreamRequestV1,
    UartStreamResponse as UartStreamResponseV1,
    UploadFwFileRequest,
    UploadFwFileResponse,
)
