apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shared-clickhouse.fullname" . }}-credentials
  labels:
    {{- include "shared-clickhouse.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.auth.adminPassword | quote }}
  {{- range .Values.databases }}
  {{ .user }}-password: {{ .password | quote }}
  {{- end }}
