/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "cluster_operator.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cluster_operator_HealthCheckRequest, cluster_operator_HealthCheckRequest, AUTO)


PB_BIND(cluster_operator_HealthCheckResponse, cluster_operator_HealthCheckResponse, AUTO)


PB_BIND(cluster_operator_NodeInfo, cluster_operator_NodeInfo, AUTO)


PB_BIND(cluster_operator_GetClusterInfoRequest, cluster_operator_GetClusterInfoRequest, AUTO)


PB_BIND(cluster_operator_GetClusterInfoResponse, cluster_operator_GetClusterInfoResponse, AUTO)


PB_BIND(cluster_operator_PodInfo, cluster_operator_PodInfo, AUTO)


PB_BIND(cluster_operator_DeploymentInfo, cluster_operator_DeploymentInfo, AUTO)


PB_BIND(cluster_operator_GetDeploymentInfoRequest, cluster_operator_GetDeploymentInfoRequest, AUTO)


PB_BIND(cluster_operator_GetDeploymentInfoResponse, cluster_operator_GetDeploymentInfoResponse, AUTO)


PB_BIND(cluster_operator_ListTestsRequest, cluster_operator_ListTestsRequest, AUTO)


PB_BIND(cluster_operator_ListTestsResponse, cluster_operator_ListTestsResponse, AUTO)


PB_BIND(cluster_operator_ExecuteTestRequest, cluster_operator_ExecuteTestRequest, AUTO)


PB_BIND(cluster_operator_ExecuteTestResponse, cluster_operator_ExecuteTestResponse, AUTO)


PB_BIND(cluster_operator_StopTestRequest, cluster_operator_StopTestRequest, AUTO)


PB_BIND(cluster_operator_StopTestResponse, cluster_operator_StopTestResponse, AUTO)


PB_BIND(cluster_operator_RegisterTestRequest, cluster_operator_RegisterTestRequest, AUTO)


PB_BIND(cluster_operator_RegisterTestResponse, cluster_operator_RegisterTestResponse, AUTO)




