syntax = "proto3";

package cluster_operator;

// Protocol imports
import "cluster_test.proto";

// This is the main interface used to access all the functionality in 
// a test cluster.
// 
// This service gets served at port 50052
//
service ClusterOperator {
  // Performs a health check to ensure the operator is at least running.
  rpc HealthCheck(HealthCheckRequest) returns (HealthCheckResponse) {}

  // Fetches Cluster Information
  rpc GetClusterInfo(GetClusterInfoRequest) returns (GetClusterInfoResponse) {}

  // Fetches Current Deployment Information
  rpc GetDeploymentInfo(GetDeploymentInfoRequest) returns (GetDeploymentInfoResponse) {}

  // Lists available tests in the cluster.
  rpc ListTests(ListTestsRequest) returns (ListTestsResponse) {}

  // Executes a test.
  rpc ExecuteTest(ExecuteTestRequest) returns (stream ExecuteTestResponse) {}

  // Stops an executing test.
  rpc StopTest(StopTestRequest) returns (StopTestResponse) {}

  // Used by test runners to register themselves with the operator 
  rpc RegisterTest(RegisterTestRequest) returns (RegisterTestResponse) {}  
}

// Operator Info
enum ClusterStatus {
  // The operator is awaiting for the cluster to ready
  STARTING = 0;

  // Ready means the operator has succesfully connected to the k8s cluster, and all the nodes are healthy.
  // At this point, the cluster is ready for work
  READY = 1;

  // The operator has been given a new deployment and is in the process of applying it to the cluster
  UPDATING = 2;

  // A deployment is running in the cluster and it's ready for the proxy to send it commands
  IDLE = 3;

  // A request to run a test has been received and it's currently executing in the cluster
  RUNNING = 4;
  
  // An error with the deployment or the operator itself has occurred 
  ERRORED = 5;
}

// HealthCheck
message HealthCheckRequest {}
message HealthCheckResponse {
  ClusterStatus status = 1;
  string error = 2;
}

// Node Info message definition
message NodeInfo {
  string name = 1;                  // Node name
  string host = 2;                  // Node hostname
  string os_image = 3;              // Operating system image used by the node
  string kernel_version = 4;        // Kernel version running on the node
  int64 cpu_cores = 5;              // CPU cores
  int64 memory_used_bytes = 6;      // Memory capacity of the node in bytes
  int64 memory_capacity_bytes = 7;  // Memory capacity of the node in bytes
  int64 storage_used_bytes = 8;     // Storage capacity of the node in bytes
  int64 storage_capacity_bytes = 9; // Storage capacity of the node in bytes
}

// Cluster Info
message GetClusterInfoRequest {}

message GetClusterInfoResponse {
  repeated NodeInfo nodes_info = 1;
}

// Deployment Info
message PodInfo {
  string name = 1;
  string image = 2;
  string node = 3;
  string status = 4;
  int32 restarts = 5;
  bool ready = 6; 
}

message DeploymentInfo {
  string name = 1;
  string uuid = 2;
  repeated PodInfo pods_info = 3;
}

message GetDeploymentInfoRequest {}
message GetDeploymentInfoResponse {
  repeated DeploymentInfo deployment_info = 1;
}

// ListTests messages
message ListTestsRequest {}
message ListTestsResponse {
  repeated cluster_test.TestInfo tests = 1;
}

// Execute messages
message ExecuteTestRequest {
  string uuid = 1;            // Which test we wanna run
  string config = 2;          // The configuration for the specific test
  repeated string nodes = 3;
}

message ExecuteTestResponse {
  bool stopped = 1;
  int32 sequence = 2;                   
  repeated cluster_test.TestStepResult results = 3;
}

// Stop messages
message StopTestRequest {
  string uuid = 1;
}

message StopTestResponse {
  string error = 2;
}

// Test Registration
message RegisterTestRequest {
  int32 port = 1;                     // What port we're serving 
  cluster_test.TestInfo info = 2;     // Metadata about the test
}

message RegisterTestResponse {
  bool success = 1;
  string error = 2;
}