# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos.cluster_operator.cluster_operator_pb2 as cluster__operator__pb2


class ClusterOperatorStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/cluster_operator.ClusterOperator/HealthCheck',
                request_serializer=cluster__operator__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=cluster__operator__pb2.HealthCheckResponse.FromString,
                )
        self.GetClusterInfo = channel.unary_unary(
                '/cluster_operator.ClusterOperator/GetClusterInfo',
                request_serializer=cluster__operator__pb2.GetClusterInfoRequest.SerializeToString,
                response_deserializer=cluster__operator__pb2.GetClusterInfoResponse.FromString,
                )
        self.GetDeploymentInfo = channel.unary_unary(
                '/cluster_operator.ClusterOperator/GetDeploymentInfo',
                request_serializer=cluster__operator__pb2.GetDeploymentInfoRequest.SerializeToString,
                response_deserializer=cluster__operator__pb2.GetDeploymentInfoResponse.FromString,
                )
        self.ListTests = channel.unary_unary(
                '/cluster_operator.ClusterOperator/ListTests',
                request_serializer=cluster__operator__pb2.ListTestsRequest.SerializeToString,
                response_deserializer=cluster__operator__pb2.ListTestsResponse.FromString,
                )
        self.ExecuteTest = channel.unary_stream(
                '/cluster_operator.ClusterOperator/ExecuteTest',
                request_serializer=cluster__operator__pb2.ExecuteTestRequest.SerializeToString,
                response_deserializer=cluster__operator__pb2.ExecuteTestResponse.FromString,
                )
        self.StopTest = channel.unary_unary(
                '/cluster_operator.ClusterOperator/StopTest',
                request_serializer=cluster__operator__pb2.StopTestRequest.SerializeToString,
                response_deserializer=cluster__operator__pb2.StopTestResponse.FromString,
                )
        self.RegisterTest = channel.unary_unary(
                '/cluster_operator.ClusterOperator/RegisterTest',
                request_serializer=cluster__operator__pb2.RegisterTestRequest.SerializeToString,
                response_deserializer=cluster__operator__pb2.RegisterTestResponse.FromString,
                )


class ClusterOperatorServicer(object):
    """Service definition
    """

    def HealthCheck(self, request, context):
        """Performs a health check to ensure the operator is at least running.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterInfo(self, request, context):
        """Fetches Cluster Information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeploymentInfo(self, request, context):
        """Fetches Current Deployment Information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTests(self, request, context):
        """Lists available tests in the cluster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTest(self, request, context):
        """Executes a test.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTest(self, request, context):
        """Stops an executing test.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterTest(self, request, context):
        """Used by test runners to register themselves with the operator 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterOperatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=cluster__operator__pb2.HealthCheckRequest.FromString,
                    response_serializer=cluster__operator__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetClusterInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterInfo,
                    request_deserializer=cluster__operator__pb2.GetClusterInfoRequest.FromString,
                    response_serializer=cluster__operator__pb2.GetClusterInfoResponse.SerializeToString,
            ),
            'GetDeploymentInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeploymentInfo,
                    request_deserializer=cluster__operator__pb2.GetDeploymentInfoRequest.FromString,
                    response_serializer=cluster__operator__pb2.GetDeploymentInfoResponse.SerializeToString,
            ),
            'ListTests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTests,
                    request_deserializer=cluster__operator__pb2.ListTestsRequest.FromString,
                    response_serializer=cluster__operator__pb2.ListTestsResponse.SerializeToString,
            ),
            'ExecuteTest': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteTest,
                    request_deserializer=cluster__operator__pb2.ExecuteTestRequest.FromString,
                    response_serializer=cluster__operator__pb2.ExecuteTestResponse.SerializeToString,
            ),
            'StopTest': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTest,
                    request_deserializer=cluster__operator__pb2.StopTestRequest.FromString,
                    response_serializer=cluster__operator__pb2.StopTestResponse.SerializeToString,
            ),
            'RegisterTest': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTest,
                    request_deserializer=cluster__operator__pb2.RegisterTestRequest.FromString,
                    response_serializer=cluster__operator__pb2.RegisterTestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cluster_operator.ClusterOperator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClusterOperator(object):
    """Service definition
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cluster_operator.ClusterOperator/HealthCheck',
            cluster__operator__pb2.HealthCheckRequest.SerializeToString,
            cluster__operator__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClusterInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cluster_operator.ClusterOperator/GetClusterInfo',
            cluster__operator__pb2.GetClusterInfoRequest.SerializeToString,
            cluster__operator__pb2.GetClusterInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDeploymentInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cluster_operator.ClusterOperator/GetDeploymentInfo',
            cluster__operator__pb2.GetDeploymentInfoRequest.SerializeToString,
            cluster__operator__pb2.GetDeploymentInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cluster_operator.ClusterOperator/ListTests',
            cluster__operator__pb2.ListTestsRequest.SerializeToString,
            cluster__operator__pb2.ListTestsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cluster_operator.ClusterOperator/ExecuteTest',
            cluster__operator__pb2.ExecuteTestRequest.SerializeToString,
            cluster__operator__pb2.ExecuteTestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cluster_operator.ClusterOperator/StopTest',
            cluster__operator__pb2.StopTestRequest.SerializeToString,
            cluster__operator__pb2.StopTestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cluster_operator.ClusterOperator/RegisterTest',
            cluster__operator__pb2.RegisterTestRequest.SerializeToString,
            cluster__operator__pb2.RegisterTestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
