syntax = "proto3";

import "cluster_test.proto";

package cluster_operator;

service ClusterOperator {
  // Performs a health check to ensure the operator is at least running.
  rpc HealthCheck(HealthCheckRequest) returns (HealthCheckResponse) {}

  // Fetches Operator Information
  rpc GetOperatorInfo(GetOperatorInfoRequest) returns (GetOperatorInfoResponse) {}

  // Fetches Current Deployment Information
  rpc GetDeploymentInfo(GetDeploymentInfoRequest) returns (GetDeploymentInfoResponse) {}

  // Used by test runners to register themselves with the operator 
  rpc RegisterTest(RegisterTestRequest) returns (RegisterTestResponse) {}
  
  // Lists available tests in the cluster.
  rpc ListTests(ListTestsRequest) returns (ListTestsResponse) {}

  // Executes a test on a standalone board.
  rpc ExecuteTest(cluster_test.ExecuteTestRequest) returns (stream cluster_test.ExecuteTestResponse) {}
}

// HealthCheck
message HealthCheckRequest {}
message HealthCheckResponse {}

// Operator Info
enum OperatorStatus {
  // Starting means that the operator is awaiting for the cluster to ready, and registered with 
  // the proxy
  STARTING = 0;

  // Ready means the operator has succesfully connected to the cluster, and all the nodes are healthy.
  // At this point, the cluster is ready to be registered with the proxy, and also ready for test runners
  // to register themselves with the cluster
  READY = 1;

  // Connected means the 
  CONNECTED = 2;
  
  ERRORED = 3;
}

message OperatorInfo {
  string image = 1;
  OperatorStatus status = 2;
  string error = 3;
}

message GetOperatorInfoRequest {}

message GetOperatorInfoResponse {
  OperatorInfo info = 1;
}

// Deployment Info
enum DeploymentStatus {
  NONE = 0;
  INSTALLING = 1;
  UPDATING = 2;
  RUNNING = 3;
}

message DeploymentInfo {
  string name = 1;
  DeploymentStatus status = 2;
}

message GetDeploymentInfoRequest {}
message GetDeploymentInfoResponse {
  DeploymentInfo info = 1;
}

// Test Registration
message RegisterTestRequest {
  int32 port = 1;                     // What port we're serving 
  cluster_test.TestInfo info = 2;     // Metadata about the test
}

message RegisterTestResponse {
  bool success = 1;
  string error = 2;
}

// ListTests messages
message ListTestsRequest {}
message ListTestsResponse {
  repeated cluster_test.TestInfo tests = 1;
}