syntax = "proto3";

import "mtib_runner.proto";

package mtib_controller;

service MtibController {
  // Performs a health check to ensure the cluster is operational.
  rpc HealthCheck(HealthCheckRequest) returns (HealthCheckResponse) {}

  // Fetches comprehensive Info about the test cluster, including runners and supported hardware.
  rpc GetClusterInfo(GetClusterInfoRequest) returns (GetClusterInfoResponse) {}

  // Hardware/System reset
  rpc Reset(ResetRequest) returns (ResetResponse) {}

  // Lists available tests in the cluster.
  rpc ListTests(ListTestsRequest) returns (ListTestsResponse) {}

  // Executes a test on a standalone board.
  rpc ExecuteTest(ExecuteTestRequest) returns (stream ExecuteTestResponse) {}
}

// Reset
message ResetRequest{}
message ResetResponse{}

enum ClusterStatus {
  Ready = 0;
  NotReady = 1;
  Errored = 2;
}

// HealthCheck messages
message HealthCheckRequest {}
message HealthCheckResponse {
  ClusterStatus status = 1;
  string error = 2;
}

// Test Info, now with additional information
message StepInfo {
  int32 sequence = 1;
  string name = 2;
  string description = 3;
}

message TestInfo {
  string id = 1;
  string name = 2;
  string description = 3;
  repeated StepInfo steps = 4;
}

// ListTests messages
message ListTestsRequest {}
message ListTestsResponse {
  repeated TestInfo tests = 1;
}

message TestStepResult {
  int32 runnerId = 1; 
  bool execOk = 2;
  string error = 3;
  bool success = 4; 
  string detailedResult = 5;    // Optionally include detailed logs or results of the step.
  int32 progressPercentage = 6; // Progress of the test execution as a whole.
  string timestamp = 7;         // Timestamp of the update, useful for logs and tracking.
}

// Messages for executing tests on panel boards
message ExecuteTestRequest {
  string testId = 1;
  repeated int32 runnerIds = 2; // Specifies which boards in the panel to test. Empty means test all.
}

message ExecuteTestResponse {
  string instance = 1;
  int32 sequence = 3;
  repeated TestStepResult results = 4;
}

// Describes supported hardware within the cluster
message HardwareInfo {
  string model = 1; 
  string version = 2;
}

message ClusterInfo {
  string name = 1;

  // Embedded runners information
  repeated mtib_runner.RunnerInfo runners = 2;

  // Supported hardware and capabilities
  repeated HardwareInfo supportedHardware = 3;
}

// Requests for fetching cluster Info
message GetClusterInfoRequest {}

// Response containing comprehensive information about the cluster
message GetClusterInfoResponse {
  ClusterInfo info = 1;
}