-- Drop the legacy unique index ``fixture_designs_name_key`` on
-- fixture_designs(name).
--
-- Under the old model, fixture designs were keyed globally by name (and
-- later by name+revision). With per-package ownership (v0.5.0), every
-- TestPackage owns its own design and two different packages can
-- legitimately produce designs with the same human-readable name —
-- they're scoped by ``testPackageId @unique`` instead.
--
-- The 20260427120000 refactor migration dropped
-- ``fixture_designs_name_revision_key`` but missed this earlier
-- ``fixture_designs_name_key`` index. The result: re-uploading a test
-- package whose fixture name matches an already-extracted design
-- failed with ``Unique constraint failed on the fields: (name)`` and
-- the design was silently skipped. Caught in production while
-- exercising the alpha manufacturing flow on v0.5.1.
--
-- IF EXISTS so the migration tolerates either pre-state (the index
-- may already be gone on hosts that received the hotfix manually).

DROP INDEX IF EXISTS "fixture_designs_name_key";
