services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
      - ./influxdb-entrypoint.sh:/docker-entrypoint-initdb.d/influxdb-entrypoint.sh
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin_password
      - INFLUXDB_ORG=org
      - INFLUXDB_BUCKET=bucket
      - INFLUXDB_TOKEN=my-super-secret-auth-token
      - INFLUXDB_INIT_MODE=setup
    restart: always

volumes:
  influxdb-data:
