apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-backup
  namespace: argocd
spec:
  project: media
  source:
    repoURL: https://github.com/gophersys/infrastructure.git
    targetRevision: main
    path: apps/music/config-backup
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - ServerSideApply=true
