apiVersion: v1
kind: ConfigMap
metadata:
  name: ci-config
  namespace: devops
  labels:
    app.kubernetes.io/part-of: concord
    app.kubernetes.io/component: ci
data:
  REPO_URL: "git@bitbucket.org:corekinect/concord.git"
  BRANCH: "main"
  MINIO_ENDPOINT: "http://concord-minio.staging.svc:9000"
  MINIO_BUCKET: "devops"
