{{- if and .Values.ingress.enabled .Values.admin.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: concord-ci-ingress
  labels:
    {{- include "concord-ci.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - admin.{{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: admin.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: concord-ci-admin
                port:
                  number: {{ .Values.admin.port }}
{{- end }}
