package mtib_test_fixture;

service MtibFixture {

    rpc check_I2C_addresses(VerifyAddressesRequest) returns (VerifyAddressesResponse)

    /*********************************************************************
                     Altimeter Request and response 
    *********************************************************************/

    // RPC method to measure voltage consumption
    rpc BMP390_ReadVoltage (BMP390_MeasureVoltageRequest) returns (BMP390_MeasureVoltageResponse);

    // RPC method to read the status register
    rpc BMP390_ReadStatusRegister (BMP390_ReadStatusRegisterRequest) returns (BMP390_ReadStatusRegisterResponse);


    /*********************************************************************
                     Mux Request and response 
    *********************************************************************/

    // RPC method to read the value from the selected channel
    rpc Mux_ReadChannel (MuxReadChannelRequest) returns (MuxReadChannelResponse);


    /*********************************************************************
                     Accelerometer Request and response 
    *********************************************************************/

    // RPC to read accelerometer values and voltage draw
    rpc LIS2DE12_ReadValues(LIS2DE12_ReadValuesRequest) returns (LIS2DE12_ReadValuesResponse);


    /*********************************************************************
                     EEPROM Request and response 
    *********************************************************************/

    /// set the ficture number/ get fixture number 
    // RPC for read and write check
    rpc EEPPROM_ReadWriteCheck(EepromReadWriteCheckRequest) returns (EepromReadWriteCheckResponse);

    // RPC for data retention test
    rpc EEPPROM_DataRetentionTest(EepromDataRetentionTestRequest) returns (EepromDataRetentionTestResponse);



    /*********************************************************************
                     INA219 Request and response 
    *********************************************************************/
    // RPC to request current measurement
     rpc INA219_ReadCurrent(INA219RequestCurrent) returns (INA219ResponseCurrent);

    // RPC to request voltage measurement
    rpc INA219_ReadVoltage(INA219RequestVoltage) returns (INA219ResponseVoltage);

    // RPC to request total power consumption
    rpc INA219_ReadPower(INA219RequestPower) returns (INA219ResponsePower);

    /*********************************************************************
                    Sigma Logs
    *********************************************************************/
    rpc Sigma_SendMessage(SigmaMessageRequest) returns (SigmaMessageResponse); // called by orange pi to send data to sigma through stm32

    rpc OrangePi_SendMessage(SigmaMessageRequest) returns (SigmaMessageResponse); // called by stm32 to send data from sigma to orangpi
}

/*********************************************************
    I2C Addresses Request and response 
*********************************************************/
message VerifyAddressesRequest {
  enum DeviceType{
    BMP390_address  = 0;
    Accel_address = 1;
    Eeprom_address = 2;
    tps_address = 3;
    INA219_address = 4;
  }
  
  DeviceType device = 1;
}

message VerifyAddressesResponse {
  bool device_is_connected = 1;
}

/*********************************************************
    Message Logs Request and response 
*********************************************************/
message SigmaMessageRequest {
  uint8 uart_port = 1;
  repeated bytes data = 2;
  uint16 data_size = 3;
}

message SigmaMessageResponse {
  bool success = 1;
}

/*********************************************************
    Altimeter Request and response 
*********************************************************/

message BMP390_MeasureVoltageRequest {
  // No additional fields needed for this request
}

message BMP390_MeasureVoltageResponse {
  // The measured voltage consumption in volts
  float voltage = 1;
}

message BMP390_ReadStatusRegisterRequest {
  // No additional fields needed for this request
}

message BMP390_ReadStatusRegisterResponse {
  // The value of the status register
  uint32 status_register = 1;
}

/*********************************************************
    Accelerometer Request and response 
*********************************************************/

message LIS2DE12_ReadValuesRequest {
    // No additional fields needed for reading accelerometer values
}

message LIS2DE12_ReadValuesResponse {
    // Accelerometer values in x, y, and z directions
    float x_value = 1;
    float y_value = 2;
    float z_value = 3;

    // Voltage draw to check for short circuit
    float voltage_draw = 4;
}

/*********************************************************
    MUX Request and response 
*********************************************************/
// Enum to represent different channel numbers
enum ChannelNumber {
    CHANNEL_0 = 0;
    CHANNEL_1 = 1;
    CHANNEL_2 = 2;
    CHANNEL_3 = 3;
    CHANNEL_4 = 4;
    CHANNEL_5 = 5;
    CHANNEL_6 = 6;
    CHANNEL_7 = 7;
  }

  message MuxReadChannelRequest {
    // The channel number to read from
    ChannelNumber channel_number = 1;
  }
  
  message MuxReadChannelResponse {
    // The value read from the selected channel
    float channel_value = 1;

    // Additional ADC value from the COM pin
    float com_adc_value = 2;
  }

/*********************************************************
    EEPROM Request and response 
*********************************************************/

message EepromDataRetentionTestRequest {
  // Specify parameters for the data retention test
  bytes data_to_write = 1;
}

message EepromDataRetentionTestResponse {
  // Response indicating the success of the data retention test
  bool is_data_retention_successful = 1;
}

message EepromReadWriteCheckRequest {
    // Specify the EEPROM address and data to read and write
    bytes data_to_write = 2;
  }
  
  message EepromReadWriteCheckResponse {
    // Response indicating the success of read and write operations
    bool is_read_write_successful = 1;
  }

/*********************************************************
    INA219 Current and Voltage Monitor Request and response 
*********************************************************/
// Message to request the current measurement
message INA219RequestCurrent {
    // No additional fields needed for requesting current
  }
  
  // Response for the current measurement request
  message INA219ResponseCurrent {
    // Current measurement value in Amperes
    float current_value = 1;
  }
  
  // Message to request the voltage measurement
  message INA219RequestVoltage {
    // No additional fields needed for requesting voltage
  }
  
  // Response for the voltage measurement request
  message INA219ResponseVoltage {
    // Voltage measurement value in Volts
    float voltage_value = 1;
  }
  
  // Message to request the total power consumption
  message INA219RequestPower {
    // No additional fields needed for requesting power
  }
  
  // Response for the total power consumption request
  message INA219ResponsePower {
    // Power consumption value in Watts
    float power_value = 1;
  }
  
