"""Type definitions for MTIB V2 client.

Re-exports protobuf message types for convenience.
"""

# Standard includes
from dataclasses import dataclass
from enum import IntEnum
from typing import List, Optional

# Protocol includes - import from V2 proto
from protocols.mtib_v2.mtib_v2_pb2 import (
    # Common types
    Empty,
    Timestamp,
    Error,
    Response,
    # Target/Device types
    Architecture,
    TargetDevice,
    ListTargetsResponse,
    # Debug types
    DebugProbeType,
    DebugState,
    DebugProbe,
    ListProbesResponse,
    DebugConnectRequest,
    DebugConnectResponse,
    DebugDisconnectRequest,
    DebugStatusRequest,
    DebugStatusResponse,
    DebugHaltRequest,
    DebugResumeRequest,
    DebugStepRequest,
    DebugResetRequest,
    RegisterValue,
    ReadRegistersRequest,
    ReadRegistersResponse,
    WriteRegisterRequest,
    ReadMemoryRequest,
    ReadMemoryResponse,
    WriteMemoryRequest,
    BreakpointType,
    SetBreakpointRequest,
    SetBreakpointResponse,
    ClearBreakpointRequest,
    WatchpointMode,
    SetWatchpointRequest,
    SetWatchpointResponse,
    StackFrame,
    BacktraceRequest,
    BacktraceResponse,
    # Flash types
    FlashInfoRequest,
    FlashRegion,
    FlashInfoResponse,
    FlashEraseRequest,
    FlashWriteRequest,
    FlashWriteResponse,
    FlashProgramRequest,
    FlashProgramResponse,
    # RTT types
    RttStartRequest,
    RttStartResponse,
    RttStopRequest,
    RttStreamRequest,
    RttStreamResponse,
    # SWO types
    SwoStartRequest,
    SwoStreamResponse,
    # UART types
    Parity,
    StopBits,
    FlowControl,
    UartConfig,
    UartOpenRequest,
    UartOpenResponse,
    UartCloseRequest,
    UartStreamRequest,
    UartStreamResponse,
    # Power types
    PowerChannel,
    PowerConfig,
    PowerEnableRequest,
    PowerDisableRequest,
    PowerStatusRequest,
    PowerStatusResponse,
    PowerSample,
    PowerStreamRequest,
    PowerStreamResponse,
    PowerMeasureRequest,
    PowerMeasureResponse,
    # Logic Analyzer types
    LogicChannelConfig,
    LogicCaptureConfig,
    LogicCaptureStartRequest,
    LogicCaptureStartResponse,
    LogicCaptureStatusRequest,
    LogicCaptureStatusResponse,
    LogicCaptureStopRequest,
    Protocol,
    I2cDecoderConfig,
    SpiDecoderConfig,
    UartDecoderConfig,
    AddDecoderRequest,
    AddDecoderResponse,
    I2cTransaction,
    SpiTransaction,
    DecodedData,
    GetDecodedDataRequest,
    GetDecodedDataResponse,
    # GPIO types
    GpioDirection,
    GpioPull,
    GpioConfigRequest,
    GpioWriteRequest,
    GpioReadRequest,
    GpioReadResponse,
    GpioWatchRequest,
    GpioEventResponse,
    # I2C types
    I2cConfig,
    I2cTransferRequest,
    I2cTransferResponse,
    I2cScanRequest,
    I2cScanResponse,
    # SPI types
    SpiConfig,
    SpiTransferRequest,
    SpiTransferResponse,
    # CAN types
    CanConfig,
    CanFrame,
    CanSendRequest,
    CanReceiveResponse,
    CanFilterConfig,
    CanSetFilterRequest,
    # BLE types
    BleDevice,
    BleScanRequest,
    BleScanResponse,
    BleConnectRequest,
    BleConnectResponse,
    BleDisconnectRequest,
    BleService,
    BleCharacteristic,
    BleDiscoverServicesRequest,
    BleDiscoverServicesResponse,
    BleReadRequest,
    BleReadResponse,
    BleWriteRequest,
    BleNotificationResponse,
    # Zephyr types
    ZephyrShellRequest,
    ZephyrShellResponse,
    ZephyrLogLevel,
    ZephyrLogEntry,
    ZephyrLogStreamRequest,
    ZephyrLogStreamResponse,
    ZephyrDevicetreeRequest,
    ZephyrDevicetreeNode,
    ZephyrDevicetreeResponse,
    ZephyrThread,
    ZephyrThreadsRequest,
    ZephyrThreadsResponse,
    TestResult,
    TwisterRunRequest,
    TwisterRunResponse,
    # File types
    FileInfo,
    ListFilesRequest,
    ListFilesResponse,
    UploadFileRequest,
    UploadFileResponse,
    DownloadFileRequest,
    DownloadFileResponse,
    DeleteFileRequest,
    # Health/System types
    HealthCheckRequest,
    HealthCheckResponse,
    SystemInfoRequest,
    SystemInfoResponse,
)

# Export all imported types
__all__ = [
    # Common
    "Empty",
    "Timestamp",
    "Error",
    "Response",
    # Target/Device
    "Architecture",
    "TargetDevice",
    "ListTargetsResponse",
    # Debug
    "DebugProbeType",
    "DebugState",
    "DebugProbe",
    "ListProbesResponse",
    "DebugConnectRequest",
    "DebugConnectResponse",
    # ... and all other types
    # Health/System
    "HealthCheckRequest",
    "HealthCheckResponse",
    "SystemInfoRequest",
    "SystemInfoResponse",
]
