#!/usr/bin/env bash
#
# generate-machine-index.sh — regenerate machines/README.md and machines/ledger.md
# from the set of machines/hosts/<name>/identity.yaml files.
#
# Usage: ./generate-machine-index.sh
#
# Idempotent. When machines/hosts/ is empty (or contains no identity.yaml
# files), both output files are rewritten with a "no machines yet" placeholder.
#
# identity.yaml is expected to contain at least:
#   name: <string>
#   os: <string>          # e.g., linux-debian, windows-server, wsl
#   purpose: <string>
#   tailscale_hostname: <string>
#   status: <active|planned|retired>
#
# Missing fields are rendered as "-".
#
set -Eeuo pipefail
IFS=$'\n\t'

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MACHINES_DIR="$(cd "$PROJECT_ROOT/.." && pwd)"
HOSTS_DIR="$MACHINES_DIR/hosts"
README_OUT="$MACHINES_DIR/README.md"
LEDGER_OUT="$MACHINES_DIR/ledger.md"

function log_info()  { printf '\033[0;36m[info]\033[0m  %s\n' "$*"; }
function log_warn()  { printf '\033[0;33m[warn]\033[0m  %s\n' "$*" >&2; }
function log_error() { printf '\033[0;31m[error]\033[0m %s\n' "$*" >&2; }

function require_cmd() {
  local missing=()
  local cmd
  for cmd in "$@"; do
    command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd")
  done
  if [[ ${#missing[@]} -gt 0 ]]; then
    log_error "missing required tool(s): ${missing[*]}"
    exit 127
  fi
}

function yaml_field() {
  # Extract a simple "key: value" line from a YAML file. Does not handle
  # block scalars, flow style, anchors, etc. — identity.yaml is intentionally
  # flat. Returns empty string on miss.
  local file="$1" key="$2"
  python3 -c "
import re, sys
try:
    txt = open(sys.argv[1]).read()
    m = re.search(r'^\s*' + re.escape(sys.argv[2]) + r'\s*:\s*[\"\']?([^\"\'\n]+?)[\"\']?\s*\$', txt, re.M)
    print(m.group(1).strip() if m else '')
except Exception:
    print('')
" "$file" "$key"
}

function render_empty() {
  cat > "$README_OUT" <<'EOF'
# machines

No machines enrolled yet. See `machines/CONVENTIONS.md` for how to add one:

1. Pick a template from `machines/templates/`.
2. Scaffold with `bash machines/ctl.sh new-host <template> <host-name>`.
3. Edit `machines/hosts/<host-name>/identity.yaml` with the real values.
4. Run `bash ctl.sh generate-index` from the infrastructure root to
   regenerate this index.

This file is auto-generated — do not edit manually.
EOF

  cat > "$LEDGER_OUT" <<'EOF'
# machines — ledger

Summary of machine lifecycle states. Regenerated by
`machines/scripts/generate-machine-index.sh`.

| State    | Count |
|----------|-------|
| active   | 0     |
| planned  | 0     |
| retired  | 0     |

No machines enrolled yet.
EOF
  log_info "no machines found — wrote placeholders"
}

function render_populated() {
  local hosts=("$@")

  # README: flat table of all machines.
  {
    printf '# machines\n\n'
    printf 'Auto-generated index. Regenerate with:\n\n'
    printf '    bash ctl.sh generate-index\n\n'
    printf '| name | os | purpose | tailscale hostname | status |\n'
    printf '|------|----|---------|--------------------|--------|\n'
    local host name os purpose ts status
    for host in "${hosts[@]}"; do
      local id="$HOSTS_DIR/$host/identity.yaml"
      name="$(yaml_field "$id" name)"
      os="$(yaml_field "$id" os)"
      purpose="$(yaml_field "$id" purpose)"
      ts="$(yaml_field "$id" tailscale_hostname)"
      status="$(yaml_field "$id" status)"
      printf '| %s | %s | %s | %s | %s |\n' \
        "${name:-$host}" "${os:--}" "${purpose:--}" "${ts:--}" "${status:--}"
    done
  } > "$README_OUT"

  # Ledger: count per state.
  local active=0 planned=0 retired=0 other=0
  local host status
  for host in "${hosts[@]}"; do
    status="$(yaml_field "$HOSTS_DIR/$host/identity.yaml" status)"
    case "$status" in
      active)  active=$((active+1)) ;;
      planned) planned=$((planned+1)) ;;
      retired) retired=$((retired+1)) ;;
      *)       other=$((other+1)) ;;
    esac
  done

  {
    printf '# machines — ledger\n\n'
    printf 'Lifecycle summary across all enrolled machines.\n\n'
    printf '| state    | count |\n'
    printf '|----------|-------|\n'
    printf '| active   | %s |\n' "$active"
    printf '| planned  | %s |\n' "$planned"
    printf '| retired  | %s |\n' "$retired"
    if [[ $other -gt 0 ]]; then
      printf '| (unset)  | %s |\n' "$other"
    fi
  } > "$LEDGER_OUT"

  log_info "indexed ${#hosts[@]} machine(s)"
}

function main() {
  require_cmd python3 find

  if [[ ! -d "$HOSTS_DIR" ]]; then
    log_warn "hosts directory missing: $HOSTS_DIR"
    mkdir -p "$HOSTS_DIR"
  fi

  # Collect machine dirs that have an identity.yaml.
  local hosts=()
  local d
  while IFS= read -r -d '' d; do
    local name
    name="$(basename "$d")"
    if [[ -f "$HOSTS_DIR/$name/identity.yaml" ]]; then
      hosts+=("$name")
    fi
  done < <(find "$HOSTS_DIR" -mindepth 1 -maxdepth 1 -type d -print0 2>/dev/null)

  if [[ ${#hosts[@]} -eq 0 ]]; then
    render_empty
  else
    # Sort alphabetically by name.
    IFS=$'\n' read -rd '' -a hosts < <(printf '%s\n' "${hosts[@]}" | sort && printf '\0')
    render_populated "${hosts[@]}"
  fi

  log_info "wrote $README_OUT"
  log_info "wrote $LEDGER_OUT"
}

main "$@"
