#!/usr/bin/env bash
#
# generate-machine-index.sh — regenerate machines/README.md and machines/ledger.md
# from the set of machines/{development,services}/<name>/identity.yaml files.
#
# Usage: ./generate-machine-index.sh
#
# Idempotent. When no host directories contain identity.yaml, both output
# files are rewritten with a "no machines yet" placeholder.
#
# identity.yaml is expected to contain at least:
#   name: <string>
#   os: <string>          # e.g., linux-debian, windows-server, wsl
#   purpose: <string>
#   tailscale_hostname: <string>
#   status: <active|planned|retired>
#
# Missing fields are rendered as "-".
#
set -Eeuo pipefail
IFS=$'\n\t'

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MACHINES_DIR="$(cd "$PROJECT_ROOT/.." && pwd)"
README_OUT="$MACHINES_DIR/README.md"
LEDGER_OUT="$MACHINES_DIR/ledger.md"

CATEGORIES=(development services)

function log_info()  { printf '\033[0;36m[info]\033[0m  %s\n' "$*"; }
function log_warn()  { printf '\033[0;33m[warn]\033[0m  %s\n' "$*" >&2; }
function log_error() { printf '\033[0;31m[error]\033[0m %s\n' "$*" >&2; }

function require_cmd() {
  local missing=()
  local cmd
  for cmd in "$@"; do
    command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd")
  done
  if [[ ${#missing[@]} -gt 0 ]]; then
    log_error "missing required tool(s): ${missing[*]}"
    exit 127
  fi
}

function yaml_field() {
  # Extract a simple "key: value" line from a YAML file. Does not handle
  # block scalars, flow style, anchors, etc. — identity.yaml is intentionally
  # flat. Returns empty string on miss.
  local file="$1" key="$2"
  python3 -c "
import re, sys
try:
    txt = open(sys.argv[1]).read()
    m = re.search(r'^\s*' + re.escape(sys.argv[2]) + r'\s*:\s*[\"\']?([^\"\'\n]+?)[\"\']?\s*\$', txt, re.M)
    print(m.group(1).strip() if m else '')
except Exception:
    print('')
" "$file" "$key"
}

function render_empty() {
  cat > "$README_OUT" <<'EOF'
# machines

No machines enrolled yet. See `machines/CONVENTIONS.md` for how to add one:

1. Pick a template from `machines/templates/<category>/` where `<category>`
   is `development` (workstations) or `services` (cluster nodes, bastions,
   builders).
2. Scaffold with
   `bash machines/ctl.sh new-host <category> <template> <host-name>`.
3. Edit `machines/<category>/<host-name>/identity.yaml` with the real values.
4. Run `bash machines/ctl.sh generate-index` to regenerate this index.

This file is auto-generated — do not edit manually.
EOF

  cat > "$LEDGER_OUT" <<'EOF'
# machines — ledger

Summary of machine lifecycle states. Regenerated by
`machines/scripts/generate-machine-index.sh`.

| State    | Development | Services | Total |
|----------|-------------|----------|-------|
| active   | 0           | 0        | 0     |
| planned  | 0           | 0        | 0     |
| retired  | 0           | 0        | 0     |

No machines enrolled yet.
EOF
  log_info "no machines found — wrote placeholders"
}

# Globals populated by collect_hosts for render_populated to consume.
# Each entry: "<category>/<name>"
HOSTS=()

function collect_hosts() {
  local cat d name
  for cat in "${CATEGORIES[@]}"; do
    local dir="$MACHINES_DIR/$cat"
    [[ -d "$dir" ]] || continue
    while IFS= read -r -d '' d; do
      name="$(basename "$d")"
      if [[ -f "$dir/$name/identity.yaml" ]]; then
        HOSTS+=("$cat/$name")
      fi
    done < <(find "$dir" -mindepth 1 -maxdepth 1 -type d -print0 2>/dev/null)
  done

  # Sort alphabetically.
  if [[ ${#HOSTS[@]} -gt 0 ]]; then
    local sorted=()
    while IFS= read -r line; do sorted+=("$line"); done \
      < <(printf '%s\n' "${HOSTS[@]}" | sort)
    HOSTS=("${sorted[@]}")
  fi
}

function render_populated() {
  # README: two tables — development first, then services.
  {
    printf '# machines\n\n'
    printf 'Auto-generated index. Regenerate with:\n\n'
    printf '    bash machines/ctl.sh generate-index\n\n'

    local cat header_written
    for cat in "${CATEGORIES[@]}"; do
      header_written=false
      local entry rel name os purpose ts status
      for entry in ${HOSTS[@]+"${HOSTS[@]}"}; do
        [[ "$entry" == "$cat/"* ]] || continue
        if ! $header_written; then
          printf '## %s\n\n' "$cat"
          printf '| name | os | purpose | tailscale hostname | status |\n'
          printf '|------|----|---------|--------------------|--------|\n'
          header_written=true
        fi
        rel="${entry#"$cat/"}"
        local id="$MACHINES_DIR/$cat/$rel/identity.yaml"
        name="$(yaml_field "$id" name)"
        os="$(yaml_field "$id" os)"
        purpose="$(yaml_field "$id" purpose)"
        ts="$(yaml_field "$id" tailscale_hostname)"
        status="$(yaml_field "$id" status)"
        printf '| %s | %s | %s | %s | %s |\n' \
          "${name:-$rel}" "${os:--}" "${purpose:--}" "${ts:--}" "${status:--}"
      done
      if $header_written; then
        printf '\n'
      fi
    done
  } > "$README_OUT"

  # Ledger: per-category + total counts.
  local dev_active=0 dev_planned=0 dev_retired=0
  local svc_active=0 svc_planned=0 svc_retired=0
  local entry cat rel status
  for entry in ${HOSTS[@]+"${HOSTS[@]}"}; do
    cat="${entry%%/*}"
    rel="${entry#*/}"
    status="$(yaml_field "$MACHINES_DIR/$cat/$rel/identity.yaml" status)"
    case "$cat:$status" in
      development:active)  dev_active=$((dev_active+1)) ;;
      development:planned) dev_planned=$((dev_planned+1)) ;;
      development:retired) dev_retired=$((dev_retired+1)) ;;
      services:active)     svc_active=$((svc_active+1)) ;;
      services:planned)    svc_planned=$((svc_planned+1)) ;;
      services:retired)    svc_retired=$((svc_retired+1)) ;;
    esac
  done
  local t_active=$((dev_active + svc_active))
  local t_planned=$((dev_planned + svc_planned))
  local t_retired=$((dev_retired + svc_retired))

  {
    printf '# machines — ledger\n\n'
    printf 'Lifecycle summary across all enrolled machines.\n\n'
    printf '| state    | development | services | total |\n'
    printf '|----------|-------------|----------|-------|\n'
    printf '| active   | %s | %s | %s |\n' "$dev_active" "$svc_active" "$t_active"
    printf '| planned  | %s | %s | %s |\n' "$dev_planned" "$svc_planned" "$t_planned"
    printf '| retired  | %s | %s | %s |\n' "$dev_retired" "$svc_retired" "$t_retired"
  } > "$LEDGER_OUT"

  log_info "indexed ${#HOSTS[@]} machine(s)"
}

function main() {
  require_cmd python3 find

  local cat
  for cat in "${CATEGORIES[@]}"; do
    if [[ ! -d "$MACHINES_DIR/$cat" ]]; then
      log_warn "category directory missing: $MACHINES_DIR/$cat"
      mkdir -p "$MACHINES_DIR/$cat"
    fi
  done

  collect_hosts

  if [[ ${#HOSTS[@]} -eq 0 ]]; then
    render_empty
  else
    render_populated
  fi

  log_info "wrote $README_OUT"
  log_info "wrote $LEDGER_OUT"
}

main "$@"
