apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shared-postgres.fullname" . }}-credentials
  labels:
    {{- include "shared-postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.auth.postgresPassword | quote }}
  {{- range .Values.databases }}
  {{ .user }}-password: {{ .password | quote }}
  {{- end }}
