// Package persistence is the http-gateway's typed data layer: a thin, pgx-backed facade over the
// sqlc-generated Querier (ADR-0023, codegen axis #1). It is the home of the persistence port the
// composition root wires and the route execute stages call — TYPED, never string-built SQL. The
// generated typed Querier + row models live in ./generated (regenerated by `bash ./ctl.sh generate`);
// this file is the hand-written constructor + the domain-facing facade that maps pgx's not-found
// sentinel to a typed errors.KindNotFound.
//
// One concept, one home (10 §9): the constructor spine is New(Configuration, Dependencies); the DSN
// arrives as a secrets.Reference (loggable, never the value) and is resolved ONCE through the injected
// Secrets port at startup. No global, no os.Getenv, no module-level pool — the composition root owns
// wiring (the same shape as internal/server.New).
package persistence

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/gophersys/libs/go/errors"
	"github.com/gophersys/libs/go/observability"
	"github.com/gophersys/libs/go/secrets"

	"github.com/gophersys/eden/apps/platformgateway/persistence/generated"
)

// Configuration is the immutable, fully-resolved persistence input (the configuration pattern). It
// holds NO live handles and reads NO environment: the DSN arrives as a loggable secrets.Reference the
// composition root parsed at the edge, and New resolves it to the connection string through the
// injected Secrets port. (Configuration carries the full HNS-1 word — `config` would be banned.)
type Configuration struct {
	// DSN is the secrets Reference the Postgres connection string resolves from at startup. It is
	// loggable and lives in configuration; the value (which may carry a password) never does. REQUIRED.
	DSN secrets.Reference
}

// Dependencies is the injected hexagon: the narrow ports the data layer depends on. New consumes
// ports; it constructs none. (Dependencies carries the full HNS-1 word — `deps` would be banned at
// the package/field-pattern level; the idiomatic struct name is exempt but the field stays spelled.)
type Dependencies struct {
	// Secrets is the redaction port the DSN is resolved through. The connection string is read inside
	// a Secret.Use window and never retained past pool construction. REQUIRED.
	Secrets secrets.Provider
	// Observability is the structured-Event stream the data layer logs lifecycle on (open/close).
	// REQUIRED — telemetry is wired, never dark.
	Observability observability.Provider
}

// Persistence is the concrete value New returns (return-concrete): it owns the pgx pool and exposes
// the typed users store the route execute stages call, plus the embedded startup Migrate. Its zero
// value is unusable; construct via New. Safe for concurrent use — a *pgxpool.Pool is concurrency-safe,
// and the store holds only the generated Querier over it.
type Persistence struct {
	pool          *pgxpool.Pool
	users         *Users
	rbac          *RBAC
	accounts      *Accounts
	connectors    *Connectors
	observability observability.Provider
}

// New is the pure-at-the-edge constructor spine (10 §9): it validates Dependencies, resolves the DSN
// secret ONCE through the injected Secrets port (inside a Use window so the value never escapes), opens
// a pgx pool against it, and returns the concrete *Persistence the server composes. It performs the
// one blocking step a data layer needs — establishing the pool — and pings once so a bad DSN fails
// fast at startup rather than on the first request. On any failure it returns a wrapped, typed error
// and leaks no pool.
//
// The first argument is context so the blocking pool open + ping honor the composition root's startup
// deadline; the spine otherwise mirrors server.New(Configuration, Dependencies).
func New(ctx context.Context, configuration Configuration, dependencies Dependencies) (*Persistence, error) {
	if dependencies.Secrets == nil {
		return nil, errors.New(errors.KindInvalid, "persistence: New requires Dependencies.Secrets")
	}
	if dependencies.Observability == nil {
		return nil, errors.New(errors.KindInvalid, "persistence: New requires Dependencies.Observability")
	}
	if configuration.DSN.IsZero() {
		return nil, errors.New(errors.KindInvalid, "persistence: New requires Configuration.DSN (a secrets.Reference)")
	}

	secret, err := dependencies.Secrets.Resolve(ctx, configuration.DSN)
	if err != nil {
		// The Reference is loggable and rides the error; the value never does.
		return nil, errors.Wrap(errors.KindUnavailable, "persistence: resolve DSN secret", err).
			WithField("dsn-reference", configuration.DSN.String())
	}
	defer secret.Zeroize()

	// Open the pool inside the Use window so the connection string (which may carry a password) is
	// read once and never retained past construction. pgxpool copies the parsed config, so the slice
	// the closure sees does not outlive the call. The pgx error is wrapped HERE (the boundary
	// crossing) so the chain is preserved; the outer guard only attaches the loggable reference.
	pool, err := secrets.Use1(secret, func(plaintext []byte) (*pgxpool.Pool, error) {
		p, perr := pgxpool.New(ctx, string(plaintext))
		if perr != nil {
			return nil, errors.Wrap(errors.KindUnavailable, "persistence: open pgx pool", perr)
		}
		return p, nil
	})
	if err != nil {
		return nil, errors.Wrap(errors.KindUnavailable, "persistence: open pgx pool", err).
			WithField("dsn-reference", configuration.DSN.String())
	}

	// Fail fast on a bad DSN: a pool that cannot reach Postgres is a startup error, not a per-request
	// surprise. Reap the pool on a failed ping so New leaks nothing.
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, errors.Wrap(errors.KindUnavailable, "persistence: ping Postgres", err).
			WithField("dsn-reference", configuration.DSN.String())
	}

	dependencies.Observability.Log(ctx, observability.SeverityInfo, "persistence: pool open",
		observability.String("dsn-reference", configuration.DSN.String()))

	queries := generated.New(pool)
	return &Persistence{
		pool:          pool,
		users:         &Users{queries: queries},
		rbac:          &RBAC{queries: queries},
		accounts:      &Accounts{queries: queries},
		connectors:    &Connectors{pool: pool, queries: queries},
		observability: dependencies.Observability,
	}, nil
}

// Users returns the typed users store the route execute stages call (accept-interfaces,
// return-concrete — the consumer receives a usable store, not another port). The store maps pgx's
// not-found sentinel to a typed errors.KindNotFound and owns the idempotent default-user seed.
func (p *Persistence) Users() *Users { return p.users }

// RBAC returns the typed RBAC store the /v1/me route + the login bootstrap call (accept-interfaces,
// return-concrete — a usable store, not another port). It owns the membership read (maps pgx's
// not-found to a typed errors.KindNotFound) and the idempotent org/permission-set/membership seed.
func (p *Persistence) RBAC() *RBAC { return p.rbac }

// Accounts returns the typed linked-identity store the login Authenticator + the password-account seed
// call (accept-interfaces, return-concrete — a usable store, not another port). It owns the credential
// read by (provider, provider_account_id) (maps pgx's not-found to a typed errors.KindNotFound) and the
// idempotent find-or-create seed — the OAuth-ready authentication seam.
func (p *Persistence) Accounts() *Accounts { return p.accounts }

// Connectors returns the typed connector store the /v1/connectors routes call (accept-interfaces,
// return-concrete — a usable store, not another port). It owns the envelope-sealed user-credential
// storage (two-write create/replace in one transaction), the tenant-scoped reads, and the pgx-not-found
// → KindNotFound / unique-violation → KindConflict mappings (ADR-0029, doc 19).
func (p *Persistence) Connectors() *Connectors { return p.connectors }

// Close releases the pool. Idempotent: a second Close is a no-op (a nil pool short-circuits), so the
// composition root may defer it unconditionally. It logs the close on the observability stream.
func (p *Persistence) Close() {
	if p == nil || p.pool == nil {
		return
	}
	p.observability.Log(context.Background(), observability.SeverityInfo, "persistence: pool close")
	p.pool.Close()
	p.pool = nil
}

// isNoRows reports whether err is pgx's no-rows sentinel — the single place the data layer translates
// "the query found nothing" into the domain's typed not-found. Kept here so the mapping lives once.
func isNoRows(err error) bool { return errors.Is(err, pgx.ErrNoRows) }
