FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y python3 python3-pip libgpiod-dev python3-libgpiod usbutils i2c-tools && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY apps/edge/mtib-server/setup.py setup.py
RUN pip install -e . && pip cache purge

COPY libs/python /libs/python
COPY libs/protocols/mtib /libs/protocols/mtib
ENV PYTHONPATH="/libs:/libs/protocols:/libs/python/:${PYTHONPATH}"

COPY apps/edge/mtib-server/src src

# Skip FluidNC assets — not needed for Joulescope test
RUN mkdir -p /app/assets && echo "ok" > /app/assets/config.yaml

ENTRYPOINT ["python3", "src/main.py"]
