apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    {{- include "shared-grafana.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      {{- if .Values.datasource.clickhouse.enabled }}
      - name: ClickHouse
        type: grafana-clickhouse-datasource
        access: proxy
        isDefault: true
        jsonData:
          host: {{ .Values.datasource.clickhouse.host }}
          port: {{ .Values.datasource.clickhouse.httpPort }}
          protocol: http
          defaultDatabase: {{ .Values.datasource.clickhouse.database }}
          username: {{ .Values.datasource.clickhouse.user }}
        secureJsonData:
          password: {{ .Values.datasource.clickhouse.password | quote }}
      {{- end }}
