apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  labels:
    {{- include "shared-grafana.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.auth.adminPassword | quote }}
