apiVersion: v1
kind: Service
metadata:
  name: {{ include "shared-grafana.fullname" . }}
  labels:
    {{- include "shared-grafana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "shared-grafana.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
