// Skin gallery sweep (shadcn transposition) — drives the REAL vite dev-serve (started by
// screenshots-skin.sh) and captures every reskinned surface in BOTH themes to /tmp/ui-audit/skin/.
// Real flows over the dev-serve (no page.route stubs except the fake-project spine, which has no live
// saga here). Not a gate — a visual-evidence harness reusing the same real substrate the e2e uses.
import { chromium } from '@playwright/test';

const BASE = process.env.E2E_BASE_URL;
if (!BASE) throw new Error('E2E_BASE_URL is required');
const OUT = '/tmp/ui-audit/skin';

const PROJECT_ID = 'proj-skin-demo';
const SUPERVISOR_ID = 'sess-skin-supervisor';
const FAKE_PROJECT = {
  data: {
    id: PROJECT_ID,
    name: 'Aurora Ledger',
    idea: 'A double-entry ledger service generated by Eden.',
    kind: 'service',
    status: 'building',
    harness: 'claude',
    stacks: ['go', 'svelte'],
    services: ['postgres'],
    supervisorAgentId: SUPERVISOR_ID,
    repoUrl: 'https://github.com/eden-demo/aurora-ledger',
    defaultBranch: 'init/seed',
    createdAt: '2026-06-22T10:00:00Z',
    updatedAt: '2026-06-22T10:05:00Z',
  },
  errors: [],
  kind: '',
};
const FAKE_REPORT = {
  schemaVersion: '1.0.0',
  repository: {
    identifier: 'Aurora Ledger',
    headCommit: 'abcdef0123456789abcdef0123456789abcdef01',
    analyzedAt: '2026-06-22T10:06:00Z',
    commitCount: 42,
  },
  window: { toCommit: 'abcdef0123456789abcdef0123456789abcdef01', revisions: 42 },
  entities: [
    {
      path: 'internal/ledger/posting.go',
      kind: 'file',
      language: 'go',
      lines: 320,
      cyclomatic: 18,
      maintainability: 68,
      churnAbsolute: 210,
      churnRelative: 0.65,
      changeFrequency: 12,
      hotspotScore: 0.82,
    },
    {
      path: 'internal/ledger/balance.go',
      kind: 'file',
      language: 'go',
      lines: 140,
      cyclomatic: 6,
      maintainability: 84,
      churnAbsolute: 40,
      churnRelative: 0.28,
      changeFrequency: 4,
      hotspotScore: 0.31,
    },
    {
      path: 'cmd/ledger/main.go',
      kind: 'file',
      language: 'go',
      lines: 60,
      cyclomatic: 3,
      maintainability: 92,
      churnAbsolute: 12,
      churnRelative: 0.2,
      changeFrequency: 2,
      hotspotScore: 0.12,
    },
  ],
  couplings: [],
  ownership: [],
  summary: {
    lines: 520,
    entityCount: 3,
    technicalDebtRatio: 0.08,
    maintainabilityRating: 'B',
    busFactor: 2,
  },
  trends: [],
  views: [],
};

async function stubProject(page) {
  await page.route(
    (url) => url.pathname.includes('/gateway/'),
    async (route) => {
      const url = new URL(route.request().url());
      const path = url.pathname.replace(/^.*\/gateway/, '');
      if (path === `/projects/${PROJECT_ID}/insight`) return route.fulfill({ json: FAKE_REPORT });
      if (path === `/projects/${PROJECT_ID}`) return route.fulfill({ json: FAKE_PROJECT });
      if (path === '/healthz') return route.fulfill({ json: { status: 'ok' } });
      return route.continue();
    },
  );
}

async function setTheme(page, mode) {
  await page.addInitScript((m) => {
    try {
      localStorage.setItem('eden-theme', m);
    } catch {
      /* private mode */
    }
  }, mode);
}

const wait = (page, ms = 400) => page.waitForTimeout(ms);

async function shoot(page, name, mode) {
  await wait(page, 300);
  await page.screenshot({ path: `${OUT}/${name}-${mode}.png` });
}

async function run(browser, mode) {
  const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  const page = await ctx.newPage();
  await setTheme(page, mode);

  // login
  await page.goto(`${BASE}/login`, { waitUntil: 'networkidle' });
  await page.getByTestId('login-screen').waitFor({ state: 'visible', timeout: 15000 });
  await shoot(page, 'login', mode);

  // projects (empty on the real dev-serve)
  await page.goto(`${BASE}/projects`, { waitUntil: 'networkidle' });
  await page.getByTestId('dash-empty').waitFor({ state: 'visible', timeout: 15000 });
  await shoot(page, 'projects-empty', mode);

  // build view (/chat) — the empty build workspace + session rail
  await page.goto(`${BASE}/chat`, { waitUntil: 'networkidle' });
  await page.getByTestId('chat-app').waitFor({ state: 'visible', timeout: 15000 });
  await page.getByTestId('gateway-health').waitFor({ state: 'visible', timeout: 15000 });
  await shoot(page, 'build', mode);

  // wizard SPARK (create flow full-screen)
  await page.getByTestId('new-session').first().click();
  await page.getByTestId('create-flow').waitFor({ state: 'visible', timeout: 15000 });
  await shoot(page, 'wizard-spark', mode);
  // wizard REVIEW (drive a real propose round-trip against the dev-serve)
  await page
    .getByTestId('create-spark')
    .fill('A tool that turns my invoices into a clean dashboard');
  await page.getByTestId('create-start').click();
  try {
    await page.getByTestId('create-scope').waitFor({ state: 'visible', timeout: 15000 });
    await shoot(page, 'wizard-review', mode);
  } catch {
    // propose unavailable on this dev-serve — skip the review shot, keep going.
  }
  // close the flow
  await page
    .getByTestId('create-cancel')
    .click()
    .catch(() => {});

  // sessions list (empty)
  await page.goto(`${BASE}/sessions`, { waitUntil: 'networkidle' });
  await page.getByTestId('sessions-page').waitFor({ state: 'visible', timeout: 15000 });
  await shoot(page, 'sessions', mode);

  // clusters (the north star — chrome-aligned)
  await page.goto(`${BASE}/clusters`, { waitUntil: 'networkidle' });
  await wait(page, 900);
  await shoot(page, 'clusters', mode);

  // project overview + insight (over the fake project)
  await stubProject(page);
  await page.goto(`${BASE}/projects/${PROJECT_ID}`, { waitUntil: 'networkidle' });
  await page.getByTestId('project-overview').waitFor({ state: 'visible', timeout: 15000 });
  await shoot(page, 'overview', mode);
  await page.goto(`${BASE}/projects/${PROJECT_ID}/insight`, { waitUntil: 'networkidle' });
  await page.getByTestId('insight-hotspot').waitFor({ state: 'visible', timeout: 15000 });
  await shoot(page, 'insight', mode);
  await page.unrouteAll({ behavior: 'ignoreErrors' });

  // settings → agents
  await page.goto(`${BASE}/projects`, { waitUntil: 'networkidle' });
  await page.getByTestId('user-settings-open').click();
  await page.getByTestId('settings-surface').waitFor({ state: 'visible', timeout: 15000 });
  await page.locator('.eden-settings-surface-rail-item[data-section="agents"]').click();
  await shoot(page, 'settings-agents', mode);
  // settings → connectors (empty product surface)
  await page.locator('.eden-settings-surface-rail-item[data-section="connectors"]').click();
  await page.getByTestId('settings-connectors').waitFor({ state: 'visible', timeout: 15000 });
  await shoot(page, 'settings-connectors', mode);

  await ctx.close();
}

const browser = await chromium.launch();
try {
  await run(browser, 'light');
  await run(browser, 'dark');
  console.log('skin gallery written to', OUT);
} finally {
  await browser.close();
}
