// W4 screenshot sweep — drives the REAL vite dev-serve (started by screenshots.sh) and captures the
// five wave-4 surfaces to /tmp/ui-audit/. The Overview + Insight are shot over a fake project fixture
// (page.route, pathname-predicate — never a glob) since a live saga is not booted here; the empty
// projects state + the settings sheet are shot against the real dev-serve. Light + one dark shot.
import { chromium } from 'playwright';

const BASE = process.env.E2E_BASE_URL;
if (!BASE) throw new Error('E2E_BASE_URL is required');
const OUT = '/tmp/ui-audit';

const PROJECT_ID = 'proj-shot-demo';
const SUPERVISOR_ID = 'sess-shot-supervisor';
const FAKE_PROJECT = {
  data: {
    id: PROJECT_ID,
    name: 'Aurora Ledger',
    idea: 'A double-entry ledger service generated by Eden.',
    kind: 'service',
    status: 'building',
    harness: 'claude',
    stacks: ['go', 'svelte'],
    services: ['postgres'],
    supervisorAgentId: SUPERVISOR_ID,
    repoUrl: 'https://github.com/eden-demo/aurora-ledger',
    defaultBranch: 'init/seed',
    createdAt: '2026-06-22T10:00:00Z',
    updatedAt: '2026-06-22T10:05:00Z',
  },
  errors: [],
  kind: '',
};
const FAKE_REPORT = {
  schemaVersion: '1.0.0',
  repository: {
    identifier: 'Aurora Ledger',
    headCommit: 'abcdef0123456789abcdef0123456789abcdef01',
    analyzedAt: '2026-06-22T10:06:00Z',
    commitCount: 42,
  },
  window: { toCommit: 'abcdef0123456789abcdef0123456789abcdef01', revisions: 42 },
  entities: [
    {
      path: 'internal/ledger/posting.go',
      kind: 'file',
      language: 'go',
      lines: 320,
      cyclomatic: 18,
      maintainability: 68,
      churnAbsolute: 210,
      churnRelative: 0.65,
      changeFrequency: 12,
      hotspotScore: 0.82,
    },
    {
      path: 'internal/ledger/balance.go',
      kind: 'file',
      language: 'go',
      lines: 140,
      cyclomatic: 6,
      maintainability: 84,
      churnAbsolute: 40,
      churnRelative: 0.28,
      changeFrequency: 4,
      hotspotScore: 0.31,
    },
    {
      path: 'cmd/ledger/main.go',
      kind: 'file',
      language: 'go',
      lines: 60,
      cyclomatic: 3,
      maintainability: 92,
      churnAbsolute: 12,
      churnRelative: 0.2,
      changeFrequency: 2,
      hotspotScore: 0.12,
    },
  ],
  couplings: [],
  ownership: [],
  summary: {
    lines: 520,
    entityCount: 3,
    technicalDebtRatio: 0.08,
    maintainabilityRating: 'B',
    busFactor: 2,
  },
  trends: [],
  views: [],
};

async function stubProject(page) {
  await page.route(
    (url) => url.pathname.startsWith('/gateway/'),
    async (route) => {
      const url = new URL(route.request().url());
      const path = url.pathname.replace(/^.*\/gateway/, '');
      if (path === `/projects/${PROJECT_ID}/insight`) return route.fulfill({ json: FAKE_REPORT });
      if (path === `/projects/${PROJECT_ID}`) return route.fulfill({ json: FAKE_PROJECT });
      if (path === '/healthz') return route.fulfill({ json: { status: 'ok' } });
      return route.fulfill({ status: 404, json: { kind: 'not-found', message: path } });
    },
  );
}

const browser = await chromium.launch();
try {
  const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  const page = await ctx.newPage();

  // 1) projects empty state — the real dev-serve seeds no projects, so /projects renders dash-empty.
  await page.goto(`${BASE}/projects`, { waitUntil: 'networkidle' });
  await page.getByTestId('dash-empty').waitFor({ state: 'visible', timeout: 15000 });
  await page.screenshot({ path: `${OUT}/wave4-projects-empty.png` });

  // 2) overview — over the fake building project.
  await stubProject(page);
  await page.goto(`${BASE}/projects/${PROJECT_ID}`, { waitUntil: 'networkidle' });
  await page.getByTestId('project-overview').waitFor({ state: 'visible', timeout: 15000 });
  await page.screenshot({ path: `${OUT}/wave4-overview.png` });

  // 3) insight — the hotspot map + summary over the fake report.
  await page.goto(`${BASE}/projects/${PROJECT_ID}/insight`, { waitUntil: 'networkidle' });
  await page.getByTestId('insight-hotspot').waitFor({ state: 'visible', timeout: 15000 });
  await page.waitForTimeout(400);
  await page.screenshot({ path: `${OUT}/wave4-insight.png` });

  // 4) settings (light) — drop the fake-project stub so /projects reads the REAL (empty) dev-serve
  //    list, then open the sheet from the sidebar user affordance (→ Agents) and click Appearance so
  //    the shot shows the colour-mode control + the rail over a clean empty dashboard.
  await page.unrouteAll({ behavior: 'ignoreErrors' });
  await page.goto(`${BASE}/projects`, { waitUntil: 'networkidle' });
  await page.getByTestId('user-settings-open').click();
  await page.getByTestId('settings-surface').waitFor({ state: 'visible', timeout: 15000 });
  await page.locator('.eden-settings-surface-rail-item[data-section="appearance"]').click();
  await page.waitForTimeout(300);
  await page.screenshot({ path: `${OUT}/wave4-settings.png` });

  // 5) settings (dark) — flip to Dark the REAL way (click the Appearance colour-mode control), which
  //    drives the themePreference store → the sheet chrome + the app content both retheme LIVE. Then
  //    switch to Agents so the dark shot shows the config cards under the dark sheet.
  await page.getByTestId('settings-colormode-dark').click();
  await page.waitForTimeout(300);
  await page.locator('.eden-settings-surface-rail-item[data-section="agents"]').click();
  await page.waitForTimeout(300);
  await page.screenshot({ path: `${OUT}/wave4-settings-dark.png` });

  console.log('screenshots written to', OUT);
} finally {
  await browser.close();
}
