// W5 FINAL GALLERY sweep (doc 17 W-UI-5) — drives the REAL vite dev-serve (started by
// screenshots-w5.sh) and captures EVERY screen in BOTH themes to /tmp/ui-audit/final/. The chat/Build
// view is driven through the REAL create flow (the dev-serve scripts a real agent that streams the
// canonical taxonomy — a "Hello, world" answer, a Write tool card, a usage tick), so the Build shot
// shows a live transcript, not an empty state. The Overview + Insight are shot over a fake project
// fixture (page.route, pathname-predicate) since a live saga is not booted here. Every other surface
// is the real dev-serve. Named final-<screen>-{light,dark}.png.
import { chromium } from 'playwright';

const BASE = process.env.E2E_BASE_URL;
if (!BASE) throw new Error('E2E_BASE_URL is required');
const OUT = '/tmp/ui-audit/final';

const PROJECT_ID = 'proj-shot-demo';
const SUPERVISOR_ID = 'sess-shot-supervisor';
const FAKE_PROJECT = {
  data: {
    id: PROJECT_ID,
    name: 'Aurora Ledger',
    idea: 'A double-entry ledger service generated by Eden.',
    kind: 'service',
    status: 'building',
    harness: 'claude',
    stacks: ['go', 'svelte'],
    services: ['postgres'],
    supervisorAgentId: SUPERVISOR_ID,
    repoUrl: 'https://github.com/eden-demo/aurora-ledger',
    defaultBranch: 'init/seed',
    createdAt: '2026-06-22T10:00:00Z',
    updatedAt: '2026-06-22T10:05:00Z',
  },
  errors: [],
  kind: '',
};
const FAKE_REPORT = {
  schemaVersion: '1.0.0',
  repository: {
    identifier: 'Aurora Ledger',
    headCommit: 'abcdef0123456789abcdef0123456789abcdef01',
    analyzedAt: '2026-06-22T10:06:00Z',
    commitCount: 42,
  },
  window: { toCommit: 'abcdef0123456789abcdef0123456789abcdef01', revisions: 42 },
  entities: [
    {
      path: 'internal/ledger/posting.go',
      kind: 'file',
      language: 'go',
      lines: 320,
      cyclomatic: 18,
      maintainability: 68,
      churnAbsolute: 210,
      churnRelative: 0.65,
      changeFrequency: 12,
      hotspotScore: 0.82,
    },
    {
      path: 'internal/ledger/balance.go',
      kind: 'file',
      language: 'go',
      lines: 140,
      cyclomatic: 6,
      maintainability: 84,
      churnAbsolute: 40,
      churnRelative: 0.28,
      changeFrequency: 4,
      hotspotScore: 0.31,
    },
    {
      path: 'cmd/ledger/main.go',
      kind: 'file',
      language: 'go',
      lines: 60,
      cyclomatic: 3,
      maintainability: 92,
      churnAbsolute: 12,
      churnRelative: 0.2,
      changeFrequency: 2,
      hotspotScore: 0.12,
    },
  ],
  couplings: [],
  ownership: [],
  summary: {
    lines: 520,
    entityCount: 3,
    technicalDebtRatio: 0.08,
    maintainabilityRating: 'B',
    busFactor: 2,
  },
  trends: [],
  views: [],
};

/** Force the app into a colour mode the REAL way: seed the same localStorage key the app.html
 *  bootstrap + themePreference store read, so the first paint is already themed (no flash). */
async function setTheme(page, mode) {
  await page.addInitScript((m) => {
    try {
      localStorage.setItem('eden-theme', m);
    } catch {
      /* private mode — the store falls back to system */
    }
  }, mode);
}

async function stubProject(page) {
  await page.route(
    (url) => url.pathname.startsWith('/gateway/'),
    async (route) => {
      const url = new URL(route.request().url());
      const path = url.pathname.replace(/^.*\/gateway/, '');
      if (path === `/projects/${PROJECT_ID}/insight`) return route.fulfill({ json: FAKE_REPORT });
      if (path === `/projects/${PROJECT_ID}`) return route.fulfill({ json: FAKE_PROJECT });
      if (path === '/healthz') return route.fulfill({ json: { status: 'ok' } });
      return route.fulfill({ status: 404, json: { kind: 'not-found', message: path } });
    },
  );
}

/** Drive the real create flow to a live transcript (Spark → Review → Build it), the SAME path the
 *  chat-slice e2e drives. Leaves the Build view showing a streamed answer + tool card + usage. */
async function driveBuildTranscript(page, base) {
  await page.goto(`${base}/chat`, { waitUntil: 'networkidle' });
  await page.getByTestId('chat-app').waitFor({ state: 'visible', timeout: 15000 });
  await page.getByTestId('gateway-health').waitFor({ state: 'visible', timeout: 15000 });
  await page.getByTestId('new-session').first().click();
  await page.getByTestId('create-flow').waitFor({ state: 'visible', timeout: 15000 });
  await page.getByTestId('create-spark').fill('Write a note and say hello.');
  await page.getByTestId('create-start').click();
  await page.getByTestId('create-launch').waitFor({ state: 'visible', timeout: 15000 });
  await page.getByTestId('create-launch').click();
  await page.getByTestId('active-harness').waitFor({ state: 'visible', timeout: 15000 });
  // Wait for the real streamed answer to render (proves the transcript is populated).
  await page
    .getByTestId('assistant-text')
    .filter({ hasText: 'Hello, world' })
    .first()
    .waitFor({ state: 'visible', timeout: 20000 });
  await page.waitForTimeout(500);
}

/** Capture the full gallery for one colour mode. */
async function shootMode(browser, mode, base) {
  const suffix = mode === 'dark' ? 'dark' : 'light';
  const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  const page = await ctx.newPage();
  await setTheme(page, mode);

  // 1) login (outside the shell).
  await page.goto(`${base}/login`, { waitUntil: 'networkidle' });
  await page.getByTestId('login-screen').waitFor({ state: 'visible', timeout: 15000 });
  await page.waitForTimeout(300);
  await page.screenshot({ path: `${OUT}/final-login-${suffix}.png` });

  // 2) projects — the dashboard. Wait on the always-present dashboard root (not the empty state):
  //    the light pass shoots the EMPTY product surface (the real dev-serve seeds none), and the dark
  //    pass shoots the POPULATED grid (the light pass's create flow persisted a project), so the
  //    gallery carries both the empty + populated variants across the two themes.
  await page.goto(`${base}/projects`, { waitUntil: 'networkidle' });
  await page.getByTestId('projects-dashboard').waitFor({ state: 'visible', timeout: 15000 });
  await page.waitForTimeout(400);
  await page.screenshot({ path: `${OUT}/final-projects-${suffix}.png` });

  // 3) sessions (empty product surface).
  await page.goto(`${base}/sessions`, { waitUntil: 'networkidle' });
  await page.getByTestId('sessions-page').waitFor({ state: 'visible', timeout: 15000 });
  await page.waitForTimeout(300);
  await page.screenshot({ path: `${OUT}/final-sessions-${suffix}.png` });

  // 4) clusters (the north star).
  await page.goto(`${base}/clusters`, { waitUntil: 'networkidle' });
  await page.waitForTimeout(700);
  await page.screenshot({ path: `${OUT}/final-clusters-${suffix}.png` });

  // 5) project OVERVIEW + 6) INSIGHT — over the fake building project.
  await stubProject(page);
  await page.goto(`${base}/projects/${PROJECT_ID}`, { waitUntil: 'networkidle' });
  await page.getByTestId('project-overview').waitFor({ state: 'visible', timeout: 15000 });
  await page.waitForTimeout(300);
  await page.screenshot({ path: `${OUT}/final-overview-${suffix}.png` });

  await page.goto(`${base}/projects/${PROJECT_ID}/insight`, { waitUntil: 'networkidle' });
  await page.getByTestId('insight-hotspot').waitFor({ state: 'visible', timeout: 15000 });
  await page.waitForTimeout(400);
  await page.screenshot({ path: `${OUT}/final-insight-${suffix}.png` });
  await page.unrouteAll({ behavior: 'ignoreErrors' });

  // 7) BUILD (chat) — a live transcript over the real create flow.
  await driveBuildTranscript(page, base);
  await page.screenshot({ path: `${OUT}/final-build-${suffix}.png` });
  // tear the session down so the dev-serve has no orphan live handle before the next mode.
  await page
    .getByTestId('stop')
    .click()
    .catch(() => {});
  await page
    .getByTestId('empty-state')
    .waitFor({ state: 'visible', timeout: 10000 })
    .catch(() => {});

  // 8) WIZARD spark + 9) review — the full-screen create flow.
  await page.goto(`${base}/chat?new=1`, { waitUntil: 'networkidle' });
  await page.getByTestId('create-flow').waitFor({ state: 'visible', timeout: 15000 });
  await page.waitForTimeout(300);
  await page.screenshot({ path: `${OUT}/final-wizard-spark-${suffix}.png` });
  await page.getByTestId('create-spark').fill('A payments service in Go');
  await page.getByTestId('create-start').click();
  await page.getByTestId('create-flow').waitFor({ state: 'visible', timeout: 15000 });
  await page
    .getByTestId('create-scope')
    .waitFor({ state: 'visible', timeout: 15000 })
    .catch(() => {});
  await page.waitForTimeout(500);
  await page.screenshot({ path: `${OUT}/final-wizard-review-${suffix}.png` });
  await page.keyboard.press('Escape').catch(() => {});

  // 10) SETTINGS — Appearance then Agents (open from the sidebar user affordance).
  await page.goto(`${base}/projects`, { waitUntil: 'networkidle' });
  await page.getByTestId('user-settings-open').click();
  await page.getByTestId('settings-surface').waitFor({ state: 'visible', timeout: 15000 });
  await page.locator('.eden-settings-surface-rail-item[data-section="appearance"]').click();
  await page.waitForTimeout(300);
  await page.screenshot({ path: `${OUT}/final-settings-appearance-${suffix}.png` });
  await page.locator('.eden-settings-surface-rail-item[data-section="agents"]').click();
  await page.waitForTimeout(300);
  await page.screenshot({ path: `${OUT}/final-settings-agents-${suffix}.png` });

  await ctx.close();
}

const browser = await chromium.launch();
try {
  await shootMode(browser, 'light', BASE);
  await shootMode(browser, 'dark', BASE);
  console.log('W5 gallery written to', OUT);
} finally {
  await browser.close();
}
