import { expect, test, type Page, type Route } from '@playwright/test';

// Render test for the project WORKSPACE route (the XCode-like 3-pane workspace, W4) over a FAKE
// project + a FAKE worktree. The gateway is not booted: the four surfaces the workspace reads are
// intercepted with page.route and fulfilled with deterministic fixtures —
//   • GET /projects/{id}                     → the enveloped projectView (branch/repo/status/stacks/
//                                              supervisor),
//   • GET /sessions/{id}/workspace           → the worktree file LIST (init/product/* + a JSON file),
//   • GET /sessions/{id}/workspace/file?path → the file-READ contract the workspace specifies
//                                              ({ path, kind, text }),
//   • GET /sessions/{id}/events              → a canonical SSE transcript (the agentsession Event
//                                              taxonomy) the chat rails fold + render.
// A green run PROVES the 3-pane shell composes, the top bar renders the git/settings info, the
// supervisor conversation renders the streamed taxonomy off the REAL SSE parser, and the center pane
// renders the worktree tree + the markdown/JSON viewer — all without a live backend.

const PROJECT_ID = 'proj-workspace-demo';
const SUPERVISOR_ID = 'sess-supervisor-demo';

/** The fake project the route reads (the enveloped projectView; getProject unwraps `.data`). The
 *  fields are exactly the ones the top bar + the session binding consume. */
const FAKE_PROJECT = {
  data: {
    id: PROJECT_ID,
    name: 'Aurora Ledger',
    idea: 'A double-entry ledger service.',
    kind: 'service',
    status: 'building',
    harness: 'claude',
    stacks: ['go', 'svelte'],
    services: ['postgres'],
    supervisorAgentId: SUPERVISOR_ID,
    repoUrl: 'https://github.com/eden-demo/aurora-ledger',
    defaultBranch: 'init/seed',
    createdAt: '2026-06-22T10:00:00Z',
    updatedAt: '2026-06-22T10:05:00Z',
  },
  errors: [],
  kind: '',
};

/** The fake worktree listing — the committed init/product assets the center pane renders. */
const FAKE_WORKTREE = {
  files: [
    { path: 'init/product/PRODUCT.md', size: 412, modifiedUnix: 1_750_000_000 },
    { path: 'init/product/spec.json', size: 96, modifiedUnix: 1_750_000_100 },
    { path: 'README.md', size: 64, modifiedUnix: 1_750_000_200 },
  ],
};

/** The fake file contents keyed by relative path (the file-read contract: { path, kind, text }). */
const FAKE_CONTENT: Record<string, { kind: string; text: string }> = {
  'init/product/PRODUCT.md': {
    kind: 'markdown',
    text: '# Aurora Ledger\n\nA **double-entry** ledger service generated by Eden.\n\n- balances\n- postings\n',
  },
  'init/product/spec.json': {
    kind: 'json',
    text: '{"productKind":"service","stack":{"languages":["go"]}}',
  },
  'README.md': { kind: 'markdown', text: '# Aurora Ledger\n\nSee init/product for the spec.\n' },
};

/** A canonical SSE transcript over the real event-stream framing the gateway writes (event: / id: /
 *  data: / blank line). It exercises the taxonomy the conversation renders: ready state → an
 *  assistant message (start + text-delta + end) → a Write tool (start + end) → a usage tick → a
 *  clean terminal result. The reader ends the stream on the terminal event. */
function sseTranscript(): string {
  const frames: Array<{ kind: string; seq: number; data: Record<string, unknown> }> = [
    {
      kind: 'session-state',
      seq: 1,
      data: {
        sessionId: SUPERVISOR_ID,
        seq: 1,
        kind: 'session-state',
        time: '2026-06-22T10:05:01Z',
        state: { from: 'initializing', to: 'ready', allowed: ['prompt'], canResolve: false },
      },
    },
    {
      kind: 'message-start',
      seq: 2,
      data: {
        sessionId: SUPERVISOR_ID,
        seq: 2,
        kind: 'message-start',
        turnId: 't1',
        time: '2026-06-22T10:05:02Z',
      },
    },
    {
      kind: 'text-delta',
      seq: 3,
      data: {
        sessionId: SUPERVISOR_ID,
        seq: 3,
        kind: 'text-delta',
        turnId: 't1',
        time: '2026-06-22T10:05:03Z',
        message: { role: 'assistant', delta: 'Scaffolding the ledger service.' },
      },
    },
    {
      kind: 'message-end',
      seq: 4,
      data: {
        sessionId: SUPERVISOR_ID,
        seq: 4,
        kind: 'message-end',
        turnId: 't1',
        time: '2026-06-22T10:05:04Z',
      },
    },
    {
      kind: 'tool-start',
      seq: 5,
      data: {
        sessionId: SUPERVISOR_ID,
        seq: 5,
        kind: 'tool-start',
        turnId: 't1',
        time: '2026-06-22T10:05:05Z',
        tool: { callId: 'c1', name: 'Write', argsSummary: 'path=init/product/PRODUCT.md' },
      },
    },
    {
      kind: 'tool-end',
      seq: 6,
      data: {
        sessionId: SUPERVISOR_ID,
        seq: 6,
        kind: 'tool-end',
        turnId: 't1',
        time: '2026-06-22T10:05:06Z',
        tool: {
          callId: 'c1',
          name: 'Write',
          outcome: 'ok',
          resultDigest: 'wrote 412 bytes',
          durationMs: 12,
        },
      },
    },
    {
      kind: 'usage',
      seq: 7,
      data: {
        sessionId: SUPERVISOR_ID,
        seq: 7,
        kind: 'usage',
        time: '2026-06-22T10:05:07Z',
        usage: {
          model: 'fake-fable-5',
          harness: 'claude',
          inputTokens: 100,
          outputTokens: 40,
          cacheReadTokens: 0,
          cacheCreationTokens: 0,
          costMicros: 1500,
          cumulative: true,
        },
      },
    },
    {
      kind: 'result',
      seq: 8,
      data: {
        sessionId: SUPERVISOR_ID,
        seq: 8,
        kind: 'result',
        time: '2026-06-22T10:05:08Z',
        terminal: {
          outcome: 'completed',
          resultText: 'Scaffold committed.',
          ledger: {
            model: 'fake-fable-5',
            harness: 'claude',
            inputTokens: 100,
            outputTokens: 40,
            cacheReadTokens: 0,
            cacheCreationTokens: 0,
            costMicros: 1500,
            turns: 1,
            toolUses: 1,
            wallTimeMs: 7000,
          },
        },
      },
    },
  ];
  return (
    frames
      .map((f) => `event: ${f.kind}\nid: ${f.seq}\ndata: ${JSON.stringify(f.data)}\n`)
      .join('\n') + '\n'
  );
}

/** Wire the four gateway surfaces onto deterministic fixtures. The workspace resolves the gateway to
 *  the same-origin `/gateway` proxy by default, so every gateway call lands under `**\/gateway/**`. */
async function stubGateway(page: Page): Promise<void> {
  // Match by PATHNAME, not the '**/gateway/**' glob: under `vite dev` the app's own source modules
  // live at /src/lib/gateway/*.ts, which that glob also matches — the stub then 404s the app's JS,
  // the route chunk fails its dynamic import, and SvelteKit shows its 500 page (the long-standing
  // "workspace-render 500" flake). Only the same-origin API prefix /gateway/ is the stub's business.
  await page.route(
    (url) => url.pathname.startsWith('/gateway/'),
    async (route: Route) => {
      const url = new URL(route.request().url());
      const path = url.pathname.replace(/^.*\/gateway/, '');

      if (path === `/projects/${PROJECT_ID}`) {
        await route.fulfill({ json: FAKE_PROJECT });
        return;
      }
      if (path === `/sessions/${SUPERVISOR_ID}/workspace`) {
        await route.fulfill({ json: FAKE_WORKTREE });
        return;
      }
      if (path === `/sessions/${SUPERVISOR_ID}/workspace/file`) {
        const wanted = url.searchParams.get('path') ?? '';
        const found = FAKE_CONTENT[wanted];
        if (!found) {
          await route.fulfill({
            status: 404,
            json: { kind: 'not-found', message: 'no such file' },
          });
          return;
        }
        await route.fulfill({ json: { path: wanted, kind: found.kind, text: found.text } });
        return;
      }
      if (path === `/sessions/${SUPERVISOR_ID}/events`) {
        await route.fulfill({
          status: 200,
          contentType: 'text/event-stream',
          headers: { 'cache-control': 'no-cache' },
          body: sseTranscript(),
        });
        return;
      }
      if (path === '/healthz') {
        await route.fulfill({ json: { status: 'ok' } });
        return;
      }
      await route.fulfill({ status: 404, json: { kind: 'not-found', message: path } });
    },
  );
}

test.describe('project workspace — 3-pane render over a fake project + worktree', () => {
  test('renders the top bar, supervisor conversation, and the worktree tree + viewer', async ({
    page,
  }) => {
    await stubGateway(page);
    await page.goto(`/projects/${PROJECT_ID}/workspace`);

    // ── the 3-pane shell composes ─────────────────────────────────────────────.
    await expect(page.getByTestId('workspace-shell')).toBeVisible();
    await expect(page.getByTestId('workspace-left')).toBeVisible();
    await expect(page.getByTestId('workspace-center')).toBeVisible();

    // ── TOP BAR — git info + project settings ─────────────────────────────────.
    await expect(page.getByTestId('project-name')).toHaveText('Aurora Ledger');
    await expect(page.getByTestId('project-branch')).toContainText('init/seed');
    const repoLink = page.getByTestId('project-repo-link');
    await expect(repoLink).toHaveAttribute('href', 'https://github.com/eden-demo/aurora-ledger');
    await expect(page.getByTestId('project-status')).toHaveText('building');
    await expect(page.getByTestId('project-stack').first()).toHaveText('go');
    await expect(page.getByTestId('project-supervisor')).toContainText(SUPERVISOR_ID);

    // ── LEFT — the supervisor conversation renders the streamed taxonomy (real SSE parser) ──.
    await expect(page.getByTestId('supervisor-session-id')).toHaveText(SUPERVISOR_ID);
    await expect(page.getByTestId('assistant-text')).toContainText(
      'Scaffolding the ledger service',
      {
        timeout: 15_000,
      },
    );
    const toolCard = page.getByTestId('tool-card').first();
    await expect(toolCard).toContainText('Write');
    await expect(page.getByTestId('supervisor-terminal')).toHaveAttribute(
      'data-outcome',
      'completed',
    );

    // ── CENTER — the worktree tree lists the generated assets, the viewer renders markdown ──.
    await expect(page.getByTestId('worktree-count')).toHaveText('3');
    await expect(page.getByTestId('worktree-file').first()).toBeVisible();
    // The default selection opens the product markdown — the viewer pretty-renders it.
    await expect(page.getByTestId('viewer-path')).toHaveText('init/product/PRODUCT.md');
    await expect(page.getByTestId('viewer-markdown')).toContainText('Aurora Ledger');

    // ── select the JSON asset → the viewer switches to a pretty-rendered JSON code block ──.
    await page.getByTestId('worktree-file').filter({ hasText: 'spec.json' }).click();
    await expect(page.getByTestId('viewer-path')).toHaveText('init/product/spec.json');
    await expect(page.getByTestId('viewer-json')).toContainText('productKind');
    // The JSON is re-indented (pretty-printed) — the two-space body carries a newline + indent.
    await expect(page.getByTestId('viewer-json')).toContainText('"stack"');
  });

  test('a not-found project shows an honest fault, not a blank shell', async ({ page }) => {
    // Pathname predicate, not '**/gateway/**' — see stubGateway: the glob would also 404 the
    // app's own /src/lib/gateway/*.ts modules under `vite dev`.
    await page.route(
      (url) => url.pathname.startsWith('/gateway/'),
      async (route: Route) => {
        await route.fulfill({
          status: 404,
          json: { kind: 'not-found', message: 'no such project' },
        });
      },
    );
    await page.goto('/projects/does-not-exist/workspace');
    await expect(page.getByTestId('workspace-fault')).toBeVisible();
    await expect(page.getByTestId('workspace-fault')).toContainText('not-found');
  });
});
