package agentprofile_test

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/gophersys/libs/go/agentprofile"
	"github.com/gophersys/libs/go/agentprofile/agentprofiletest"
)

// goldenFile is one line of the hand-written expectation: the emitted path and the exact bytes. An
// empty content means "the presence, position and mode are golden; the bytes have their own test".
type goldenFile struct {
	path    string
	content string
}

// The GOLDEN emission for the claude-code harness. The fixture is a committed profile document; the
// expectation below is written out by hand, file by file, byte for byte, IN ORDER. Regeneration is
// MANUAL and reviewed — there is deliberately no -update flag, because a golden a test can rewrite
// for itself is a golden that cannot fail.
//
// The expectation is the CONTRACT's emitted surface (contracts/agentprofile.md §3.6):
//
//	CLAUDE.md · .claude/rules/NN-<name>.md · .claude/skills/<name>/SKILL.md · .claude/settings.json
//
// Two parts of it are NOT implemented at 436d7f7 and these assertions are RED first, in the ordinary
// TDD sense — no break-probe compensates for them, because the feature is genuinely absent:
//
//   - the NN- ordering prefix on a rule filename. The estate corpus this renderer exists to
//     reproduce is numerically prefixed (00-identity.md … 24-typescript-pipeline.md) and the numbers
//     carry the LOAD ORDER. The author cannot supply them: document.go runs the HNS-1 slug grammar
//     (word := [a-z][a-z0-9]*) over every fragment name, so "00-identity" is rejected as a name. The
//     prefix must therefore be GENERATED by the renderer from the COMPOSED index, which is right —
//     the order is the renderer's knowledge, not the author's.
//   - .claude/settings.json. `grep -rn settings go/agentprofile/*.go` returns nothing.

// goldenNotice is the provenance line the golden expects on every emitted markdown document,
// spelled out as a literal rather than by calling the library — a golden that asked the code under
// test what it should look like would agree with any change the code made.
const goldenNotice = "<!-- generated by agentprofile (schemaVersion 1, role reviewer, harness claude-code, overlay eden)." +
	" Do not edit: edit the profile document and re-render. -->\n\n"

// goldenRoot is the cell's own emission subtree. Every path below hangs off it, so two roles
// rendering for the same harness can never collide on a native filename such as CLAUDE.md.
const goldenRoot = "profiles/reviewer/claude-code"

// goldenPrefixWidth is the zero-padded width of the NN- ordering prefix on an emitted rule filename.
// TWO, for one reason that is not aesthetic: the width must be FIXED, or the filenames stop
// describing the order they exist to encode — with a variable width "10-y.md" sorts BEFORE "9-x.md",
// so the tenth rule would read as the second. Two digits is the width the estate corpus already uses
// (00 through 24), which is the corpus §3.1 names as the requirements case.
const goldenPrefixWidth = 2

// TestGolden_ClaudeEmissionIsTheContractSurface renders the committed fixture for the claude cell
// with the eden overlay applied and asserts the WHOLE FileSet: every path, every content byte, every
// mode, and the order they arrive in. The order is load-bearing on its own — ".claude/..." sorts
// BEFORE "CLAUDE.md" ('.' < 'C'), and "rules" < "settings.json" < "skills" — so an emission that
// merely contained the right files in the wrong sequence would produce a different Digest and a
// different profileRef.
func TestGolden_ClaudeEmissionIsTheContractSurface(t *testing.T) {
	t.Parallel()
	files := renderGoldenFixture(t)

	want := []goldenFile{
		// The rules carry the generated NN- prefix in COMPOSED order, which is name order:
		// conservation (overlay) < fail-loudly (defaults) < naming (role wins over defaults).
		{goldenRoot + "/.claude/rules/00-conservation.md", goldenNotice + "Every dispatcher carries a conservation record."},
		{goldenRoot + "/.claude/rules/01-fail-loudly.md", goldenNotice + "A missing tool is a failure, never a skip."},
		{goldenRoot + "/.claude/rules/02-naming.md", goldenNotice + "The reviewer spells every name in full."},
		// settings.json's KEYS are the implementer's call; its presence, position and determinism are
		// not. Its content is asserted by TestGolden_ClaudeSettingsAreDeterministicAndDerived.
		{goldenRoot + "/.claude/settings.json", ""},
		{goldenRoot + "/.claude/skills/deep-research/SKILL.md", goldenNotice + "The eden refutation loop runs until dry."},
		{goldenRoot + "/CLAUDE.md", goldenNotice + "Refuse a change you cannot refute."},
	}

	if len(files) != len(want) {
		t.Fatalf("the claude emission carries %d file(s), want %d\n got: %s\nwant: %s",
			len(files), len(want), pathsOf(files), wantPathsOf(want))
	}
	for i := range want {
		if files[i].Path != want[i].path {
			t.Errorf("file %d Path = %q, want %q", i, files[i].Path, want[i].path)
			continue
		}
		if files[i].Mode != 0o644 {
			t.Errorf("file %d (%s) Mode = %v, want 0644 — instrumentation is data an agent reads, never a program it runs",
				i, want[i].path, files[i].Mode)
		}
		if want[i].content == "" {
			continue
		}
		if string(files[i].Content) != want[i].content {
			t.Errorf("file %d (%s) content:\n got: %q\nwant: %q", i, want[i].path, files[i].Content, want[i].content)
		}
	}
}

// TestGolden_ClaudeRulePrefixWidthIsFixed asserts the ordering prefix stays a FIXED width past nine
// rules. This is the assertion a variable-width implementation fails: with 12 composed rules, the
// tenth must be "09-", the eleventh "10-", and the emitted paths must still arrive in composed
// order — because the path sort is lexicographic and "10-" sorts before "9-".
func TestGolden_ClaudeRulePrefixWidthIsFixed(t *testing.T) {
	t.Parallel()
	const ruleCount = 12
	names := make([]string, 0, ruleCount)
	rules := make([]string, 0, ruleCount)
	for i := range ruleCount {
		// Names are drawn so their SORTED order is their declaration order, and so no name is a
		// prefix of another: rule-a, rule-b, ... rule-l.
		name := "rule-" + string(rune('a'+i))
		names = append(names, name)
		rules = append(rules, `{"name":"`+name+`","body":"body of `+name+`"}`)
	}
	document := []byte(`{"schemaVersion":1,"defaults":{"instruction":"i","rules":[` +
		strings.Join(rules, ",") + `]},"roles":{"reviewer":{"harnesses":["claude-code"]}}}`)

	files := renderDocument(t, document, "")
	missing := make([]string, 0, ruleCount)
	for i, name := range names {
		want := goldenRoot + "/.claude/rules/" + zeroPad(i, goldenPrefixWidth) + "-" + name + ".md"
		if !containsPath(files, want) {
			missing = append(missing, want)
		}
	}
	if len(missing) != 0 {
		t.Fatalf("%d of %d composed rules carry no fixed-width NN- ordering prefix; missing:\n  %s\nemitted: %s",
			len(missing), ruleCount, strings.Join(missing, "\n  "), pathsOf(files))
	}
}

// TestGolden_ClaudeSettingsAreDeterministicAndDerived asserts the three properties of
// .claude/settings.json that a caller depends on and that a naive implementation gets wrong: it
// EXISTS, its bytes are byte-identical across two independently constructed Compilers, and it is a
// FUNCTION of the document rather than a constant blob. It is the one emitted file that is a JSON
// object, so Go map iteration order is a live hazard — the key-order assertion is what catches a
// nested value built from a map, which json.Marshal's own top-level key sorting would otherwise hide.
func TestGolden_ClaudeSettingsAreDeterministicAndDerived(t *testing.T) {
	t.Parallel()
	settingsPath := goldenRoot + "/.claude/settings.json"

	first := contentAt(t, renderGoldenFixture(t), settingsPath)
	second := contentAt(t, renderGoldenFixture(t), settingsPath)
	if string(first) != string(second) {
		t.Errorf("settings.json is not byte-stable across two Compilers:\n got: %q\nwant: %q", second, first)
	}

	var decoded map[string]json.RawMessage
	if err := json.Unmarshal(first, &decoded); err != nil {
		t.Fatalf("settings.json is not a JSON object: %v (bytes: %q)", err, first)
	}
	if len(decoded) == 0 {
		t.Error("settings.json decoded to an empty object; an empty settings file is a deterministic nothing, which is the false green this library exists to prevent")
	}
	assertJSONKeysAscend(t, first)

	// A settings file that ignored the document would be identical for a different role. It must not
	// be: the emission addresses a CELL, and its settings are that cell's.
	other := renderDocument(t, mustReadFixture(t, "reviewer-profile.json"), "")
	otherSettings := contentAt(t, other, settingsPath)
	if string(otherSettings) == string(first) {
		t.Errorf("settings.json is identical with and without the eden overlay applied (%q); it must be derived from the document, not a constant", first)
	}
}

// renderGoldenFixture renders the committed fixture for the claude cell with the eden overlay.
func renderGoldenFixture(t *testing.T) agentprofile.FileSet {
	t.Helper()
	return renderDocument(t, mustReadFixture(t, "reviewer-profile.json"), "eden")
}

// renderDocument builds a Compiler over document with the given overlay selector and renders the
// reviewer/claude-code cell through the REAL ClaudeRenderer.
func renderDocument(t *testing.T, document []byte, repository string) agentprofile.FileSet {
	t.Helper()
	compiler, err := agentprofile.New(
		agentprofile.Config{Document: document, Repository: repository},
		agentprofile.Deps{
			Renderers: []agentprofile.Renderer{agentprofile.ClaudeRenderer{}},
			Tree:      agentprofiletest.NewTree(),
		},
	)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	files, err := compiler.Render(context.Background(), agentprofile.Target{
		Role: "reviewer", Harness: agentprofile.HarnessClaudeCode,
	})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	return files
}

// mustReadFixture reads a committed test fixture by name.
func mustReadFixture(t *testing.T, name string) []byte {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", name)) //nolint:gosec // a fixed test fixture path
	if err != nil {
		t.Fatalf("read fixture %s: %v", name, err)
	}
	return raw
}

// contentAt returns the emitted bytes at path, failing the test when the emission has no such file.
func contentAt(t *testing.T, files agentprofile.FileSet, path string) []byte {
	t.Helper()
	for i := range files {
		if files[i].Path == path {
			return files[i].Content
		}
	}
	t.Fatalf("the emission carries no file at %q\nemitted: %s", path, pathsOf(files))
	return nil
}

// containsPath reports whether the emission carries a file at path.
func containsPath(files agentprofile.FileSet, path string) bool {
	for i := range files {
		if files[i].Path == path {
			return true
		}
	}
	return false
}

// assertJSONKeysAscend fails t unless the object's keys appear in the RAW BYTES in ascending order.
// Decoding into a map and sorting would prove nothing — the emitted byte order is the property, and
// it is what a value assembled from a Go map would violate.
func assertJSONKeysAscend(t *testing.T, raw []byte) {
	t.Helper()
	decoder := json.NewDecoder(strings.NewReader(string(raw)))
	if _, err := decoder.Token(); err != nil { // consume '{'
		t.Fatalf("settings.json: reading the opening token: %v", err)
	}
	previous := ""
	for decoder.More() {
		token, err := decoder.Token()
		if err != nil {
			t.Fatalf("settings.json: reading a key: %v", err)
		}
		key, isString := token.(string)
		if !isString {
			t.Fatalf("settings.json: expected a string key, got %T", token)
		}
		if previous != "" && key < previous {
			t.Errorf("settings.json keys are not in ascending byte order: %q follows %q — an emission built from a Go map is not deterministic", key, previous)
		}
		previous = key
		var skipped json.RawMessage
		if err := decoder.Decode(&skipped); err != nil {
			t.Fatalf("settings.json: skipping the value of %q: %v", key, err)
		}
	}
}

// pathsOf renders an emission's paths for a failure message.
func pathsOf(files agentprofile.FileSet) string {
	paths := make([]string, 0, len(files))
	for i := range files {
		paths = append(paths, files[i].Path)
	}
	return "\n  " + strings.Join(paths, "\n  ")
}

// wantPathsOf renders the golden's paths for a failure message.
func wantPathsOf(want []goldenFile) string {
	paths := make([]string, 0, len(want))
	for i := range want {
		paths = append(paths, want[i].path)
	}
	return "\n  " + strings.Join(paths, "\n  ")
}

// zeroPad renders n as a fixed-width, zero-padded decimal.
func zeroPad(n, width int) string {
	rendered := strconv.Itoa(n)
	for len(rendered) < width {
		rendered = "0" + rendered
	}
	return rendered
}
