package agentprofile

import (
	"context"
	"io/fs"
	"strconv"
)

// profileRoot is the repository-relative directory the whole matrix renders under. Every cell owns
// the subtree <profileRoot>/<role>/<harness>, so two roles rendering for the same harness cannot
// collide on a native filename such as CLAUDE.md, and one cell can be committed, diffed and
// addressed by digest on its own.
const profileRoot = "profiles"

// fileMode is the permission bits every emitted file carries. Instrumentation is data an agent
// reads, never a program it runs, so nothing here is executable.
const fileMode fs.FileMode = 0o644

// ClaudeRenderer emits the claude-code harness's native instrumentation layout: CLAUDE.md for the
// role's instruction, .claude/rules/<name>.md per composed rule, and .claude/skills/<name>/SKILL.md
// per composed skill, all under this cell's own root. It is stateless, so the zero value is ready to
// wire and it is safe for concurrent use.
type ClaudeRenderer struct{}

// Harness reports the adapter key this renderer emits for.
func (ClaudeRenderer) Harness() Harness { return HarnessClaudeCode }

// Render emits the claude-code file set for one resolved cell, in the order rules and skills were
// already sorted into. It cannot fail: every input invariant — slug names, non-empty bodies, a
// declared cell — is established before a Resolved exists, so the error in the signature belongs to
// the port, not to a path this renderer takes.
//
//nolint:gocritic // hugeParam: Resolved is by value BY DESIGN — the copy is what makes the projection immutable to the renderer, which a pointer would surrender.
func (ClaudeRenderer) Render(_ context.Context, resolved Resolved) (FileSet, error) {
	root := profileRoot + "/" + resolved.Target.String()
	notice := generatedNotice(&resolved)
	files := make(FileSet, 0, 1+len(resolved.Rules)+len(resolved.Skills))
	files = append(files, File{
		Path:    root + "/CLAUDE.md",
		Content: []byte(notice + resolved.Instruction),
		Mode:    fileMode,
	})
	for _, rule := range resolved.Rules {
		files = append(files, File{
			Path:    root + "/.claude/rules/" + rule.Name + ".md",
			Content: []byte(notice + rule.Body),
			Mode:    fileMode,
		})
	}
	for _, skill := range resolved.Skills {
		files = append(files, File{
			Path:    root + "/.claude/skills/" + skill.Name + "/SKILL.md",
			Content: []byte(notice + skill.Body),
			Mode:    fileMode,
		})
	}
	return files, nil
}

// OMPRenderer is the declared-but-unbuilt renderer for the omp harness. It exists so the matrix can
// name the harness and so wiring it is a compile-time fact; every Render fails loudly with the
// harness in the error. It NEVER emits an empty FileSet, because an empty emission would let the
// drift check pass over a profile that was never written — a green gate proving nothing.
type OMPRenderer struct{}

// Harness reports the adapter key this renderer emits for.
func (OMPRenderer) Harness() Harness { return HarnessOMP }

// Render fails with a NotImplementedError naming the omp harness. Replacing this body with a real
// emission is the whole change; nothing else in the library moves.
//
//nolint:gocritic // hugeParam: the by-value Resolved is the frozen port signature, not this renderer's choice; it is unread here and stays by value so every binding matches.
func (OMPRenderer) Render(_ context.Context, _ Resolved) (FileSet, error) {
	return nil, notImplemented(HarnessOMP)
}

// CodexRenderer is the declared-but-unbuilt renderer for the codex harness. It behaves exactly as
// OMPRenderer does: named in the matrix, loud on Render, never silently empty.
type CodexRenderer struct{}

// Harness reports the adapter key this renderer emits for.
func (CodexRenderer) Harness() Harness { return HarnessCodex }

// Render fails with a NotImplementedError naming the codex harness. Replacing this body with a real
// emission is the whole change; nothing else in the library moves.
//
//nolint:gocritic // hugeParam: the by-value Resolved is the frozen port signature, not this renderer's choice; it is unread here and stays by value so every binding matches.
func (CodexRenderer) Render(_ context.Context, _ Resolved) (FileSet, error) {
	return nil, notImplemented(HarnessCodex)
}

// generatedNotice is the provenance line every emitted document opens with. It names the schema
// version, the cell and the overlay that produced the file, so a human who finds the file in a
// repository learns where it came from and is told not to edit it — the one instruction that keeps
// the drift check meaningful. It is derived only from Resolved, so it stays deterministic.
func generatedNotice(resolved *Resolved) string {
	return "<!-- generated by agentprofile (schemaVersion " + strconv.Itoa(resolved.SchemaVersion) +
		", role " + string(resolved.Target.Role) +
		", harness " + string(resolved.Target.Harness) +
		", overlay " + overlayLabel(resolved.Repository) +
		"). Do not edit: edit the profile document and re-render. -->\n\n"
}

// overlayLabel renders the applied overlay for the provenance line, naming the base matrix
// explicitly rather than leaving a reader to interpret an empty field.
func overlayLabel(repository string) string {
	if repository == "" {
		return "none"
	}
	return repository
}
