from protos.mtib_runner.mtib_runner_pb2 import (  # Types for C# client to Orange Pi gRPC server; Health Check; Gpio; Adc; Power; Power Monitor; Sensors; Firmware Files; J-Link; Uart
    AccelReadMaxRequest, AccelReadMaxResponse, AccelReadRequest,
    AccelReadResponse, AdcReadAllRequest, AdcReadAllResponse, AdcReadRequest,
    AdcReadResponse, AltimeterReadRequest, AltimeterReadResponse,
    DeleteFwFileRequest, DeleteFwFileResponse, DeviceType,
    DutCurrentReadRequest, DutCurrentReadResponse, DutPowerEnableRequest,
    DutPowerEnableResponse, DutPowerReadRequest, DutPowerReadResponse,
    DutVoltageReadRequest, DutVoltageReadResponse, DutVoltageSetRequest,
    DutVoltageSetResponse, EepromReadRequest, EepromReadResponse,
    EepromWriteRequest, EepromWriteResponse, FlashHexFileRequest,
    FlashHexFileResponse, FwFileInfo, GetRunnerInfoRequest,
    GetRunnerInfoResponse, GpioConfigRequest, GpioConfigResponse,
    GpioReadRequest, GpioReadResponse, GpioWriteRequest, GpioWriteResponse,
    HealthCheckResponse, ListFwFilesRequest, ListFwFilesResponse, RunnerInfo,
    UartStreamRequest, UartStreamResponse, UploadFwFileRequest,
    UploadFwFileResponse)
from protos.mtib_runner_zephyr.mtib_runner_zephyr_pb2 import (  # Types for Orange Pi to STM32; Gpio; Adc; Power; Power Monitor; Altimeter; Accelerometer; Memory; Uart
    AdcReadAllChannelsRequest, AdcReadAllChannelsResponse,
    AdcReadChannelRequest, AdcReadChannelResponse, Bmp390ReadValuesRequest,
    Bmp390ReadValuesResponse, DutEnableChargerRequest,
    DutEnableChargerResponse, DutEnablePowerRequest, DutEnablePowerResponse,
    DutSetOutputVoltageRequest, DutSetOutputVoltageResponse,
    EepromReadFromMemRequest, EepromReadFromMemResponse,
    EepromWriteToMemRequest, EepromWriteToMemResponse, GpioConfigurePinRequest,
    GpioConfigurePinResponse, GpioDirection, GpioReadPinRequest,
    GpioReadPinResponse, GpioSetPinRequest, GpioSetPinResponse, GpioValue,
    Ina219ReadCurrentRequest, Ina219ReadCurrentResponse,
    Ina219ReadPowerRequest, Ina219ReadPowerResponse, Ina219ReadVoltageRequest,
    Ina219ReadVoltageResponse, Lis2de12ReadMaxForceRequest,
    Lis2de12ReadMaxForceResponse, Lis2de12ReadValuesRequest,
    Lis2de12ReadValuesResponse, UartDeviceType, UartMessageRequest,
    UartMessageResponse, UartPortStateChangeRequest,
    UartPortStateChangeResponse)
