# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import comm_coproc_mfg_pb2 as comm__coproc__mfg__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in comm_coproc_mfg_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommCoprocMfgStub(object):
    """Service for manufacturing commands
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetImeiIccids = channel.unary_unary(
                '/CommCoprocMfg/GetImeiIccids',
                request_serializer=comm__coproc__mfg__pb2.Empty.SerializeToString,
                response_deserializer=comm__coproc__mfg__pb2.GetImeiIccidsResponse.FromString,
                _registered_method=True)
        self.GetChipIds = channel.unary_unary(
                '/CommCoprocMfg/GetChipIds',
                request_serializer=comm__coproc__mfg__pb2.Empty.SerializeToString,
                response_deserializer=comm__coproc__mfg__pb2.GetChipIdsResponse.FromString,
                _registered_method=True)
        self.VerifyExternalFlash = channel.unary_unary(
                '/CommCoprocMfg/VerifyExternalFlash',
                request_serializer=comm__coproc__mfg__pb2.Empty.SerializeToString,
                response_deserializer=comm__coproc__mfg__pb2.Error.FromString,
                _registered_method=True)
        self.PersonalizeDeviceId = channel.unary_unary(
                '/CommCoprocMfg/PersonalizeDeviceId',
                request_serializer=comm__coproc__mfg__pb2.PersonalizeDeviceIdRequest.SerializeToString,
                response_deserializer=comm__coproc__mfg__pb2.Error.FromString,
                _registered_method=True)
        self.GetPublicKeys = channel.unary_unary(
                '/CommCoprocMfg/GetPublicKeys',
                request_serializer=comm__coproc__mfg__pb2.Empty.SerializeToString,
                response_deserializer=comm__coproc__mfg__pb2.GetPublicKeysResponse.FromString,
                _registered_method=True)
        self.PersonalizeIPCKeys = channel.unary_unary(
                '/CommCoprocMfg/PersonalizeIPCKeys',
                request_serializer=comm__coproc__mfg__pb2.PersonalizeIPCKeysRequest.SerializeToString,
                response_deserializer=comm__coproc__mfg__pb2.Error.FromString,
                _registered_method=True)


class CommCoprocMfgServicer(object):
    """Service for manufacturing commands
    """

    def GetImeiIccids(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChipIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyExternalFlash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PersonalizeDeviceId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublicKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PersonalizeIPCKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommCoprocMfgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetImeiIccids': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImeiIccids,
                    request_deserializer=comm__coproc__mfg__pb2.Empty.FromString,
                    response_serializer=comm__coproc__mfg__pb2.GetImeiIccidsResponse.SerializeToString,
            ),
            'GetChipIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChipIds,
                    request_deserializer=comm__coproc__mfg__pb2.Empty.FromString,
                    response_serializer=comm__coproc__mfg__pb2.GetChipIdsResponse.SerializeToString,
            ),
            'VerifyExternalFlash': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyExternalFlash,
                    request_deserializer=comm__coproc__mfg__pb2.Empty.FromString,
                    response_serializer=comm__coproc__mfg__pb2.Error.SerializeToString,
            ),
            'PersonalizeDeviceId': grpc.unary_unary_rpc_method_handler(
                    servicer.PersonalizeDeviceId,
                    request_deserializer=comm__coproc__mfg__pb2.PersonalizeDeviceIdRequest.FromString,
                    response_serializer=comm__coproc__mfg__pb2.Error.SerializeToString,
            ),
            'GetPublicKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicKeys,
                    request_deserializer=comm__coproc__mfg__pb2.Empty.FromString,
                    response_serializer=comm__coproc__mfg__pb2.GetPublicKeysResponse.SerializeToString,
            ),
            'PersonalizeIPCKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.PersonalizeIPCKeys,
                    request_deserializer=comm__coproc__mfg__pb2.PersonalizeIPCKeysRequest.FromString,
                    response_serializer=comm__coproc__mfg__pb2.Error.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CommCoprocMfg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CommCoprocMfg', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CommCoprocMfg(object):
    """Service for manufacturing commands
    """

    @staticmethod
    def GetImeiIccids(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CommCoprocMfg/GetImeiIccids',
            comm__coproc__mfg__pb2.Empty.SerializeToString,
            comm__coproc__mfg__pb2.GetImeiIccidsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChipIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CommCoprocMfg/GetChipIds',
            comm__coproc__mfg__pb2.Empty.SerializeToString,
            comm__coproc__mfg__pb2.GetChipIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyExternalFlash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CommCoprocMfg/VerifyExternalFlash',
            comm__coproc__mfg__pb2.Empty.SerializeToString,
            comm__coproc__mfg__pb2.Error.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PersonalizeDeviceId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CommCoprocMfg/PersonalizeDeviceId',
            comm__coproc__mfg__pb2.PersonalizeDeviceIdRequest.SerializeToString,
            comm__coproc__mfg__pb2.Error.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPublicKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CommCoprocMfg/GetPublicKeys',
            comm__coproc__mfg__pb2.Empty.SerializeToString,
            comm__coproc__mfg__pb2.GetPublicKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PersonalizeIPCKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CommCoprocMfg/PersonalizeIPCKeys',
            comm__coproc__mfg__pb2.PersonalizeIPCKeysRequest.SerializeToString,
            comm__coproc__mfg__pb2.Error.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
