# # OS release information
# OS_RELEASE_FIELDS += "HOME_URL BUG_REPORT_URL VERSION_CODENAME"
# VERSION_CODENAME = "corekinect"
# HOME_URL = "https://corekinect.com"
# BUG_REPORT_URL = "https://corekinect.com/support"

# # Override Torizon branding
# IMAGE_NAME = "CoreKinect-${MACHINE}${IMAGE_VERSION_SUFFIX}"
# IMAGE_LINK_NAME = "CoreKinect-${MACHINE}"

# # Plymouth splash branding
# SPLASH = "plymouth"
# OSTREE_BRANDING = "corekinect"

# # Override OS release information
# IMAGE_NAME_SUFFIX = ""
# DISTRO_NAME = "CoreKinect OS"
# DISTRO_VERSION = "1.0"
# DISTRO_CODENAME = "corekinect"

# # Disable garage signing to prevent hash errors
# GARAGE_SIGN_REPO = ""
# GARAGE_TARGET_VERSION = ""
