package servicespec

import (
	"fmt"
	"strings"
)

// RenderCompose renders the platform services as a docker-compose file fragment (the
// `deploy/<plane>/local` half). It models ONLY the platform services (gateway/agent-runtime) — the
// supporting stack (NATS/Postgres/Vault) lives in plane/local/docker-compose.yaml and stands up
// out-of-band — so this output is a `compose -f stack.yaml -f platform.yaml` overlay: the platform
// services join the same network as the already-running stack.
//
// Image-tag-as-environment-contract: each service renders `<name>:local` (a locally-built/loaded
// tag), one Dockerfile per service. Secret env entries render as a `${VAR}` interpolation so the
// value is injected from the loaded .env at `up` time — never inlined into the committed file.
func RenderCompose(target RenderTarget, services []ServiceSpec) string {
	var b strings.Builder
	b.WriteString("# GENERATED by deploy/servicespec (render compose). DO NOT EDIT BY HAND.\n")
	b.WriteString("# The Eden platform services overlay (ADR-0022 #2). Compose it WITH the supporting\n")
	b.WriteString("# stack:  docker compose -f plane/local/docker-compose.yaml -f plane/local/platform.yaml up\n")
	b.WriteString("name: eden-local-platform\n\n")
	b.WriteString("services:\n")

	for i := range services {
		renderComposeService(&b, target, services[i])
	}
	return b.String()
}

func renderComposeService(b *strings.Builder, target RenderTarget, service ServiceSpec) {
	fmt.Fprintf(b, "  %s:\n", service.Name)
	fmt.Fprintf(b, "    image: %s\n", service.ImageReference(RenderTarget{Plane: PlaneLocal}))
	fmt.Fprintf(b, "    container_name: eden-%s\n", service.Name)
	if len(service.Command) > 0 {
		fmt.Fprintf(b, "    command: [%s]\n", quoteJoin(service.Command))
	}
	if hasPublishedPort(service.Ports) {
		b.WriteString("    ports:\n")
		for _, p := range service.Ports {
			if p.Host > 0 {
				fmt.Fprintf(b, "      - \"127.0.0.1:%d:%d\"  # %s\n", p.Host, p.Container, p.Name)
			}
		}
	}
	if len(service.Env) > 0 {
		b.WriteString("    environment:\n")
		for _, e := range service.Env {
			if e.FromSecret != nil {
				// Locally the secret value is injected from the loaded .env via interpolation; the
				// committed file carries only the ${VAR} reference (never the value).
				fmt.Fprintf(b, "      %s: \"${%s}\"\n", e.Name, e.Name)
				continue
			}
			if e.FromVaultField != "" {
				// The local plane IS the development stage — pin the literal development segment.
				fmt.Fprintf(b, "      %s: %q\n", e.Name, vaultStageRef("development", e.FromVaultField))
				continue
			}
			if e.FromFieldRef != "" {
				// The pod downward API has no compose analog; the entries that use it (the
				// orchestrator's lease identity/namespace) are production-only, so omit them locally.
				continue
			}
			fmt.Fprintf(b, "      %s: %q\n", e.Name, e.Value)
		}
	}
	if len(service.DependsOn) > 0 {
		b.WriteString("    depends_on:\n")
		for _, d := range service.DependsOn {
			fmt.Fprintf(b, "      - %s\n", d)
		}
	}
	if service.Liveness != nil {
		fmt.Fprintf(b, "    healthcheck:\n")
		fmt.Fprintf(b, "      test: [\"CMD\", \"wget\", \"--spider\", \"-q\", \"http://127.0.0.1:%d%s\"]\n", service.Liveness.Port, service.Liveness.Path)
		b.WriteString("      interval: 5s\n      timeout: 3s\n      retries: 12\n")
	}
	b.WriteString("\n")
}

// hasPublishedPort reports whether any port has a host mapping (so a compose `ports:` block is
// worth emitting; an unpublished probe-only port would otherwise print an empty block).
func hasPublishedPort(ports []Port) bool {
	for _, p := range ports {
		if p.Host > 0 {
			return true
		}
	}
	return false
}

// quoteJoin renders a string slice as a JSON-ish quoted, comma-joined list (for compose command:).
func quoteJoin(items []string) string {
	quoted := make([]string, len(items))
	for i, it := range items {
		quoted[i] = fmt.Sprintf("%q", it)
	}
	return strings.Join(quoted, ", ")
}
