package servicespec

import (
	"fmt"
	"strings"
)

// HelmFile is one rendered chart file (relative path under the chart root + its content).
type HelmFile struct {
	Path    string
	Content string
}

// RenderHelm renders the platform services as a Helm chart (the `deploy/<plane>/production` half):
// a Chart.yaml, a values.yaml (image registry/tag/namespace as the env contract), and one
// Deployment + Service template per service. The supporting stack is NOT in the chart — it stands
// up out-of-band (a managed NATS/Postgres/Vault, or a separately-installed dependency chart) — so a
// platform service names it via env (EDEN_NATS_URL → the in-cluster Service DNS) but the chart does
// not own it.
//
// Image-tag-as-environment-contract: templates reference `{{ .Values.registry }}/<name>:{{
// .Values.tag }}`, so a single `--set tag=<sha>` re-points every service. Secret env entries render
// as a valueFrom.secretKeyRef — the manifest carries the Secret NAME/KEY, never an inlined value
// (the operator creates the Secret out-of-band; ADR-0022 #1/#3).
func RenderHelm(target RenderTarget, services []ServiceSpec) []HelmFile {
	files := []HelmFile{
		{Path: "Chart.yaml", Content: chartYAML()},
		{Path: "values.yaml", Content: valuesYAML(target)},
		{Path: ".helmignore", Content: "# generated chart\n*.md\n"},
	}
	for i := range services {
		files = append(
			files,
			HelmFile{Path: "templates/" + services[i].Name + "-deployment.yaml", Content: deploymentTemplate(services[i])},
		)
		if len(services[i].Ports) > 0 {
			files = append(
				files,
				HelmFile{Path: "templates/" + services[i].Name + "-service.yaml", Content: serviceTemplate(services[i])},
			)
		}
	}
	return files
}

func chartYAML() string {
	return `# GENERATED by deploy/servicespec (render helm). DO NOT EDIT BY HAND.
apiVersion: v2
name: eden-platform
description: Eden Milestone-B platform services (agentgateway + agent-runtime) — ADR-0022 #2.
type: application
version: 0.1.0
appVersion: "0.1.0"
`
}

func valuesYAML(target RenderTarget) string {
	registry := target.Registry
	if registry == "" {
		registry = "ghcr.io/gophersys/eden"
	}
	tag := target.Tag
	if tag == "" {
		tag = "latest"
	}
	namespace := target.Namespace
	if namespace == "" {
		namespace = "eden"
	}
	stage := target.Stage
	if stage == "" {
		stage = "production"
	}
	return fmt.Sprintf(`# GENERATED by deploy/servicespec. The image-tag-as-environment-contract knobs.
# Override per environment:  helm install eden . --set tag=<sha> --set registry=<reg>
registry: %s
tag: %q
namespace: %s
# The deployment STAGE — the segment every vault://eden/<stage>#<field> credential reference resolves
# under. Defaults to production so a prod install never inherits the development credential path; a
# staging install overrides it with:  --set stage=staging
stage: %s
`, registry, tag, namespace, stage)
}

func deploymentTemplate(service ServiceSpec) string {
	var b strings.Builder
	b.WriteString("# GENERATED by deploy/servicespec. DO NOT EDIT BY HAND.\n")
	b.WriteString("apiVersion: apps/v1\nkind: Deployment\n")
	b.WriteString("metadata:\n")
	fmt.Fprintf(&b, "  name: %s\n", service.Name)
	b.WriteString("  namespace: {{ .Values.namespace }}\n")
	fmt.Fprintf(&b, "  labels:\n    app.kubernetes.io/name: %s\n    app.kubernetes.io/part-of: eden\n", service.Name)
	b.WriteString("spec:\n")
	// A negative count folds to 1 (defensive), but an EXPLICIT 0 is legitimate: the
	// agent-runtime spec is a per-agent TEMPLATE the orchestrator instantiates — a
	// standing replica exits immediately (EDEN_AGENT_ID is required, proven live).
	replicas := service.Replicas
	if replicas < 0 {
		replicas = 1
	}
	fmt.Fprintf(&b, "  replicas: %d\n", replicas)
	fmt.Fprintf(&b, "  selector:\n    matchLabels:\n      app.kubernetes.io/name: %s\n", service.Name)
	b.WriteString("  template:\n")
	fmt.Fprintf(&b, "    metadata:\n      labels:\n        app.kubernetes.io/name: %s\n", service.Name)
	b.WriteString("    spec:\n")
	if service.ServiceAccount != "" {
		fmt.Fprintf(&b, "      serviceAccountName: %s\n", service.ServiceAccount)
	}
	b.WriteString("      containers:\n")
	fmt.Fprintf(&b, "        - name: %s\n", service.Name)
	fmt.Fprintf(&b, "          image: \"{{ .Values.registry }}/%s:{{ .Values.tag }}\"\n", service.Image)
	if len(service.Command) > 0 {
		fmt.Fprintf(&b, "          command: [%s]\n", quoteJoin(service.Command))
	}
	renderHelmPorts(&b, service)
	renderHelmEnv(&b, service)
	renderHelmResources(&b, service)
	renderHelmProbes(&b, service)
	renderHelmTokenFileMount(&b, service)
	renderHelmTokenFileVolume(&b, service)
	return b.String()
}

// renderHelmTokenFileMount projects the Vault token-file Secret as a read-only volumeMount on the
// container (production only). The volume mounts at the DIRECTORY (no subPath): kubelet lays each
// Secret key out as a file inside it, so the token lands at <dir>/<file> — with subPath the key's
// CONTENT became the file AT the mount path itself and the app's open("<dir>/<file>") failed with
// ENOTDIR (the exact live crash on the home cluster). A directory mount also keeps receiving Secret
// updates (subPath mounts never do), so a reseed's re-minted token propagates without a pod restart.
func renderHelmTokenFileMount(b *strings.Builder, service ServiceSpec) {
	m := service.TokenFileSecret
	if m == nil {
		return
	}
	b.WriteString("          volumeMounts:\n")
	fmt.Fprintf(b, "            - name: %s\n", m.volumeName())
	fmt.Fprintf(b, "              mountPath: %s\n", m.mountDir())
	b.WriteString("              readOnly: true\n")
}

// renderHelmTokenFileVolume declares the pod volume that projects the Vault token-file Secret's key
// as a single item. The Secret is materialized out-of-band (External Secrets / an operator); the
// manifest names it, never a value (the secrets no-leak contract).
func renderHelmTokenFileVolume(b *strings.Builder, service ServiceSpec) {
	m := service.TokenFileSecret
	if m == nil {
		return
	}
	b.WriteString("      volumes:\n")
	fmt.Fprintf(b, "        - name: %s\n", m.volumeName())
	b.WriteString("          secret:\n")
	fmt.Fprintf(b, "            secretName: %s\n", m.SecretName)
	b.WriteString("            items:\n")
	fmt.Fprintf(b, "              - key: %s\n", m.Key)
	fmt.Fprintf(b, "                path: %s\n", m.mountFile())
}

func renderHelmPorts(b *strings.Builder, service ServiceSpec) {
	if len(service.Ports) == 0 {
		return
	}
	b.WriteString("          ports:\n")
	for _, p := range service.Ports {
		fmt.Fprintf(b, "            - name: %s\n              containerPort: %d\n", p.Name, p.Container)
	}
}

func renderHelmEnv(b *strings.Builder, service ServiceSpec) {
	if len(service.Env) == 0 {
		return
	}
	b.WriteString("          env:\n")
	for _, e := range service.Env {
		if e.FromSecret != nil {
			fmt.Fprintf(b, "            - name: %s\n", e.Name)
			fmt.Fprintf(b, "              valueFrom:\n                secretKeyRef:\n                  name: %s\n                  key: %s\n",
				e.FromSecret.SecretName, e.FromSecret.Key)
			continue
		}
		if e.FromVaultField != "" {
			// Stage-scoped: the segment is the Helm `{{ .Values.stage }}` placeholder (defaulted to
			// production in values.yaml), so the production chart never carries the development path.
			fmt.Fprintf(b, "            - name: %s\n              value: %q\n", e.Name, vaultStageRef(vaultHelmStagePlaceholder, e.FromVaultField))
			continue
		}
		if e.FromFieldRef != "" {
			// The pod downward API: a per-replica value the render cannot know (the lease identity is
			// the pod name; the lease namespace is the pod's namespace).
			fmt.Fprintf(b, "            - name: %s\n", e.Name)
			fmt.Fprintf(b, "              valueFrom:\n                fieldRef:\n                  fieldPath: %s\n", e.FromFieldRef)
			continue
		}
		fmt.Fprintf(b, "            - name: %s\n              value: %q\n", e.Name, e.Value)
	}
}

func renderHelmResources(b *strings.Builder, service ServiceSpec) {
	r := service.Resources
	if r.CPUMillis == 0 && r.MemoryMiB == 0 {
		return
	}
	b.WriteString("          resources:\n")
	b.WriteString("            requests:\n")
	if r.CPUMillis > 0 {
		fmt.Fprintf(b, "              cpu: %dm\n", r.CPUMillis)
	}
	if r.MemoryMiB > 0 {
		fmt.Fprintf(b, "              memory: %dMi\n", r.MemoryMiB)
	}
	b.WriteString("            limits:\n")
	if r.CPUMillis > 0 {
		fmt.Fprintf(b, "              cpu: %dm\n", r.CPUMillis)
	}
	if r.MemoryMiB > 0 {
		fmt.Fprintf(b, "              memory: %dMi\n", r.MemoryMiB)
	}
	if r.EphemeralMiB > 0 {
		fmt.Fprintf(b, "              ephemeral-storage: %dMi\n", r.EphemeralMiB)
	}
}

func renderHelmProbes(b *strings.Builder, service ServiceSpec) {
	if service.Liveness != nil {
		fmt.Fprintf(b, "          livenessProbe:\n            httpGet:\n              path: %s\n              port: %d\n            initialDelaySeconds: 5\n            periodSeconds: 10\n",
			service.Liveness.Path, service.Liveness.Port)
	}
	if service.Readiness != nil {
		fmt.Fprintf(b, "          readinessProbe:\n            httpGet:\n              path: %s\n              port: %d\n            initialDelaySeconds: 3\n            periodSeconds: 5\n",
			service.Readiness.Path, service.Readiness.Port)
	}
}

func serviceTemplate(service ServiceSpec) string {
	var b strings.Builder
	b.WriteString("# GENERATED by deploy/servicespec. DO NOT EDIT BY HAND.\n")
	b.WriteString("apiVersion: v1\nkind: Service\n")
	fmt.Fprintf(&b, "metadata:\n  name: %s\n  namespace: {{ .Values.namespace }}\n", service.Name)
	fmt.Fprintf(&b, "  labels:\n    app.kubernetes.io/name: %s\n    app.kubernetes.io/part-of: eden\n", service.Name)
	b.WriteString("spec:\n")
	fmt.Fprintf(&b, "  selector:\n    app.kubernetes.io/name: %s\n", service.Name)
	b.WriteString("  ports:\n")
	for _, p := range service.Ports {
		fmt.Fprintf(&b, "    - name: %s\n      port: %d\n      targetPort: %d\n", p.Name, p.Container, p.Container)
	}
	return b.String()
}
