[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = src ../../../libs/python ../../../libs/protocols ../../../libs
addopts = -v --tb=short

filterwarnings =
    ignore::DeprecationWarning:grpc.*
    ignore::DeprecationWarning:google.*
