package workflow_test

import (
	"strings"
	"testing"

	"github.com/gophersys/cictl/internal/contract"
	"github.com/gophersys/cictl/internal/workflow"
)

// reviewSHA is a syntactically valid commit used throughout these tests. It is
// deliberately not a real cictl commit: a test that pinned a real one would go
// red the day that commit was rewritten, for a reason that has nothing to do
// with the generator.
const reviewSHA = "0123456789abcdef0123456789abcdef01234567"

func reviewContract(tier contract.ReviewTier) *contract.Contract {
	c := sampleContract()
	c.Review = contract.Review{
		Enabled:        true,
		Harness:        contract.ReviewHarnessClaude,
		Ref:            reviewSHA,
		Release:        "v0.6.0",
		Tier:           tier,
		RunsOn:         "arc-review",
		TimeoutMinutes: 30,
		StreamStore:    contract.ReviewStreamMinio,
		StreamEndpoint: "https://minio.example.invalid",
		StreamBucket:   "review-streams",
	}
	return c
}

func TestRender_TheCallerSelectsCodex(t *testing.T) {
	t.Parallel()
	c := reviewContract(contract.ReviewTierPlatform)
	c.Review.Harness = contract.ReviewHarnessCodex
	files, err := workflow.Render(c)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	body := contentOf(t, files, workflow.ReviewFileName)
	if !strings.Contains(body, "harness: codex") {
		t.Fatalf("generated caller did not select Codex:\n%s", body)
	}
	if !strings.Contains(body, "model: default") || strings.Contains(body, "model: opus") {
		t.Fatalf("generated Codex caller carried a Claude model:\n%s", body)
	}
}

// TestRender_NoReviewBlockRendersThreeFiles is the compatibility floor. Every
// repository that adopted the contract before the reviewer existed has no
// `review:` block, and its render must be exactly what it always was — a fourth
// file appearing under those repositories would fail their drift gate on a
// change they never made.
func TestRender_NoReviewBlockRendersThreeFiles(t *testing.T) {
	t.Parallel()
	files, err := workflow.Render(sampleContract())
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if len(files) != 3 {
		t.Fatalf("a contract with no review block must render 3 files, got %d", len(files))
	}
	for _, f := range files {
		if f.Name == workflow.ReviewFileName {
			t.Fatalf("a contract with no review block rendered %s", workflow.ReviewFileName)
		}
	}
}

// TestRender_ReviewEnabledAddsTheCaller asserts the fourth file appears, and only
// then.
func TestRender_ReviewEnabledAddsTheCaller(t *testing.T) {
	t.Parallel()
	files, err := workflow.Render(reviewContract(contract.ReviewTierModule))
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if len(files) != 4 {
		t.Fatalf("a review-enabled contract must render 4 files, got %d", len(files))
	}
	body := contentOf(t, files, workflow.ReviewFileName)
	if !strings.HasPrefix(body, "# GENERATED by cictl") {
		t.Errorf("the caller carries no generated-file banner:\n%s", body)
	}
}

// TestRender_TheCallerCarriesTheTierPreset is the D2 assertion. The contract
// declares a TIER, never a budget; the preset is derived in one place, so
// changing what `platform` costs is one edit and a regeneration rather than an
// edit of four contracts. A caller that matched the render therefore cannot
// carry the wrong spend — which is also what makes "tier correct" checkable by
// the org audit without a rule of its own.
func TestRender_TheCallerCarriesTheTierPreset(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		tier   contract.ReviewTier
		model  string
		budget string
		rounds string
	}{
		{contract.ReviewTierPlatform, "opus", `"25"`, `"4"`},
		{contract.ReviewTierModule, "opus", `"25"`, `"4"`},
		{contract.ReviewTierResearch, "sonnet", `"10"`, `"2"`},
		{contract.ReviewTierTooling, "sonnet", `"10"`, `"2"`},
	} {
		t.Run(string(tc.tier), func(t *testing.T) {
			t.Parallel()
			files, err := workflow.Render(reviewContract(tc.tier))
			if err != nil {
				t.Fatalf("Render: %v", err)
			}
			body := contentOf(t, files, workflow.ReviewFileName)
			for _, want := range []string{
				"harness: claude",
				"model: " + tc.model,
				"budget-usd: " + tc.budget,
				"max-rounds: " + tc.rounds,
			} {
				if !strings.Contains(body, want) {
					t.Errorf("tier %q caller is missing %q:\n%s", tc.tier, want, body)
				}
			}
		})
	}
}

// TestRender_ReviewRejectsAnUnknownTier proves the generator refuses rather than
// defaulting. A default here would pick somebody's budget for them, silently.
func TestRender_ReviewRejectsAnUnknownTier(t *testing.T) {
	t.Parallel()
	c := reviewContract("archive")
	if _, err := workflow.Render(c); err == nil {
		t.Fatal("Render accepted a review tier with no spend preset; it must refuse rather than choose a budget")
	}
}

// TestRender_TheCallerIsPinnedAndSelfHosted covers the two properties that make
// a caller safe: every action is a 40-hex commit (a tag is a pointer its owner
// can move) and the job runs on an arc-* pool (a hosted job against a $0 budget
// never starts).
func TestRender_TheCallerIsPinnedAndSelfHosted(t *testing.T) {
	t.Parallel()
	files, err := workflow.Render(reviewContract(contract.ReviewTierPlatform))
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	body := contentOf(t, files, workflow.ReviewFileName)
	for _, want := range []string{
		"uses: " + workflow.CheckoutPin,
		"uses: gophersys/cictl/review@" + reviewSHA + " # v0.6.0",
		"runs-on: arc-review",
		"timeout-minutes: 30",
		"pull-requests: write",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("the caller is missing %q:\n%s", want, body)
		}
	}
	// No caller passes a credential: arc-review supplies it as pool environment,
	// so the token has exactly one home.
	if strings.Contains(body, "secrets.") {
		t.Errorf("the caller reads a repository secret; the pool supplies the credential:\n%s", body)
	}
}

// TestRender_StreamNoneOmitsTheEndpoint proves the opt-out carries no dead
// configuration. Settings for a store the caller does not use read as intent.
func TestRender_StreamNoneOmitsTheEndpoint(t *testing.T) {
	t.Parallel()
	c := reviewContract(contract.ReviewTierTooling)
	c.Review.StreamStore = contract.ReviewStreamNone
	c.Review.StreamEndpoint = ""
	c.Review.StreamBucket = ""
	files, err := workflow.Render(c)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	body := contentOf(t, files, workflow.ReviewFileName)
	if !strings.Contains(body, "stream-store: none") {
		t.Errorf("the opt-out is not visible in the caller:\n%s", body)
	}
	for _, unwanted := range []string{"stream-endpoint:", "stream-bucket:"} {
		if strings.Contains(body, unwanted) {
			t.Errorf("the caller carries %q while archiving nothing:\n%s", unwanted, body)
		}
	}
}

// TestRender_ReviewIsDeterministic is the property drift rests on: the same
// contract renders byte-identical bytes, so a difference on disk is a hand edit
// and never a re-render.
func TestRender_ReviewIsDeterministic(t *testing.T) {
	t.Parallel()
	c := reviewContract(contract.ReviewTierModule)
	a, err := workflow.Render(c)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	b, err := workflow.Render(c)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if contentOf(t, a, workflow.ReviewFileName) != contentOf(t, b, workflow.ReviewFileName) {
		t.Fatal("two renders of one contract produced different callers; drift could not tell a hand edit from a re-render")
	}
}
