// Package workflow renders provider CI workflows deterministically from a
// contract. The contract is the source; the .github/workflows/*.yml and the
// .ci/providers/github/*.yml are GENERATED — never hand-edited — and the drift
// verb re-renders in memory and fails on any divergence (the CI-on-CI gate).
//
// Determinism is load-bearing: the same contract must render byte-identical YAML
// every time, so the renderer iterates in a fixed order and never touches a map's
// undefined iteration order or a clock. The YAML is emitted by an explicit
// string builder (not a struct marshaller) so the on-disk shape is fully pinned
// and reviewable, matching the hand-written reference workflows' style.
package workflow

import (
	"errors"
	"fmt"
	"strings"

	"github.com/gophersys/eden/tools/cictl/internal/contract"
)

// ErrNoGithubProvider is returned by Render when the contract does not declare
// the github provider, so there is nothing to render.
var ErrNoGithubProvider = errors.New("contract does not declare the github provider; nothing to render")

// File is one rendered workflow: its base name (e.g. "on-pr.yml") and content.
type File struct {
	Name    string
	Content []byte
}

// header is the generated-file banner stamped on every rendered workflow so a
// human who opens it knows it is generated and where the source lives.
const header = "# GENERATED by cictl from .ci/ci.contract.yaml — DO NOT EDIT.\n" +
	"# Re-render with `cictl generate`; the `cictl drift` gate fails on any hand-edit.\n"

// Render returns the three provider workflow files for the github provider,
// derived from the contract. The order is stable: on-pr, on-push, nightly.
func Render(c *contract.Contract) ([]File, error) {
	if !hasProvider(c, contract.ProviderGithub) {
		return nil, ErrNoGithubProvider
	}
	return []File{
		{Name: "on-pr.yml", Content: []byte(renderOnPR(c))},
		{Name: "on-push.yml", Content: []byte(renderOnPush(c))},
		{Name: "nightly.yml", Content: []byte(renderNightly(c))},
	}, nil
}

func hasProvider(c *contract.Contract, p contract.Provider) bool {
	for _, x := range c.Providers {
		if x == p {
			return true
		}
	}
	return false
}

// renderOnPR builds the pull-request workflow: the pr tier then the merge tier as
// two jobs (merge needs pr), on pull_request into the default branch.
func renderOnPR(c *contract.Contract) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("name: on-pr\n\n")
	b.WriteString("on:\n  pull_request:\n    branches: [main]\n\n")
	b.WriteString("concurrency:\n  group: on-pr-${{ github.ref }}\n  cancel-in-progress: true\n\n")
	b.WriteString("permissions:\n  contents: read\n  packages: read\n\n")
	b.WriteString("jobs:\n")
	writeJob(&b, &jobSpec{
		id:      "pr",
		name:    fmt.Sprintf("pr tier (%s)", strings.Join(c.Tiers.Pr.Verbs, ", ")),
		image:   string(c.Image),
		tier:    c.Tiers.Pr,
		nxBase:  "origin/${{ github.base_ref }}",
		needs:   "",
		comment: "The fast lane: the pr-tier verbs over the affected projects. No real substrate.",
	})
	b.WriteString("\n")
	writeJob(&b, &jobSpec{
		id:      "merge",
		name:    fmt.Sprintf("merge tier (%s)", strings.Join(c.Tiers.Merge.Verbs, ", ")),
		image:   string(c.Image),
		tier:    c.Tiers.Merge,
		nxBase:  "origin/${{ github.base_ref }}",
		needs:   "pr",
		comment: "The careful-orchestration lane: the merge-tier verbs on the real substrate before merge.",
	})
	return b.String()
}

// renderOnPush builds the push workflow: the pr tier on push to the default
// branch (the cheap post-merge re-check).
func renderOnPush(c *contract.Contract) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("name: on-push\n\n")
	b.WriteString("on:\n  push:\n    branches: [main]\n  workflow_dispatch:\n\n")
	b.WriteString("concurrency:\n  group: on-push-${{ github.ref }}\n  cancel-in-progress: true\n\n")
	b.WriteString("permissions:\n  contents: read\n  packages: read\n\n")
	b.WriteString("jobs:\n")
	writeJob(&b, &jobSpec{
		id:      "pr",
		name:    fmt.Sprintf("pr tier (%s)", strings.Join(c.Tiers.Pr.Verbs, ", ")),
		image:   string(c.Image),
		tier:    c.Tiers.Pr,
		nxBase:  "origin/main~1",
		needs:   "",
		comment: "Post-merge re-check: the pr-tier verbs over what the push changed.",
	})
	return b.String()
}

// renderNightly builds the scheduled workflow: the nightly tier on its cron
// schedule (plus a manual workflow_dispatch).
func renderNightly(c *contract.Contract) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("name: nightly\n\n")
	b.WriteString("on:\n")
	fmt.Fprintf(&b, "  schedule:\n    - cron: %q\n", c.Tiers.Nightly.Schedule)
	b.WriteString("  workflow_dispatch:\n\n")
	b.WriteString("concurrency:\n  group: nightly-${{ github.ref }}\n  cancel-in-progress: false\n\n")
	b.WriteString("permissions:\n  contents: read\n  packages: read\n\n")
	b.WriteString("jobs:\n")
	writeJob(&b, &jobSpec{
		id:      "nightly",
		name:    fmt.Sprintf("nightly tier (%s)", strings.Join(c.Tiers.Nightly.Verbs, ", ")),
		image:   string(c.Image),
		tier:    c.Tiers.Nightly,
		nxBase:  "origin/main~1",
		needs:   "",
		comment: "The exhaustive lane: every nightly-tier verb on the full substrate, on a schedule.",
	})
	return b.String()
}

// jobSpec is the resolved input to writeJob — everything one job needs, already
// derived from the contract so writeJob is a pure formatter.
type jobSpec struct {
	id      string
	name    string
	image   string
	tier    contract.Tier
	nxBase  string
	needs   string
	comment string
}

// writeJob emits one GitHub Actions job block. A tier with a non-empty substrate
// gets a privileged container with the docker socket mounted and a dockerd-start
// step, mirroring the hand-written reference substrate job. Steps and env are
// emitted in a fixed order for determinism.
func writeJob(b *strings.Builder, j *jobSpec) {
	indent := "  "
	fmt.Fprintf(b, "%s# %s\n", indent, j.comment)
	fmt.Fprintf(b, "%s%s:\n", indent, j.id)
	fmt.Fprintf(b, "%s%sname: %s\n", indent, indent, yamlStr(j.name))
	fmt.Fprintf(b, "%s%sruns-on: ubuntu-latest\n", indent, indent)
	if j.needs != "" {
		fmt.Fprintf(b, "%s%sneeds: %s\n", indent, indent, j.needs)
	}
	if j.tier.TimeoutMinutes > 0 {
		fmt.Fprintf(b, "%s%stimeout-minutes: %d\n", indent, indent, j.tier.TimeoutMinutes)
	}

	// container block
	fmt.Fprintf(b, "%s%scontainer:\n", indent, indent)
	fmt.Fprintf(b, "%s%s%simage: %s:latest\n", indent, indent, indent, j.image)
	fmt.Fprintf(b, "%s%s%scredentials:\n", indent, indent, indent)
	fmt.Fprintf(b, "%s%s%s%susername: ${{ github.actor }}\n", indent, indent, indent, indent)
	fmt.Fprintf(b, "%s%s%s%spassword: ${{ secrets.GITHUB_TOKEN }}\n", indent, indent, indent, indent)
	substrate := len(j.tier.Substrate) > 0
	if substrate {
		fmt.Fprintf(b, "%s%s%soptions: --privileged -v /var/run/docker.sock:/var/run/docker.sock\n", indent, indent, indent)
	}

	// steps
	fmt.Fprintf(b, "%s%ssteps:\n", indent, indent)
	step := indent + indent + indent
	// checkout
	fmt.Fprintf(b, "%s- name: Checkout with submodules\n", step)
	fmt.Fprintf(b, "%s  uses: actions/checkout@v4\n", step)
	fmt.Fprintf(b, "%s  with:\n", step)
	fmt.Fprintf(b, "%s    submodules: recursive\n", step)
	fmt.Fprintf(b, "%s    fetch-depth: 0\n", step)
	// dockerd start (substrate only)
	if substrate {
		fmt.Fprintf(b, "%s- name: %s\n", step, yamlStr("Start docker host (substrate: "+joinSubstrate(j.tier.Substrate)+")"))
		fmt.Fprintf(b, "%s  run: |\n", step)
		fmt.Fprintf(b, "%s    if ! docker info >/dev/null 2>&1; then\n", step)
		fmt.Fprintf(b, "%s      (dockerd >/tmp/dockerd.log 2>&1 &)\n", step)
		fmt.Fprintf(b, "%s      for _ in $(seq 1 30); do docker info >/dev/null 2>&1 && break; sleep 1; done\n", step)
		fmt.Fprintf(b, "%s    fi\n", step)
		fmt.Fprintf(b, "%s    docker version\n", step)
	}
	// the tier verbs, each its own step, in declared order
	for _, verb := range j.tier.Verbs {
		fmt.Fprintf(b, "%s- name: %s\n", step, yamlStr("bash .ci/ctl.sh "+verb))
		fmt.Fprintf(b, "%s  env:\n", step)
		fmt.Fprintf(b, "%s    NX_BASE: %s\n", step, yamlStr(j.nxBase))
		fmt.Fprintf(b, "%s  run: bash .ci/ctl.sh %s\n", step, verb)
	}
}

// yamlStr renders s as a safe single-line YAML scalar. It double-quotes whenever
// s contains a character that would change the scalar's meaning unquoted (a
// colon-space, a leading indicator, a brace from a ${{ }} expression, etc.),
// escaping any embedded quote or backslash. A plain word is emitted bare so the
// common case stays readable.
func yamlStr(s string) string {
	if s == "" {
		return `""`
	}
	if needsQuote(s) {
		r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
		return `"` + r.Replace(s) + `"`
	}
	return s
}

func needsQuote(s string) bool {
	if strings.ContainsAny(s, ":#{}[]&*!|>'\"%@`") {
		return true
	}
	switch s[0] {
	case '-', '?', ',', ' ':
		return true
	}
	return strings.HasSuffix(s, " ")
}

func joinSubstrate(ss []contract.Substrate) string {
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = string(s)
	}
	return strings.Join(parts, ", ")
}
