import logging
import re

from corekinect.utils import Logger
from flask import Blueprint, Flask
from flask_socketio import SocketIO

# Auth handlers
from .auth.api_keys import create_api_key, delete_api_key, list_api_keys
from .auth.login import login
from .auth.me import me
from .auth.permission_sets import (
    create_permission_set,
    delete_permission_set,
    list_permission_sets,
    update_permission_set,
)
from .auth.permissions_list import list_permissions
from .auth.users import users_create, users_delete, users_list, users_update

# Firmware handlers
from .firmware.appid.create import create_appid
from .firmware.appid.delete import delete_appid
from .firmware.appid.get import get_appid
from .firmware.appid.list import list_appids
from .firmware.appid.update import update_appid

# Health
from .healthcheck import healthcheck

# MTIB handlers
from .mtib.get import get_mtib
from .mtib.list import list_mtibs
from .mtib.register import register_mtib
from .mtib.unregister import unregister_mtib

# Validation handlers
from .validation.tests.run import run_tests


# -------------------------------------------------
#                                        Log Filter
# -------------------------------------------------
class LogFilter(logging.Filter):
    """
    This filter omits the logs for frequently accessed routes such as healthcheck and deployment routes,
    as well as logs generated by accepted connections.
    """

    def __init__(self):
        super().__init__()
        # Compile regular expressions only once for efficiency
        self.healthcheck_pattern = re.compile(r"GET /v2/healthcheck HTTP")
        self.accepted_pattern = re.compile(r"\(.*\) accepted \(.*\)")

    def filter(self, record):
        # Convert the log record's message to string if it isn't already
        log_message = str(record.msg)
        # Check if the log record matches any of the specified patterns
        if self.healthcheck_pattern.search(log_message) or self.accepted_pattern.search(log_message):
            return False  # Do not log if the message matches any of the patterns
        return True  # Log other messages


# -------------------------------------------------
#                                     V2 API Routes
# -------------------------------------------------
v2 = Blueprint("v2", __name__, url_prefix="/v2")


def register_v2_routes(logger: Logger, server: Flask, socketio: SocketIO):
    # Add a log filter to avoid spamming the logs with commonly hit routes
    logger.add_filter(LogFilter())

    # Auth
    v2.add_url_rule("/auth/login",           view_func=login,          methods=["POST"])
    v2.add_url_rule("/auth/me",              view_func=me,             methods=["GET"])
    v2.add_url_rule("/auth/users",           view_func=users_list,     methods=["GET"])
    v2.add_url_rule("/auth/users",           view_func=users_create,   methods=["POST"])
    v2.add_url_rule("/auth/users/<user_id>", view_func=users_update,   methods=["PUT"])
    v2.add_url_rule("/auth/users/<user_id>", view_func=users_delete,   methods=["DELETE"])

    # Permission Sets
    v2.add_url_rule("/auth/permission-sets",          view_func=list_permission_sets,   methods=["GET"])
    v2.add_url_rule("/auth/permission-sets",          view_func=create_permission_set,  methods=["POST"])
    v2.add_url_rule("/auth/permission-sets/<set_id>", view_func=update_permission_set,  methods=["PUT"])
    v2.add_url_rule("/auth/permission-sets/<set_id>", view_func=delete_permission_set,  methods=["DELETE"])

    # API Keys
    v2.add_url_rule("/auth/api-keys",          view_func=list_api_keys,   methods=["GET"])
    v2.add_url_rule("/auth/api-keys",          view_func=create_api_key,  methods=["POST"])
    v2.add_url_rule("/auth/api-keys/<key_id>", view_func=delete_api_key,  methods=["DELETE"])

    # Available Permissions
    v2.add_url_rule("/auth/permissions",        view_func=list_permissions, methods=["GET"])

    # MTIB
    v2.add_url_rule("/mtib/list",            view_func=list_mtibs,      methods=["GET"])
    v2.add_url_rule("/mtib/get",             view_func=get_mtib,        methods=["GET"])
    v2.add_url_rule("/mtib/register",        view_func=register_mtib,   methods=["POST"])
    v2.add_url_rule("/mtib/unregister",      view_func=unregister_mtib, methods=["POST"])

    # Firmware
    v2.add_url_rule("/firmware/appid",             view_func=list_appids,   methods=["GET"])
    v2.add_url_rule("/firmware/appid",             view_func=create_appid,  methods=["POST"])
    v2.add_url_rule("/firmware/appid/<int:appId>", view_func=get_appid,     methods=["GET"])
    v2.add_url_rule("/firmware/appid/<int:appId>", view_func=update_appid,  methods=["PUT"])
    v2.add_url_rule("/firmware/appid/<int:appId>", view_func=delete_appid,  methods=["DELETE"])

    # Validation
    v2.add_url_rule("/validation/tests/run", view_func=run_tests,       methods=["POST"])

    # Health
    v2.add_url_rule("/healthcheck",          view_func=healthcheck,     methods=["GET"])

    server.register_blueprint(v2)
