apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    corekinect.com/environment: production
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    corekinect.com/environment: staging
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    corekinect.com/environment: dev
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
