apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/managed-by: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/managed-by: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: shared-services
  labels:
    app.kubernetes.io/managed-by: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: codectl-staging
  labels:
    app.kubernetes.io/managed-by: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: codectl-production
  labels:
    app.kubernetes.io/managed-by: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: fintel-staging
  labels:
    app.kubernetes.io/managed-by: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: fintel-production
  labels:
    app.kubernetes.io/managed-by: infrastructure
