# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protocols.mtib.mtib_pb2 as mtib__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mtib_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class MtibV1Stub(object):
    """This is the main interface used to access all the functionality built 
    into the MTIB hardware.

    This service gets served at port 50053

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/mtib.MtibV1/HealthCheck',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GpioConfig = channel.unary_unary(
                '/mtib.MtibV1/GpioConfig',
                request_serializer=mtib__pb2.GpioConfigRequest.SerializeToString,
                response_deserializer=mtib__pb2.GpioConfigResponse.FromString,
                _registered_method=True)
        self.GpioWrite = channel.unary_unary(
                '/mtib.MtibV1/GpioWrite',
                request_serializer=mtib__pb2.GpioWriteRequest.SerializeToString,
                response_deserializer=mtib__pb2.GpioWriteResponse.FromString,
                _registered_method=True)
        self.GpioRead = channel.unary_unary(
                '/mtib.MtibV1/GpioRead',
                request_serializer=mtib__pb2.GpioReadRequest.SerializeToString,
                response_deserializer=mtib__pb2.GpioReadResponse.FromString,
                _registered_method=True)
        self.AdcRead = channel.unary_unary(
                '/mtib.MtibV1/AdcRead',
                request_serializer=mtib__pb2.AdcReadRequest.SerializeToString,
                response_deserializer=mtib__pb2.AdcReadResponse.FromString,
                _registered_method=True)
        self.AdcReadAll = channel.unary_unary(
                '/mtib.MtibV1/AdcReadAll',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.AdcReadAllResponse.FromString,
                _registered_method=True)
        self.DutPowerEnable = channel.unary_unary(
                '/mtib.MtibV1/DutPowerEnable',
                request_serializer=mtib__pb2.DutPowerRequest.SerializeToString,
                response_deserializer=mtib__pb2.DutPowerResponse.FromString,
                _registered_method=True)
        self.DutPowerDisable = channel.unary_unary(
                '/mtib.MtibV1/DutPowerDisable',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.DutPowerResponse.FromString,
                _registered_method=True)
        self.DutPowerRead = channel.unary_unary(
                '/mtib.MtibV1/DutPowerRead',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.DutPowerReadResponse.FromString,
                _registered_method=True)
        self.DutChargePowerEnable = channel.unary_unary(
                '/mtib.MtibV1/DutChargePowerEnable',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.DutPowerResponse.FromString,
                _registered_method=True)
        self.DutChargePowerDisable = channel.unary_unary(
                '/mtib.MtibV1/DutChargePowerDisable',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.DutPowerResponse.FromString,
                _registered_method=True)
        self.DutChargePowerRead = channel.unary_unary(
                '/mtib.MtibV1/DutChargePowerRead',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.DutPowerReadResponse.FromString,
                _registered_method=True)
        self.AltimeterRead = channel.unary_unary(
                '/mtib.MtibV1/AltimeterRead',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.AltimeterReadResponse.FromString,
                _registered_method=True)
        self.AccelRead = channel.unary_unary(
                '/mtib.MtibV1/AccelRead',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.AccelReadResponse.FromString,
                _registered_method=True)
        self.GetFluidNcConfig = channel.unary_unary(
                '/mtib.MtibV1/GetFluidNcConfig',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.FluidNcConfigResponse.FromString,
                _registered_method=True)
        self.UpdateFluidNcConfig = channel.unary_unary(
                '/mtib.MtibV1/UpdateFluidNcConfig',
                request_serializer=mtib__pb2.UpdateFluidNcConfigRequest.SerializeToString,
                response_deserializer=mtib__pb2.UpdateFluidNcConfigResponse.FromString,
                _registered_method=True)
        self.SendGcode = channel.unary_unary(
                '/mtib.MtibV1/SendGcode',
                request_serializer=mtib__pb2.GcodeRequest.SerializeToString,
                response_deserializer=mtib__pb2.GcodeResponse.FromString,
                _registered_method=True)
        self.UploadMotionProfile = channel.unary_unary(
                '/mtib.MtibV1/UploadMotionProfile',
                request_serializer=mtib__pb2.MotionProfileRequest.SerializeToString,
                response_deserializer=mtib__pb2.MotionProfileResponse.FromString,
                _registered_method=True)
        self.ListMotionProfiles = channel.unary_unary(
                '/mtib.MtibV1/ListMotionProfiles',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.ListMotionProfilesResponse.FromString,
                _registered_method=True)
        self.ExecuteMotionProfile = channel.unary_unary(
                '/mtib.MtibV1/ExecuteMotionProfile',
                request_serializer=mtib__pb2.ExecuteProfileRequest.SerializeToString,
                response_deserializer=mtib__pb2.ExecuteProfileResponse.FromString,
                _registered_method=True)
        self.DeleteMotionProfile = channel.unary_unary(
                '/mtib.MtibV1/DeleteMotionProfile',
                request_serializer=mtib__pb2.DeleteProfileRequest.SerializeToString,
                response_deserializer=mtib__pb2.DeleteProfileResponse.FromString,
                _registered_method=True)
        self.SetDefaultMotionProfile = channel.unary_unary(
                '/mtib.MtibV1/SetDefaultMotionProfile',
                request_serializer=mtib__pb2.SetDefaultProfileRequest.SerializeToString,
                response_deserializer=mtib__pb2.SetDefaultProfileResponse.FromString,
                _registered_method=True)
        self.GetMotionStatus = channel.unary_unary(
                '/mtib.MtibV1/GetMotionStatus',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.GetMotionStatusResponse.FromString,
                _registered_method=True)
        self.MotionStart = channel.unary_unary(
                '/mtib.MtibV1/MotionStart',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.MotionStartResponse.FromString,
                _registered_method=True)
        self.MotionHome = channel.unary_unary(
                '/mtib.MtibV1/MotionHome',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.MotionHomeResponse.FromString,
                _registered_method=True)
        self.MotionStop = channel.unary_unary(
                '/mtib.MtibV1/MotionStop',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.MotionStopResponse.FromString,
                _registered_method=True)
        self.ListProgrammers = channel.unary_unary(
                '/mtib.MtibV1/ListProgrammers',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.ListProgrammersResponse.FromString,
                _registered_method=True)
        self.ListFwFiles = channel.unary_unary(
                '/mtib.MtibV1/ListFwFiles',
                request_serializer=mtib__pb2.Empty.SerializeToString,
                response_deserializer=mtib__pb2.ListFwFilesResponse.FromString,
                _registered_method=True)
        self.UploadFwFile = channel.stream_unary(
                '/mtib.MtibV1/UploadFwFile',
                request_serializer=mtib__pb2.UploadFwFileRequest.SerializeToString,
                response_deserializer=mtib__pb2.UploadFwFileResponse.FromString,
                _registered_method=True)
        self.DeleteFwFile = channel.unary_unary(
                '/mtib.MtibV1/DeleteFwFile',
                request_serializer=mtib__pb2.DeleteFwFileRequest.SerializeToString,
                response_deserializer=mtib__pb2.DeleteFwFileResponse.FromString,
                _registered_method=True)
        self.FlashFwFile = channel.unary_unary(
                '/mtib.MtibV1/FlashFwFile',
                request_serializer=mtib__pb2.FlashFwFileRequest.SerializeToString,
                response_deserializer=mtib__pb2.FlashFwFileResponse.FromString,
                _registered_method=True)
        self.UartStream = channel.stream_stream(
                '/mtib.MtibV1/UartStream',
                request_serializer=mtib__pb2.UartStreamRequest.SerializeToString,
                response_deserializer=mtib__pb2.UartStreamResponse.FromString,
                _registered_method=True)


class MtibV1Servicer(object):
    """This is the main interface used to access all the functionality built 
    into the MTIB hardware.

    This service gets served at port 50053

    """

    def HealthCheck(self, request, context):
        """HealthCheck
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GpioConfig(self, request, context):
        """Gpio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GpioWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GpioRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdcRead(self, request, context):
        """Adc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdcReadAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutPowerEnable(self, request, context):
        """DUT Power
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutPowerDisable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutPowerRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutChargePowerEnable(self, request, context):
        """DUT Charge Power
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutChargePowerDisable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutChargePowerRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AltimeterRead(self, request, context):
        """Sensors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccelRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFluidNcConfig(self, request, context):
        """FluidNc config
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFluidNcConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendGcode(self, request, context):
        """Gcode
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadMotionProfile(self, request, context):
        """Motion Profiles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMotionProfiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteMotionProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMotionProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefaultMotionProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMotionStatus(self, request, context):
        """Motion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MotionStart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MotionHome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MotionStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProgrammers(self, request, context):
        """Firmware
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFwFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFwFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFwFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlashFwFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UartStream(self, request_iterator, context):
        """Uart streams
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MtibV1Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GpioConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GpioConfig,
                    request_deserializer=mtib__pb2.GpioConfigRequest.FromString,
                    response_serializer=mtib__pb2.GpioConfigResponse.SerializeToString,
            ),
            'GpioWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.GpioWrite,
                    request_deserializer=mtib__pb2.GpioWriteRequest.FromString,
                    response_serializer=mtib__pb2.GpioWriteResponse.SerializeToString,
            ),
            'GpioRead': grpc.unary_unary_rpc_method_handler(
                    servicer.GpioRead,
                    request_deserializer=mtib__pb2.GpioReadRequest.FromString,
                    response_serializer=mtib__pb2.GpioReadResponse.SerializeToString,
            ),
            'AdcRead': grpc.unary_unary_rpc_method_handler(
                    servicer.AdcRead,
                    request_deserializer=mtib__pb2.AdcReadRequest.FromString,
                    response_serializer=mtib__pb2.AdcReadResponse.SerializeToString,
            ),
            'AdcReadAll': grpc.unary_unary_rpc_method_handler(
                    servicer.AdcReadAll,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.AdcReadAllResponse.SerializeToString,
            ),
            'DutPowerEnable': grpc.unary_unary_rpc_method_handler(
                    servicer.DutPowerEnable,
                    request_deserializer=mtib__pb2.DutPowerRequest.FromString,
                    response_serializer=mtib__pb2.DutPowerResponse.SerializeToString,
            ),
            'DutPowerDisable': grpc.unary_unary_rpc_method_handler(
                    servicer.DutPowerDisable,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.DutPowerResponse.SerializeToString,
            ),
            'DutPowerRead': grpc.unary_unary_rpc_method_handler(
                    servicer.DutPowerRead,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.DutPowerReadResponse.SerializeToString,
            ),
            'DutChargePowerEnable': grpc.unary_unary_rpc_method_handler(
                    servicer.DutChargePowerEnable,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.DutPowerResponse.SerializeToString,
            ),
            'DutChargePowerDisable': grpc.unary_unary_rpc_method_handler(
                    servicer.DutChargePowerDisable,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.DutPowerResponse.SerializeToString,
            ),
            'DutChargePowerRead': grpc.unary_unary_rpc_method_handler(
                    servicer.DutChargePowerRead,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.DutPowerReadResponse.SerializeToString,
            ),
            'AltimeterRead': grpc.unary_unary_rpc_method_handler(
                    servicer.AltimeterRead,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.AltimeterReadResponse.SerializeToString,
            ),
            'AccelRead': grpc.unary_unary_rpc_method_handler(
                    servicer.AccelRead,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.AccelReadResponse.SerializeToString,
            ),
            'GetFluidNcConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFluidNcConfig,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.FluidNcConfigResponse.SerializeToString,
            ),
            'UpdateFluidNcConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFluidNcConfig,
                    request_deserializer=mtib__pb2.UpdateFluidNcConfigRequest.FromString,
                    response_serializer=mtib__pb2.UpdateFluidNcConfigResponse.SerializeToString,
            ),
            'SendGcode': grpc.unary_unary_rpc_method_handler(
                    servicer.SendGcode,
                    request_deserializer=mtib__pb2.GcodeRequest.FromString,
                    response_serializer=mtib__pb2.GcodeResponse.SerializeToString,
            ),
            'UploadMotionProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadMotionProfile,
                    request_deserializer=mtib__pb2.MotionProfileRequest.FromString,
                    response_serializer=mtib__pb2.MotionProfileResponse.SerializeToString,
            ),
            'ListMotionProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMotionProfiles,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.ListMotionProfilesResponse.SerializeToString,
            ),
            'ExecuteMotionProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteMotionProfile,
                    request_deserializer=mtib__pb2.ExecuteProfileRequest.FromString,
                    response_serializer=mtib__pb2.ExecuteProfileResponse.SerializeToString,
            ),
            'DeleteMotionProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMotionProfile,
                    request_deserializer=mtib__pb2.DeleteProfileRequest.FromString,
                    response_serializer=mtib__pb2.DeleteProfileResponse.SerializeToString,
            ),
            'SetDefaultMotionProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefaultMotionProfile,
                    request_deserializer=mtib__pb2.SetDefaultProfileRequest.FromString,
                    response_serializer=mtib__pb2.SetDefaultProfileResponse.SerializeToString,
            ),
            'GetMotionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMotionStatus,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.GetMotionStatusResponse.SerializeToString,
            ),
            'MotionStart': grpc.unary_unary_rpc_method_handler(
                    servicer.MotionStart,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.MotionStartResponse.SerializeToString,
            ),
            'MotionHome': grpc.unary_unary_rpc_method_handler(
                    servicer.MotionHome,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.MotionHomeResponse.SerializeToString,
            ),
            'MotionStop': grpc.unary_unary_rpc_method_handler(
                    servicer.MotionStop,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.MotionStopResponse.SerializeToString,
            ),
            'ListProgrammers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProgrammers,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.ListProgrammersResponse.SerializeToString,
            ),
            'ListFwFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFwFiles,
                    request_deserializer=mtib__pb2.Empty.FromString,
                    response_serializer=mtib__pb2.ListFwFilesResponse.SerializeToString,
            ),
            'UploadFwFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFwFile,
                    request_deserializer=mtib__pb2.UploadFwFileRequest.FromString,
                    response_serializer=mtib__pb2.UploadFwFileResponse.SerializeToString,
            ),
            'DeleteFwFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFwFile,
                    request_deserializer=mtib__pb2.DeleteFwFileRequest.FromString,
                    response_serializer=mtib__pb2.DeleteFwFileResponse.SerializeToString,
            ),
            'FlashFwFile': grpc.unary_unary_rpc_method_handler(
                    servicer.FlashFwFile,
                    request_deserializer=mtib__pb2.FlashFwFileRequest.FromString,
                    response_serializer=mtib__pb2.FlashFwFileResponse.SerializeToString,
            ),
            'UartStream': grpc.stream_stream_rpc_method_handler(
                    servicer.UartStream,
                    request_deserializer=mtib__pb2.UartStreamRequest.FromString,
                    response_serializer=mtib__pb2.UartStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mtib.MtibV1', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mtib.MtibV1', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MtibV1(object):
    """This is the main interface used to access all the functionality built 
    into the MTIB hardware.

    This service gets served at port 50053

    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/HealthCheck',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GpioConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/GpioConfig',
            mtib__pb2.GpioConfigRequest.SerializeToString,
            mtib__pb2.GpioConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GpioWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/GpioWrite',
            mtib__pb2.GpioWriteRequest.SerializeToString,
            mtib__pb2.GpioWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GpioRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/GpioRead',
            mtib__pb2.GpioReadRequest.SerializeToString,
            mtib__pb2.GpioReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdcRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/AdcRead',
            mtib__pb2.AdcReadRequest.SerializeToString,
            mtib__pb2.AdcReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdcReadAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/AdcReadAll',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.AdcReadAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DutPowerEnable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/DutPowerEnable',
            mtib__pb2.DutPowerRequest.SerializeToString,
            mtib__pb2.DutPowerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DutPowerDisable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/DutPowerDisable',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.DutPowerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DutPowerRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/DutPowerRead',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.DutPowerReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DutChargePowerEnable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/DutChargePowerEnable',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.DutPowerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DutChargePowerDisable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/DutChargePowerDisable',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.DutPowerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DutChargePowerRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/DutChargePowerRead',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.DutPowerReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AltimeterRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/AltimeterRead',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.AltimeterReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccelRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/AccelRead',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.AccelReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFluidNcConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/GetFluidNcConfig',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.FluidNcConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFluidNcConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/UpdateFluidNcConfig',
            mtib__pb2.UpdateFluidNcConfigRequest.SerializeToString,
            mtib__pb2.UpdateFluidNcConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendGcode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/SendGcode',
            mtib__pb2.GcodeRequest.SerializeToString,
            mtib__pb2.GcodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadMotionProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/UploadMotionProfile',
            mtib__pb2.MotionProfileRequest.SerializeToString,
            mtib__pb2.MotionProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMotionProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/ListMotionProfiles',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.ListMotionProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteMotionProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/ExecuteMotionProfile',
            mtib__pb2.ExecuteProfileRequest.SerializeToString,
            mtib__pb2.ExecuteProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMotionProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/DeleteMotionProfile',
            mtib__pb2.DeleteProfileRequest.SerializeToString,
            mtib__pb2.DeleteProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDefaultMotionProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/SetDefaultMotionProfile',
            mtib__pb2.SetDefaultProfileRequest.SerializeToString,
            mtib__pb2.SetDefaultProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMotionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/GetMotionStatus',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.GetMotionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MotionStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/MotionStart',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.MotionStartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MotionHome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/MotionHome',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.MotionHomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MotionStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/MotionStop',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.MotionStopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProgrammers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/ListProgrammers',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.ListProgrammersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFwFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/ListFwFiles',
            mtib__pb2.Empty.SerializeToString,
            mtib__pb2.ListFwFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFwFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/mtib.MtibV1/UploadFwFile',
            mtib__pb2.UploadFwFileRequest.SerializeToString,
            mtib__pb2.UploadFwFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFwFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/DeleteFwFile',
            mtib__pb2.DeleteFwFileRequest.SerializeToString,
            mtib__pb2.DeleteFwFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FlashFwFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib.MtibV1/FlashFwFile',
            mtib__pb2.FlashFwFileRequest.SerializeToString,
            mtib__pb2.FlashFwFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UartStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/mtib.MtibV1/UartStream',
            mtib__pb2.UartStreamRequest.SerializeToString,
            mtib__pb2.UartStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
