services:
  operator:
    image: 10.4.45.2:5000/concord-operator:latest
    pull_policy: always
    network_mode: host
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_PATH=${LOG_PATH}
      - CLUSTER_UUID=${CLUSTER_UUID}
      - PROXY_SERVER_URL=${PROXY_SERVER_URL}
      - GRPC_SERVER_PORT=${GRPC_SERVER_PORT}
      - LOCAL_REGISTRY_PORT=${LOCAL_REGISTRY_PORT}
      - KUBECONFIG_PATH=${KUBECONFIG_PATH}
      - NODES_HOSTNAMES=${NODES_HOSTNAMES}
      - NODES_MGMT_ENABLED=${NODES_MGMT_ENABLED}
    volumes:
      # Docker socket, needed by application
      - /var/run/docker.sock:/var/run/docker.sock
      # Logs location (must match environment file)
      - /var/operator:/var/operator
      # Kubernetes configuration (must match environment file)
      - /home/orangepi/.kube/config:/home/orangepi/.kube/config
