apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-operator-theta
  labels:
    app: cluster-operator-theta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-operator-theta
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cluster-operator-theta
    spec:
      terminationGracePeriodSeconds: 1
      # Use host network so operator can reach test runners via localhost:hostPort
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - "concordagent01"
      containers:
      - name: cluster-operator-theta
        image: containers.ad.corekinect.com/concord-operator:latest
        imagePullPolicy: Always

        securityContext:
          privileged: true

        env:
        - name: LOG_LEVEL
          value: "4"
        - name: LOG_PATH
          value: "/var/log"
        - name: CLUSTER_UUID
          value: "82d22cc8-20e1-4554-853c-fae941d0083a"
        - name: PROXY_SERVER_URL
          value: "http://10.4.45.30:8001"
        - name: GRPC_SERVER_PORT
          value: "50052"
        - name: GRPC_SERVER_HOST
          value: "10.4.45.21"
        - name: LOCAL_REGISTRY_PORT
          value: "5000"
        - name: KUBECONFIG_PATH
          value: "/etc/rancher/k3s/k3s.yaml"
        - name: NODES_HOSTNAMES
          value: "concordagent01"
        - name: NODES_MGMT_ENABLED
          value: "false"

        volumeMounts:
        - name: logs
          mountPath: /var/log/operator
        - name: kubeconfig
          mountPath: /etc/rancher/k3s
          readOnly: true
        - name: docker-socket
          mountPath: /var/run/docker.sock

        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"

      volumes:
      - name: logs
        hostPath:
          path: /var/log/operator
      - name: kubeconfig
        hostPath:
          path: /etc/rancher/k3s
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
