# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protos.mtib_runner.mtib_runner_pb2 as mtib__runner__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mtib_runner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class MtibRunnerStub(object):
    """This is the main interface used to access all the functionality built 
    into the MTIB hardware.

    This service gets served at port 50051

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/mtib_runner.MtibRunner/HealthCheck',
                request_serializer=mtib__runner__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetRunnerInfo = channel.unary_unary(
                '/mtib_runner.MtibRunner/GetRunnerInfo',
                request_serializer=mtib__runner__pb2.GetRunnerInfoRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.GetRunnerInfoResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/mtib_runner.MtibRunner/Reset',
                request_serializer=mtib__runner__pb2.ResetRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.GpioConfig = channel.unary_unary(
                '/mtib_runner.MtibRunner/GpioConfig',
                request_serializer=mtib__runner__pb2.GpioConfigRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.GpioConfigResponse.FromString,
                _registered_method=True)
        self.GpioWrite = channel.unary_unary(
                '/mtib_runner.MtibRunner/GpioWrite',
                request_serializer=mtib__runner__pb2.GpioWriteRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.GpioWriteResponse.FromString,
                _registered_method=True)
        self.GpioRead = channel.unary_unary(
                '/mtib_runner.MtibRunner/GpioRead',
                request_serializer=mtib__runner__pb2.GpioReadRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.GpioReadResponse.FromString,
                _registered_method=True)
        self.AdcRead = channel.unary_unary(
                '/mtib_runner.MtibRunner/AdcRead',
                request_serializer=mtib__runner__pb2.AdcReadRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.AdcReadResponse.FromString,
                _registered_method=True)
        self.AdcReadAll = channel.unary_unary(
                '/mtib_runner.MtibRunner/AdcReadAll',
                request_serializer=mtib__runner__pb2.AdcReadAllRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.AdcReadAllResponse.FromString,
                _registered_method=True)
        self.DutPowerEnable = channel.unary_unary(
                '/mtib_runner.MtibRunner/DutPowerEnable',
                request_serializer=mtib__runner__pb2.DutPowerEnableRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.DutPowerEnableResponse.FromString,
                _registered_method=True)
        self.DutChargePowerEnable = channel.unary_unary(
                '/mtib_runner.MtibRunner/DutChargePowerEnable',
                request_serializer=mtib__runner__pb2.DutPowerEnableRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.DutPowerEnableResponse.FromString,
                _registered_method=True)
        self.DutVoltageSet = channel.unary_unary(
                '/mtib_runner.MtibRunner/DutVoltageSet',
                request_serializer=mtib__runner__pb2.DutVoltageSetRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.DutVoltageSetResponse.FromString,
                _registered_method=True)
        self.DutCurrentRead = channel.unary_unary(
                '/mtib_runner.MtibRunner/DutCurrentRead',
                request_serializer=mtib__runner__pb2.DutCurrentReadRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.DutCurrentReadResponse.FromString,
                _registered_method=True)
        self.DutVoltageRead = channel.unary_unary(
                '/mtib_runner.MtibRunner/DutVoltageRead',
                request_serializer=mtib__runner__pb2.DutVoltageReadRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.DutVoltageReadResponse.FromString,
                _registered_method=True)
        self.DutPowerRead = channel.unary_unary(
                '/mtib_runner.MtibRunner/DutPowerRead',
                request_serializer=mtib__runner__pb2.DutPowerReadRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.DutPowerReadResponse.FromString,
                _registered_method=True)
        self.AltimeterRead = channel.unary_unary(
                '/mtib_runner.MtibRunner/AltimeterRead',
                request_serializer=mtib__runner__pb2.AltimeterReadRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.AltimeterReadResponse.FromString,
                _registered_method=True)
        self.AccelRead = channel.unary_unary(
                '/mtib_runner.MtibRunner/AccelRead',
                request_serializer=mtib__runner__pb2.AccelReadRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.AccelReadResponse.FromString,
                _registered_method=True)
        self.AccelReadMaxForce = channel.unary_unary(
                '/mtib_runner.MtibRunner/AccelReadMaxForce',
                request_serializer=mtib__runner__pb2.AccelReadMaxRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.AccelReadMaxResponse.FromString,
                _registered_method=True)
        self.EepromRead = channel.unary_unary(
                '/mtib_runner.MtibRunner/EepromRead',
                request_serializer=mtib__runner__pb2.EepromReadRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.EepromReadResponse.FromString,
                _registered_method=True)
        self.EepromWrite = channel.unary_unary(
                '/mtib_runner.MtibRunner/EepromWrite',
                request_serializer=mtib__runner__pb2.EepromWriteRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.EepromWriteResponse.FromString,
                _registered_method=True)
        self.ListFwFiles = channel.unary_unary(
                '/mtib_runner.MtibRunner/ListFwFiles',
                request_serializer=mtib__runner__pb2.ListFwFilesRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.ListFwFilesResponse.FromString,
                _registered_method=True)
        self.UploadFwFile = channel.stream_unary(
                '/mtib_runner.MtibRunner/UploadFwFile',
                request_serializer=mtib__runner__pb2.UploadFwFileRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.UploadFwFileResponse.FromString,
                _registered_method=True)
        self.DeleteFwFile = channel.unary_unary(
                '/mtib_runner.MtibRunner/DeleteFwFile',
                request_serializer=mtib__runner__pb2.DeleteFwFileRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.DeleteFwFileResponse.FromString,
                _registered_method=True)
        self.FlashHexFile = channel.unary_unary(
                '/mtib_runner.MtibRunner/FlashHexFile',
                request_serializer=mtib__runner__pb2.FlashHexFileRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.FlashHexFileResponse.FromString,
                _registered_method=True)
        self.nrf9160UartStream = channel.stream_stream(
                '/mtib_runner.MtibRunner/nrf9160UartStream',
                request_serializer=mtib__runner__pb2.UartStreamRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.UartStreamResponse.FromString,
                _registered_method=True)
        self.nrf52840UartStream = channel.stream_stream(
                '/mtib_runner.MtibRunner/nrf52840UartStream',
                request_serializer=mtib__runner__pb2.UartStreamRequest.SerializeToString,
                response_deserializer=mtib__runner__pb2.UartStreamResponse.FromString,
                _registered_method=True)


class MtibRunnerServicer(object):
    """This is the main interface used to access all the functionality built 
    into the MTIB hardware.

    This service gets served at port 50051

    """

    def HealthCheck(self, request, context):
        """HealthCheck
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunnerInfo(self, request, context):
        """Hardware/System reset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Hardware/System reset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GpioConfig(self, request, context):
        """Gpio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GpioWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GpioRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdcRead(self, request, context):
        """Adc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdcReadAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutPowerEnable(self, request, context):
        """Power
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutChargePowerEnable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutVoltageSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutCurrentRead(self, request, context):
        """Power Monitor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutVoltageRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutPowerRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AltimeterRead(self, request, context):
        """Sensors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccelRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccelReadMaxForce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EepromRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EepromWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFwFiles(self, request, context):
        """Firmware Files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFwFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFwFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlashHexFile(self, request, context):
        """J-Link
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def nrf9160UartStream(self, request_iterator, context):
        """Uart streams
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def nrf52840UartStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MtibRunnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=mtib__runner__pb2.HealthCheckRequest.FromString,
                    response_serializer=mtib__runner__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetRunnerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunnerInfo,
                    request_deserializer=mtib__runner__pb2.GetRunnerInfoRequest.FromString,
                    response_serializer=mtib__runner__pb2.GetRunnerInfoResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=mtib__runner__pb2.ResetRequest.FromString,
                    response_serializer=mtib__runner__pb2.ResetResponse.SerializeToString,
            ),
            'GpioConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GpioConfig,
                    request_deserializer=mtib__runner__pb2.GpioConfigRequest.FromString,
                    response_serializer=mtib__runner__pb2.GpioConfigResponse.SerializeToString,
            ),
            'GpioWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.GpioWrite,
                    request_deserializer=mtib__runner__pb2.GpioWriteRequest.FromString,
                    response_serializer=mtib__runner__pb2.GpioWriteResponse.SerializeToString,
            ),
            'GpioRead': grpc.unary_unary_rpc_method_handler(
                    servicer.GpioRead,
                    request_deserializer=mtib__runner__pb2.GpioReadRequest.FromString,
                    response_serializer=mtib__runner__pb2.GpioReadResponse.SerializeToString,
            ),
            'AdcRead': grpc.unary_unary_rpc_method_handler(
                    servicer.AdcRead,
                    request_deserializer=mtib__runner__pb2.AdcReadRequest.FromString,
                    response_serializer=mtib__runner__pb2.AdcReadResponse.SerializeToString,
            ),
            'AdcReadAll': grpc.unary_unary_rpc_method_handler(
                    servicer.AdcReadAll,
                    request_deserializer=mtib__runner__pb2.AdcReadAllRequest.FromString,
                    response_serializer=mtib__runner__pb2.AdcReadAllResponse.SerializeToString,
            ),
            'DutPowerEnable': grpc.unary_unary_rpc_method_handler(
                    servicer.DutPowerEnable,
                    request_deserializer=mtib__runner__pb2.DutPowerEnableRequest.FromString,
                    response_serializer=mtib__runner__pb2.DutPowerEnableResponse.SerializeToString,
            ),
            'DutChargePowerEnable': grpc.unary_unary_rpc_method_handler(
                    servicer.DutChargePowerEnable,
                    request_deserializer=mtib__runner__pb2.DutPowerEnableRequest.FromString,
                    response_serializer=mtib__runner__pb2.DutPowerEnableResponse.SerializeToString,
            ),
            'DutVoltageSet': grpc.unary_unary_rpc_method_handler(
                    servicer.DutVoltageSet,
                    request_deserializer=mtib__runner__pb2.DutVoltageSetRequest.FromString,
                    response_serializer=mtib__runner__pb2.DutVoltageSetResponse.SerializeToString,
            ),
            'DutCurrentRead': grpc.unary_unary_rpc_method_handler(
                    servicer.DutCurrentRead,
                    request_deserializer=mtib__runner__pb2.DutCurrentReadRequest.FromString,
                    response_serializer=mtib__runner__pb2.DutCurrentReadResponse.SerializeToString,
            ),
            'DutVoltageRead': grpc.unary_unary_rpc_method_handler(
                    servicer.DutVoltageRead,
                    request_deserializer=mtib__runner__pb2.DutVoltageReadRequest.FromString,
                    response_serializer=mtib__runner__pb2.DutVoltageReadResponse.SerializeToString,
            ),
            'DutPowerRead': grpc.unary_unary_rpc_method_handler(
                    servicer.DutPowerRead,
                    request_deserializer=mtib__runner__pb2.DutPowerReadRequest.FromString,
                    response_serializer=mtib__runner__pb2.DutPowerReadResponse.SerializeToString,
            ),
            'AltimeterRead': grpc.unary_unary_rpc_method_handler(
                    servicer.AltimeterRead,
                    request_deserializer=mtib__runner__pb2.AltimeterReadRequest.FromString,
                    response_serializer=mtib__runner__pb2.AltimeterReadResponse.SerializeToString,
            ),
            'AccelRead': grpc.unary_unary_rpc_method_handler(
                    servicer.AccelRead,
                    request_deserializer=mtib__runner__pb2.AccelReadRequest.FromString,
                    response_serializer=mtib__runner__pb2.AccelReadResponse.SerializeToString,
            ),
            'AccelReadMaxForce': grpc.unary_unary_rpc_method_handler(
                    servicer.AccelReadMaxForce,
                    request_deserializer=mtib__runner__pb2.AccelReadMaxRequest.FromString,
                    response_serializer=mtib__runner__pb2.AccelReadMaxResponse.SerializeToString,
            ),
            'EepromRead': grpc.unary_unary_rpc_method_handler(
                    servicer.EepromRead,
                    request_deserializer=mtib__runner__pb2.EepromReadRequest.FromString,
                    response_serializer=mtib__runner__pb2.EepromReadResponse.SerializeToString,
            ),
            'EepromWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.EepromWrite,
                    request_deserializer=mtib__runner__pb2.EepromWriteRequest.FromString,
                    response_serializer=mtib__runner__pb2.EepromWriteResponse.SerializeToString,
            ),
            'ListFwFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFwFiles,
                    request_deserializer=mtib__runner__pb2.ListFwFilesRequest.FromString,
                    response_serializer=mtib__runner__pb2.ListFwFilesResponse.SerializeToString,
            ),
            'UploadFwFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFwFile,
                    request_deserializer=mtib__runner__pb2.UploadFwFileRequest.FromString,
                    response_serializer=mtib__runner__pb2.UploadFwFileResponse.SerializeToString,
            ),
            'DeleteFwFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFwFile,
                    request_deserializer=mtib__runner__pb2.DeleteFwFileRequest.FromString,
                    response_serializer=mtib__runner__pb2.DeleteFwFileResponse.SerializeToString,
            ),
            'FlashHexFile': grpc.unary_unary_rpc_method_handler(
                    servicer.FlashHexFile,
                    request_deserializer=mtib__runner__pb2.FlashHexFileRequest.FromString,
                    response_serializer=mtib__runner__pb2.FlashHexFileResponse.SerializeToString,
            ),
            'nrf9160UartStream': grpc.stream_stream_rpc_method_handler(
                    servicer.nrf9160UartStream,
                    request_deserializer=mtib__runner__pb2.UartStreamRequest.FromString,
                    response_serializer=mtib__runner__pb2.UartStreamResponse.SerializeToString,
            ),
            'nrf52840UartStream': grpc.stream_stream_rpc_method_handler(
                    servicer.nrf52840UartStream,
                    request_deserializer=mtib__runner__pb2.UartStreamRequest.FromString,
                    response_serializer=mtib__runner__pb2.UartStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mtib_runner.MtibRunner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mtib_runner.MtibRunner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MtibRunner(object):
    """This is the main interface used to access all the functionality built 
    into the MTIB hardware.

    This service gets served at port 50051

    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/HealthCheck',
            mtib__runner__pb2.HealthCheckRequest.SerializeToString,
            mtib__runner__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunnerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/GetRunnerInfo',
            mtib__runner__pb2.GetRunnerInfoRequest.SerializeToString,
            mtib__runner__pb2.GetRunnerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/Reset',
            mtib__runner__pb2.ResetRequest.SerializeToString,
            mtib__runner__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GpioConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/GpioConfig',
            mtib__runner__pb2.GpioConfigRequest.SerializeToString,
            mtib__runner__pb2.GpioConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GpioWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/GpioWrite',
            mtib__runner__pb2.GpioWriteRequest.SerializeToString,
            mtib__runner__pb2.GpioWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GpioRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/GpioRead',
            mtib__runner__pb2.GpioReadRequest.SerializeToString,
            mtib__runner__pb2.GpioReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdcRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/AdcRead',
            mtib__runner__pb2.AdcReadRequest.SerializeToString,
            mtib__runner__pb2.AdcReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdcReadAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/AdcReadAll',
            mtib__runner__pb2.AdcReadAllRequest.SerializeToString,
            mtib__runner__pb2.AdcReadAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DutPowerEnable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/DutPowerEnable',
            mtib__runner__pb2.DutPowerEnableRequest.SerializeToString,
            mtib__runner__pb2.DutPowerEnableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DutChargePowerEnable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/DutChargePowerEnable',
            mtib__runner__pb2.DutPowerEnableRequest.SerializeToString,
            mtib__runner__pb2.DutPowerEnableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DutVoltageSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/DutVoltageSet',
            mtib__runner__pb2.DutVoltageSetRequest.SerializeToString,
            mtib__runner__pb2.DutVoltageSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DutCurrentRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/DutCurrentRead',
            mtib__runner__pb2.DutCurrentReadRequest.SerializeToString,
            mtib__runner__pb2.DutCurrentReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DutVoltageRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/DutVoltageRead',
            mtib__runner__pb2.DutVoltageReadRequest.SerializeToString,
            mtib__runner__pb2.DutVoltageReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DutPowerRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/DutPowerRead',
            mtib__runner__pb2.DutPowerReadRequest.SerializeToString,
            mtib__runner__pb2.DutPowerReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AltimeterRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/AltimeterRead',
            mtib__runner__pb2.AltimeterReadRequest.SerializeToString,
            mtib__runner__pb2.AltimeterReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccelRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/AccelRead',
            mtib__runner__pb2.AccelReadRequest.SerializeToString,
            mtib__runner__pb2.AccelReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccelReadMaxForce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/AccelReadMaxForce',
            mtib__runner__pb2.AccelReadMaxRequest.SerializeToString,
            mtib__runner__pb2.AccelReadMaxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EepromRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/EepromRead',
            mtib__runner__pb2.EepromReadRequest.SerializeToString,
            mtib__runner__pb2.EepromReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EepromWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/EepromWrite',
            mtib__runner__pb2.EepromWriteRequest.SerializeToString,
            mtib__runner__pb2.EepromWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFwFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/ListFwFiles',
            mtib__runner__pb2.ListFwFilesRequest.SerializeToString,
            mtib__runner__pb2.ListFwFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFwFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/mtib_runner.MtibRunner/UploadFwFile',
            mtib__runner__pb2.UploadFwFileRequest.SerializeToString,
            mtib__runner__pb2.UploadFwFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFwFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/DeleteFwFile',
            mtib__runner__pb2.DeleteFwFileRequest.SerializeToString,
            mtib__runner__pb2.DeleteFwFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FlashHexFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtib_runner.MtibRunner/FlashHexFile',
            mtib__runner__pb2.FlashHexFileRequest.SerializeToString,
            mtib__runner__pb2.FlashHexFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def nrf9160UartStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/mtib_runner.MtibRunner/nrf9160UartStream',
            mtib__runner__pb2.UartStreamRequest.SerializeToString,
            mtib__runner__pb2.UartStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def nrf52840UartStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/mtib_runner.MtibRunner/nrf52840UartStream',
            mtib__runner__pb2.UartStreamRequest.SerializeToString,
            mtib__runner__pb2.UartStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
