/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "mtib_runner.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(mtib_runner_FwFileInfo, mtib_runner_FwFileInfo, AUTO)


PB_BIND(mtib_runner_RunnerInfo, mtib_runner_RunnerInfo, AUTO)


PB_BIND(mtib_runner_ResetRequest, mtib_runner_ResetRequest, AUTO)


PB_BIND(mtib_runner_ResetResponse, mtib_runner_ResetResponse, AUTO)


PB_BIND(mtib_runner_HealthCheckRequest, mtib_runner_HealthCheckRequest, AUTO)


PB_BIND(mtib_runner_HealthCheckResponse, mtib_runner_HealthCheckResponse, AUTO)


PB_BIND(mtib_runner_GetRunnerInfoRequest, mtib_runner_GetRunnerInfoRequest, AUTO)


PB_BIND(mtib_runner_GetRunnerInfoResponse, mtib_runner_GetRunnerInfoResponse, AUTO)


PB_BIND(mtib_runner_GpioConfigRequest, mtib_runner_GpioConfigRequest, AUTO)


PB_BIND(mtib_runner_GpioConfigResponse, mtib_runner_GpioConfigResponse, AUTO)


PB_BIND(mtib_runner_GpioWriteRequest, mtib_runner_GpioWriteRequest, AUTO)


PB_BIND(mtib_runner_GpioWriteResponse, mtib_runner_GpioWriteResponse, AUTO)


PB_BIND(mtib_runner_GpioReadRequest, mtib_runner_GpioReadRequest, AUTO)


PB_BIND(mtib_runner_GpioReadResponse, mtib_runner_GpioReadResponse, AUTO)


PB_BIND(mtib_runner_AdcReadRequest, mtib_runner_AdcReadRequest, AUTO)


PB_BIND(mtib_runner_AdcReadResponse, mtib_runner_AdcReadResponse, AUTO)


PB_BIND(mtib_runner_AdcReadAllRequest, mtib_runner_AdcReadAllRequest, AUTO)


PB_BIND(mtib_runner_AdcReadAllResponse, mtib_runner_AdcReadAllResponse, AUTO)


PB_BIND(mtib_runner_UartConfigRequest, mtib_runner_UartConfigRequest, AUTO)


PB_BIND(mtib_runner_UartConfigResponse, mtib_runner_UartConfigResponse, AUTO)


PB_BIND(mtib_runner_UartStreamRequest, mtib_runner_UartStreamRequest, AUTO)


PB_BIND(mtib_runner_UartStreamResponse, mtib_runner_UartStreamResponse, AUTO)


PB_BIND(mtib_runner_ListFwFilesRequest, mtib_runner_ListFwFilesRequest, AUTO)


PB_BIND(mtib_runner_ListFwFilesResponse, mtib_runner_ListFwFilesResponse, AUTO)


PB_BIND(mtib_runner_UploadFwFileRequest, mtib_runner_UploadFwFileRequest, AUTO)


PB_BIND(mtib_runner_UploadFwFileResponse, mtib_runner_UploadFwFileResponse, AUTO)


PB_BIND(mtib_runner_DeleteFwFileRequest, mtib_runner_DeleteFwFileRequest, AUTO)


PB_BIND(mtib_runner_DeleteFwFileResponse, mtib_runner_DeleteFwFileResponse, AUTO)


PB_BIND(mtib_runner_FlashHexFileRequest, mtib_runner_FlashHexFileRequest, AUTO)


PB_BIND(mtib_runner_FlashHexFileResponse, mtib_runner_FlashHexFileResponse, AUTO)


PB_BIND(mtib_runner_DutPowerEnableRequest, mtib_runner_DutPowerEnableRequest, AUTO)


PB_BIND(mtib_runner_DutPowerEnableResponse, mtib_runner_DutPowerEnableResponse, AUTO)


PB_BIND(mtib_runner_DutVoltageSetRequest, mtib_runner_DutVoltageSetRequest, AUTO)


PB_BIND(mtib_runner_DutVoltageSetResponse, mtib_runner_DutVoltageSetResponse, AUTO)


PB_BIND(mtib_runner_DutCurrentReadRequest, mtib_runner_DutCurrentReadRequest, AUTO)


PB_BIND(mtib_runner_DutCurrentReadResponse, mtib_runner_DutCurrentReadResponse, AUTO)


PB_BIND(mtib_runner_DutVoltageReadRequest, mtib_runner_DutVoltageReadRequest, AUTO)


PB_BIND(mtib_runner_DutVoltageReadResponse, mtib_runner_DutVoltageReadResponse, AUTO)


PB_BIND(mtib_runner_DutPowerReadRequest, mtib_runner_DutPowerReadRequest, AUTO)


PB_BIND(mtib_runner_DutPowerReadResponse, mtib_runner_DutPowerReadResponse, AUTO)


PB_BIND(mtib_runner_AltimeterReadRequest, mtib_runner_AltimeterReadRequest, AUTO)


PB_BIND(mtib_runner_AltimeterReadResponse, mtib_runner_AltimeterReadResponse, AUTO)


PB_BIND(mtib_runner_AccelReadRequest, mtib_runner_AccelReadRequest, AUTO)


PB_BIND(mtib_runner_AccelReadResponse, mtib_runner_AccelReadResponse, AUTO)


PB_BIND(mtib_runner_AccelReadMaxRequest, mtib_runner_AccelReadMaxRequest, AUTO)


PB_BIND(mtib_runner_AccelReadMaxResponse, mtib_runner_AccelReadMaxResponse, AUTO)


PB_BIND(mtib_runner_EepromReadRequest, mtib_runner_EepromReadRequest, AUTO)


PB_BIND(mtib_runner_EepromReadResponse, mtib_runner_EepromReadResponse, AUTO)


PB_BIND(mtib_runner_EepromWriteRequest, mtib_runner_EepromWriteRequest, AUTO)


PB_BIND(mtib_runner_EepromWriteResponse, mtib_runner_EepromWriteResponse, AUTO)










#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

