#@TYPE: Machine
#@NAME: Toradex Verdin iMX8M Mini Extra Configuration

require conf/machine/verdin-imx8mm.conf

# Ensure overlays are loaded at boot
TEZI_EXTERNAL_KERNEL_DEVICETREE_BOOT:append = " \
    ina219-overlay.dtbo \
    ad7689-overlay.dtbo \
    no-i2s.dtbo \
    no-i2c.dtbo \
    usb.dtbo \
"


