apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{DEPLOYMENT_NAME}}"
  labels:
    app: "{{DEPLOYMENT_NAME}}"
    corekinect.com/managed-by: concord
    corekinect.com/fixture-id: "{{FIXTURE_ID}}"
    corekinect.com/deployment-id: "{{DEPLOYMENT_ID}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{DEPLOYMENT_NAME}}"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: "{{DEPLOYMENT_NAME}}"
        corekinect.com/managed-by: concord
        corekinect.com/fixture-id: "{{FIXTURE_ID}}"
        corekinect.com/deployment-id: "{{DEPLOYMENT_ID}}"
    spec:
      terminationGracePeriodSeconds: 1
      initContainers:
      - name: remount-sys
        image: busybox:latest
        command: ['sh', '-c', 'mount -o remount,rw /sys']
        securityContext:
          privileged: true
      nodeSelector:
        kubernetes.io/hostname: "{{NODE_HOSTNAME}}"
      tolerations:
      - key: "corekinect.com/role"
        operator: "Equal"
        value: "edge"
        effect: "NoSchedule"
      containers:
      - name: mtib-server
        image: "{{IMAGE}}"
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 50053
          hostPort: 50053
        env:
        - name: HARDWARE_VERSION
          value: "REV1.1"
        - name: LOG_LEVEL
          value: "{{LOG_LEVEL}}"
        - name: LOG_PATH
          value: "/var/log"
        - name: SERVER_PORT
          value: "50053"
        - name: ASSETS_PATH
          value: "assets"
        - name: METRICS_ENABLED
          value: "{{METRICS_ENABLED}}"
        - name: METRICS_BROKER_URL
          value: "mqtt://kubecop.ad.corekinect.com:1883"
        - name: MOTION_ENABLED
          value: "{{MOTION_ENABLED}}"
        volumeMounts:
        - name: devices
          mountPath: /dev
        - name: logs
          mountPath: /var/log/runner
        - name: fw-files
          mountPath: /var/fw_files/
        - name: gpio
          mountPath: /sys/class/gpio
        - name: sys-bus-iio
          mountPath: /sys/bus/iio
        resources:
          requests:
            cpu: "{{CPU_REQUEST}}"
            memory: "{{MEMORY_REQUEST}}"
          limits:
            cpu: "{{CPU_LIMIT}}"
            memory: "{{MEMORY_LIMIT}}"
      volumes:
      - name: devices
        hostPath:
          path: /dev
      - name: logs
        hostPath:
          path: /var/log/runner
      - name: fw-files
        hostPath:
          path: /var/fw_files/
      - name: gpio
        hostPath:
          path: /sys/class/gpio
      - name: sys-bus-iio
        hostPath:
          path: /sys/bus/iio
