"""Zephyr/HAL ingestion parsers.

Two layers:
- fixture-string unit tests for every parser (run everywhere; fixtures
  mirror the REAL formats quoted in data/zephyr/VALIDATION.md), plus a
  fake-tree assembly/ensure() suite in tmp_path;
- live tests against the pinned clones in data/zephyr (skip-guarded).

Note on input-only pins: the ESP32-S3 has NO input-only GPIOs — its
soc_caps.h states "No GPIO is input only" and the datasheet pin table
lists GPIO46 as I/O/T.  The famous input-only GPIO46 belongs to the
ESP32-S2 (asserted below); on the original ESP32 it is GPIO34-39.
"""

from pathlib import Path

import pytest

from src.ecad.ingest.zephyr import (
    STRAPPING,
    NeedsFallbackTree,
    ZephyrTree,
    ZephyrTreeError,
    ensure,
    parse_dtsi_labels,
    parse_dtsi_ngpios,
    parse_input_only,
    parse_io_mux,
    parse_pin_file,
    parse_pinctrl,
    parse_sigmap,
)


def _find_repo_root() -> Path | None:
    """This worktree first, then the main checkout (data/ is not synced
    into worktrees; reading the main repo's data/ is sanctioned)."""
    for cand in (Path(__file__).resolve().parents[2],
                 Path("/Users/mateo/code/research-hardware")):
        if (cand / "data" / "zephyr" / "zephyr").is_dir():
            return cand
    return None


REPO_ROOT = _find_repo_root()
live = pytest.mark.skipif(REPO_ROOT is None,
                          reason="data/zephyr clones not present on this machine")


# --------------------------------------------------------------------------
# Fixture strings (formats copied from the real files / VALIDATION.md)
# --------------------------------------------------------------------------

PINCTRL = """\
/* NOTE: Autogenerated file using esp_genpinctrl.py */

/* I2C0_SDA */
#define I2C0_SDA_GPIO2 \\
\tESP32_PINMUX(2, ESP_I2CEXT0_SDA_IN, ESP_I2CEXT0_SDA_OUT)

#define LEDC_CH0_GPIO8 \\
\tESP32_PINMUX(8, ESP_NOSIG, ESP_LEDC_LS_SIG_OUT0)

#define SPIM2_MISO_GPIO13 \\
\tESP32_PINMUX(13, ESP_FSPIQ_IN, ESP_NOSIG)

#define UART0_TX_GPIO42 \\
\tESP32_PINMUX(42, ESP_NOSIG, ESP_U0TXD_OUT)

#define UART0_TX_GPIO43 \\
\tESP32_PINMUX(43, ESP_NOSIG, ESP_U0TXD_OUT)

#define UART0_RX_GPIO44 \\
\tESP32_PINMUX(44, ESP_U0RXD_IN, ESP_NOSIG)
"""

SIGMAP = """\
#define ESP_NOSIG                         ESP_SIG_INVAL

#define ESP_SPIQ_IN                   0
#define ESP_SPIQ_OUT                  0
#define ESP_U0RXD_IN                  12
#define ESP_U0TXD_OUT                 12
#define ESP_I2CEXT0_SDA_IN            30
#define ESP_I2CEXT0_SDA_OUT           30
#define ESP_FSPIQ_IN                  61
#define ESP_LEDC_LS_SIG_OUT0          45
"""

DTSI = """\
/ {
\tsoc {
\t\tuart0: uart@60000000 {
\t\t\tcompatible = "espressif,esp32-uart";
\t\t};

\t\tgpio: gpio {
\t\t\tcompatible = "simple-bus";
\t\t\tgpio-map = <
\t\t\t\t0x00 0x0 &gpio0 0x0 0x0
\t\t\t\t0x20 0x0 &gpio1 0x0 0x0
\t\t\t>;

\t\t\tgpio0: gpio@60004000 {
\t\t\t\tcompatible = "espressif,esp32-gpio";
\t\t\t\tngpios = <32>;  /* 0..31 */
\t\t\t};

\t\t\tgpio1: gpio@60004800 {
\t\t\t\tcompatible = "espressif,esp32-gpio";
\t\t\t\tngpios = <22>; /* 32..53 */
\t\t\t};
\t\t};

\t\ttwai: can@6002b000 {
\t\t\tcompatible = "espressif,esp32-twai";
\t\t};

\t\tpinctrl: pin-controller {
\t\t\tstatus = "okay";
\t\t};

\t\tflash: flash-controller@60002000 {
\t\t\tflash0: flash@0 {
\t\t\t\tcompatible = "soc-nv-flash";
\t\t\t};
\t\t};
\t};
};
"""

IO_MUX = """\
#define IO_MUX_GPIO0_REG        PERIPHS_IO_MUX_GPIO0_U
#define IO_MUX_GPIO13_REG       PERIPHS_IO_MUX_GPIO13_U
#define IO_MUX_GPIO43_REG       PERIPHS_IO_MUX_U0TXD_U
#define IO_MUX_GPIO44_REG       PERIPHS_IO_MUX_U0RXD_U
#define IO_MUX_GPIO46_REG       PERIPHS_IO_MUX_GPIO46_U

#define PERIPHS_IO_MUX_GPIO0_U            (REG_IO_MUX_BASE +0x04)
#define FUNC_GPIO0_GPIO0                            1
#define FUNC_GPIO0_GPIO0_0                          0

#define PERIPHS_IO_MUX_GPIO13_U           (REG_IO_MUX_BASE +0x38)
#define FUNC_GPIO13_FSPIQ                           4
#define FUNC_GPIO13_SUBSPIQ                         3
#define FUNC_GPIO13_FSPIIO7                         2
#define FUNC_GPIO13_GPIO13                          1
#define FUNC_GPIO13_GPIO13_0                        0

#define PERIPHS_IO_MUX_U0TXD_U            (REG_IO_MUX_BASE +0xb0)
#define FUNC_U0TXD_CLK_OUT1                         2
#define FUNC_U0TXD_GPIO43                           1
#define FUNC_U0TXD_U0TXD                            0

#define PERIPHS_IO_MUX_U0RXD_U            (REG_IO_MUX_BASE +0xb4)
#define FUNC_U0RXD_CLK_OUT2                         2
#define FUNC_U0RXD_GPIO44                           1
#define FUNC_U0RXD_U0RXD                            0

#define PERIPHS_IO_MUX_GPIO46_U           (REG_IO_MUX_BASE +0xbc)
#define FUNC_GPIO46_GPIO46                          1
#define FUNC_GPIO46_GPIO46_0                        0
"""

SOC_CAPS_S3 = """\
// No GPIO is input only
#define SOC_GPIO_VALID_GPIO_MASK         (0x1FFFFFFFFFFFFULL & ~(0ULL | BIT22 | BIT23 | BIT24 | BIT25))
#define SOC_GPIO_VALID_OUTPUT_GPIO_MASK  (SOC_GPIO_VALID_GPIO_MASK)
"""

SOC_CAPS_ESP32 = """\
#define SOC_GPIO_VALID_GPIO_MASK        (0xFFFFFFFFFFULL & ~(0ULL | BIT24 | BIT28 | BIT29 | BIT30 | BIT31))
#define SOC_GPIO_VALID_OUTPUT_GPIO_MASK (SOC_GPIO_VALID_GPIO_MASK & ~(0ULL | BIT34 | BIT35 | BIT36 | BIT37 | BIT38 | BIT39))
"""

SOC_CAPS_C3 = """\
#define SOC_GPIO_VALID_GPIO_MASK        ((1U<<SOC_GPIO_PIN_COUNT) - 1)
#define SOC_GPIO_VALID_OUTPUT_GPIO_MASK SOC_GPIO_VALID_GPIO_MASK
"""

PIN_FILE = """\
# Pinned sources for Espressif ingestion factory
# Resolved 2026-07-30

zephyr:
  url: https://github.com/zephyrproject-rtos/zephyr
  tag: v3.7.2            # newest patch of newest LTS series
  sha: bbbf8b30094dacd0d6830946ba206bcec8af6b0c
  sparse:
    - dts/xtensa/espressif
    - dts/riscv/espressif
    - include/zephyr/dt-bindings/pinctrl
    - boards/espressif

hal_espressif:
  url: https://github.com/zephyrproject-rtos/hal_espressif
  ref: 01fc4ec49b8b178d7aea765cdb8709311ee4c50b   # pinned by west.yml
  sha: 01fc4ec49b8b178d7aea765cdb8709311ee4c50b
  sparse:
    - components/soc

# Fallback (for SoCs absent from the LTS tree, currently esp32h2):
fallback:
  zephyr_tag: v4.4.1     # newest non-LTS release
  hal_espressif_rev: 19f979cfe66bcab09abe3b0b3aa419a664c1606c
"""


# --------------------------------------------------------------------------
# Parser unit tests (run everywhere)
# --------------------------------------------------------------------------

def test_parse_pinctrl_joins_continuations_and_groups():
    entries = parse_pinctrl(PINCTRL)
    by_key = {(e.group, e.gpio): e for e in entries}
    assert len(entries) == 6
    i2c = by_key[("I2C0_SDA", 2)]
    assert i2c.sig_in == "ESP_I2CEXT0_SDA_IN"
    assert i2c.sig_out == "ESP_I2CEXT0_SDA_OUT"


def test_parse_pinctrl_nosig_sentinel():
    entries = parse_pinctrl(PINCTRL)
    ledc = next(e for e in entries if e.group == "LEDC_CH0")
    assert ledc.sig_in is None  # ESP_NOSIG -> output-only signal
    assert ledc.sig_out == "ESP_LEDC_LS_SIG_OUT0"
    miso = next(e for e in entries if e.group == "SPIM2_MISO")
    assert miso.sig_out is None
    assert miso.sig_in == "ESP_FSPIQ_IN"


def test_parse_sigmap_numeric_defines_only():
    ids = parse_sigmap(SIGMAP)
    assert ids["ESP_U0TXD_OUT"] == 12
    assert ids["ESP_FSPIQ_IN"] == 61
    assert "ESP_NOSIG" not in ids  # alias of ESP_SIG_INVAL, not numeric


def test_parse_dtsi_dual_banks_and_labels():
    assert parse_dtsi_ngpios(DTSI) == (32, 22)
    labels = parse_dtsi_labels(DTSI)
    for expected in ("uart0", "gpio", "gpio0", "gpio1", "twai",
                     "pinctrl", "flash", "flash0"):
        assert expected in labels
    # twai's node name is can@... — label wins, node name is irrelevant
    assert "can" not in labels
    assert labels == tuple(sorted(set(labels)))


def test_parse_io_mux_pad_indirection_and_dedupe():
    funcs = parse_io_mux(IO_MUX)
    assert set(funcs) == {0, 13, 43, 44, 46}
    # pad U0TXD maps to GPIO43; functions ordered by IO MUX index
    assert funcs[43] == ("U0TXD", "GPIO43", "CLK_OUT1")
    # duplicate _0 alias deduped, real functions with digits kept
    assert funcs[0] == ("GPIO0",)
    assert funcs[13] == ("GPIO13", "FSPIIO7", "SUBSPIQ", "FSPIQ")
    assert funcs[46] == ("GPIO46",)


def test_parse_input_only_mask_shapes():
    assert parse_input_only(SOC_CAPS_S3) == ()          # S3: none
    assert parse_input_only(SOC_CAPS_ESP32) == (34, 35, 36, 37, 38, 39)
    assert parse_input_only(SOC_CAPS_C3) == ()
    assert parse_input_only("") == ()


def test_parse_pin_file_real_format():
    pin = parse_pin_file(PIN_FILE)
    assert pin["zephyr"]["sha"] == "bbbf8b30094dacd0d6830946ba206bcec8af6b0c"
    assert pin["zephyr"]["tag"] == "v3.7.2"  # inline comment stripped
    assert pin["zephyr"]["sparse"] == [
        "dts/xtensa/espressif", "dts/riscv/espressif",
        "include/zephyr/dt-bindings/pinctrl", "boards/espressif"]
    assert pin["hal_espressif"]["sparse"] == ["components/soc"]
    assert pin["fallback"]["zephyr_tag"] == "v4.4.1"


# --------------------------------------------------------------------------
# Fake-tree assembly + ensure() tests (run everywhere)
# --------------------------------------------------------------------------

ZSHA = "bbbf8b30094dacd0d6830946ba206bcec8af6b0c"
HSHA = "01fc4ec49b8b178d7aea765cdb8709311ee4c50b"


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def _fake_repo(tmp_path: Path) -> Path:
    root = tmp_path / "repo"
    dz = root / "data" / "zephyr"
    _write(dz / "PIN", PIN_FILE)
    _write(dz / "zephyr" / ".git" / "HEAD", ZSHA + "\n")
    _write(dz / "hal_espressif" / ".git" / "HEAD", HSHA + "\n")
    pinctrl = dz / "zephyr" / "include" / "zephyr" / "dt-bindings" / "pinctrl"
    _write(pinctrl / "esp32s3-pinctrl.h", PINCTRL)
    _write(pinctrl / "esp32s3-gpio-sigmap.h", SIGMAP)
    _write(dz / "zephyr" / "dts" / "xtensa" / "espressif" / "esp32s3"
           / "esp32s3_common.dtsi", DTSI)
    _write(dz / "zephyr" / "dts" / "riscv" / "espressif" / ".keep", "")
    _write(dz / "zephyr" / "boards" / "espressif" / ".keep", "")
    hal_soc = dz / "hal_espressif" / "components" / "soc"
    _write(hal_soc / "esp32s3" / "include" / "soc" / "io_mux_reg.h", IO_MUX)
    _write(hal_soc / "esp32s3" / "include" / "soc" / "soc_caps.h", SOC_CAPS_S3)
    # esp32h2 exists HAL-side only (mirrors the real LTS tree)
    _write(hal_soc / "esp32h2" / "include" / "soc" / "io_mux_reg.h", IO_MUX)
    return root


def test_ensure_ok_and_soc_assembly(tmp_path):
    tree = ensure(_fake_repo(tmp_path))
    soc = tree.soc("esp32s3")
    assert soc.gpio_count == 54  # 32 + 22
    # native-pin selection: UART0_TX offered on 42 and 43, but only
    # GPIO43's IO MUX carries U0TXD -> 43 wins
    assert soc.signals == {"SPIM2_MISO": 13, "UART0_RX": 44, "UART0_TX": 43}
    assert soc.gpios[43].iomux_functions == ("U0TXD", "GPIO43", "CLK_OUT1")
    assert soc.gpios[46].input_only is False
    assert soc.strapping == (0, 3, 45, 46)
    assert "twai" in soc.peripherals and "uart0" in soc.peripherals
    assert tree.soc("esp32s3") is soc  # cached


def test_ensure_missing_pin_raises(tmp_path):
    with pytest.raises(ZephyrTreeError, match="PIN"):
        ensure(tmp_path / "nowhere")


def test_ensure_missing_clone_gives_clone_command(tmp_path):
    root = _fake_repo(tmp_path)
    import shutil
    shutil.rmtree(root / "data" / "zephyr" / "hal_espressif")
    with pytest.raises(ZephyrTreeError) as exc:
        ensure(root)
    msg = str(exc.value)
    assert "git clone" in msg and "hal_espressif" in msg
    assert HSHA in msg  # ref-pinned repo: fetch+checkout by sha
    assert "sparse-checkout set components/soc" in msg


def test_ensure_drifted_sha_raises_with_fix(tmp_path):
    root = _fake_repo(tmp_path)
    _write(root / "data" / "zephyr" / "zephyr" / ".git" / "HEAD", "f" * 40)
    with pytest.raises(ZephyrTreeError) as exc:
        ensure(root)
    msg = str(exc.value)
    assert ZSHA in msg and "f" * 40 in msg
    assert "rm -rf" in msg and "--branch v3.7.2" in msg


def test_git_head_symbolic_ref_resolution(tmp_path):
    root = _fake_repo(tmp_path)
    gd = root / "data" / "zephyr" / "zephyr" / ".git"
    _write(gd / "HEAD", "ref: refs/heads/main\n")
    _write(gd / "refs" / "heads" / "main", ZSHA + "\n")
    ensure(root)  # resolves through the loose ref, still matches PIN


def test_soc_source_policy_and_needs_fallback(tmp_path):
    tree = ensure(_fake_repo(tmp_path))
    assert tree.soc_source("esp32s3") == "lts"
    assert tree.soc_source("esp32h2") == "fallback"
    with pytest.raises(NeedsFallbackTree) as exc:
        tree.soc("esp32h2")
    msg = str(exc.value)
    assert "git clone" in msg and "--branch v4.4.1" in msg
    assert "zephyr-fallback" in msg
    # once the fallback tree exists, esp32h2 parses from it
    fb = tree.fallback_dir
    _write(fb / "include" / "zephyr" / "dt-bindings" / "pinctrl"
           / "esp32h2-pinctrl.h", PINCTRL)
    _write(fb / "include" / "zephyr" / "dt-bindings" / "pinctrl"
           / "esp32h2-gpio-sigmap.h", SIGMAP)
    _write(fb / "dts" / "riscv" / "espressif" / "esp32h2"
           / "esp32h2_common.dtsi", DTSI)
    soc = tree.soc("esp32h2")
    assert soc.strapping == STRAPPING["esp32h2"] == (8, 9, 25)


def test_unknown_soc_raises(tmp_path):
    tree = ensure(_fake_repo(tmp_path))
    with pytest.raises(ZephyrTreeError, match="unknown SoC"):
        tree.soc("esp99")


# --------------------------------------------------------------------------
# Live tests against the pinned data/zephyr clones
# --------------------------------------------------------------------------

@pytest.fixture(scope="module")
def tree() -> ZephyrTree:
    assert REPO_ROOT is not None
    return ensure(REPO_ROOT)


@live
def test_live_ensure_matches_pin(tree):
    assert tree.pin["zephyr"]["tag"] == "v3.7.2"
    assert tree.soc_source("esp32s3") == "lts"
    assert tree.soc_source("esp32h2") == "fallback"


@live
def test_live_esp32s3(tree):
    soc = tree.soc("esp32s3")
    assert soc.gpio_count == 54          # dtsi banks 32 + 22
    assert soc.signals["UART0_TX"] == 43
    assert soc.signals["UART0_RX"] == 44
    assert soc.signals["SPIM2_MISO"] == 13  # FSPIQ home pad
    assert soc.gpios[43].iomux_functions[0] == "U0TXD"
    assert soc.strapping == (0, 3, 45, 46)
    assert 22 not in soc.gpios           # GPIO22-25 pads do not exist on S3
    for label in ("uart0", "uart1", "i2c0", "spi2", "twai", "ledc0",
                  "gpio0", "gpio1", "usb_serial"):
        assert label in soc.peripherals


@live
def test_live_input_only_truth(tree):
    # S3: no input-only pins (soc_caps: "No GPIO is input only"; the
    # datasheet pin table lists GPIO46 as I/O/T).
    s3 = tree.soc("esp32s3")
    assert s3.gpios[46].input_only is False
    assert not any(g.input_only for g in s3.gpios.values())
    # The input-only GPIO46 is an ESP32-S2 fact:
    s2 = tree.soc("esp32s2")
    assert s2.gpios[46].input_only is True
    # ESP32: GPIO34-39 are input-only.
    esp32 = tree.soc("esp32")
    assert all(esp32.gpios[n].input_only for n in (34, 35, 36, 37, 38, 39))
    assert esp32.gpios[33].input_only is False


@live
def test_live_esp32(tree):
    soc = tree.soc("esp32")
    assert soc.gpio_count == 40          # banks 32 + 8
    assert soc.signals["UART0_TX"] == 1  # U0TXD home pad
    assert soc.signals["UART0_RX"] == 3
    assert soc.strapping == (0, 2, 5, 12, 15)


@live
def test_live_all_lts_socs_parse(tree):
    counts = {"esp32": 40, "esp32s2": 54, "esp32s3": 54,
              "esp32c3": 26, "esp32c6": 30}
    for name, expected in counts.items():
        soc = tree.soc(name)
        assert soc.gpio_count == expected, name
        assert soc.gpios and soc.signals, name
        assert "uart0" in soc.peripherals, name
        assert soc.strapping == STRAPPING[name], name
        # every default placement points at a GPIO with a real IO MUX pad
        assert all(g in soc.gpios for g in soc.signals.values()), name


@live
def test_live_esp32h2_fallback_policy(tree):
    assert tree.soc_source("esp32h2") == "fallback"
    if tree.fallback_dir.is_dir():
        soc = tree.soc("esp32h2")
        assert soc.strapping == (8, 9, 25)
        assert soc.gpios
    else:
        with pytest.raises(NeedsFallbackTree) as exc:
            tree.soc("esp32h2")
        assert "v4.4.1" in str(exc.value)
