/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "mtib_posix.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HealthCheckRequest, HealthCheckRequest, AUTO)


PB_BIND(HealthCheckResponse, HealthCheckResponse, AUTO)


PB_BIND(GpioConfigRequest, GpioConfigRequest, AUTO)


PB_BIND(GpioConfigResponse, GpioConfigResponse, AUTO)


PB_BIND(GpioWriteRequest, GpioWriteRequest, AUTO)


PB_BIND(GpioWriteResponse, GpioWriteResponse, AUTO)


PB_BIND(GpioReadRequest, GpioReadRequest, AUTO)


PB_BIND(GpioReadResponse, GpioReadResponse, AUTO)


PB_BIND(AdcReadRequest, AdcReadRequest, AUTO)


PB_BIND(AdcReadResponse, AdcReadResponse, AUTO)


PB_BIND(AdcReadAllRequest, AdcReadAllRequest, AUTO)


PB_BIND(AdcReadAllResponse, AdcReadAllResponse, AUTO)


PB_BIND(UartConfigRequest, UartConfigRequest, AUTO)


PB_BIND(UartConfigResponse, UartConfigResponse, AUTO)


PB_BIND(UartStreamRequest, UartStreamRequest, AUTO)


PB_BIND(UartStreamResponse, UartStreamResponse, AUTO)


PB_BIND(ListFwFilesRequest, ListFwFilesRequest, AUTO)


PB_BIND(FwFileInfo, FwFileInfo, AUTO)


PB_BIND(ListFwFilesResponse, ListFwFilesResponse, AUTO)


PB_BIND(UploadFwFileRequest, UploadFwFileRequest, AUTO)


PB_BIND(UploadFwFileResponse, UploadFwFileResponse, AUTO)


PB_BIND(DeleteFwFileRequest, DeleteFwFileRequest, AUTO)


PB_BIND(DeleteFwFileResponse, DeleteFwFileResponse, AUTO)


PB_BIND(FlashHexFileRequest, FlashHexFileRequest, AUTO)


PB_BIND(FlashHexFileResponse, FlashHexFileResponse, AUTO)


PB_BIND(DutPowerEnableRequest, DutPowerEnableRequest, AUTO)


PB_BIND(DutPowerEnableResponse, DutPowerEnableResponse, AUTO)


PB_BIND(DutVoltageSetRequest, DutVoltageSetRequest, AUTO)


PB_BIND(DutVoltageSetResponse, DutVoltageSetResponse, AUTO)


PB_BIND(DutCurrentReadRequest, DutCurrentReadRequest, AUTO)


PB_BIND(DutCurrentReadResponse, DutCurrentReadResponse, AUTO)


PB_BIND(DutVoltageReadRequest, DutVoltageReadRequest, AUTO)


PB_BIND(DutVoltageReadResponse, DutVoltageReadResponse, AUTO)


PB_BIND(DutPowerReadRequest, DutPowerReadRequest, AUTO)


PB_BIND(DutPowerReadResponse, DutPowerReadResponse, AUTO)


PB_BIND(AltimeterReadRequest, AltimeterReadRequest, AUTO)


PB_BIND(AltimeterReadResponse, AltimeterReadResponse, AUTO)


PB_BIND(AccelReadRequest, AccelReadRequest, AUTO)


PB_BIND(AccelReadResponse, AccelReadResponse, AUTO)


PB_BIND(AccelReadMaxRequest, AccelReadMaxRequest, AUTO)


PB_BIND(AccelReadMaxResponse, AccelReadMaxResponse, AUTO)


PB_BIND(EepromReadRequest, EepromReadRequest, AUTO)


PB_BIND(EepromReadResponse, EepromReadResponse, AUTO)


PB_BIND(EepromWriteRequest, EepromWriteRequest, AUTO)


PB_BIND(EepromWriteResponse, EepromWriteResponse, AUTO)










#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

