# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mtib_zephyr_pb2 as mtib__zephyr__pb2


class MtibZephyrStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GpioConfigurePin = channel.unary_unary(
                '/MtibZephyr/GpioConfigurePin',
                request_serializer=mtib__zephyr__pb2.GpioConfigurePinRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.GpioConfigurePinResponse.FromString,
                )
        self.GpioSetPin = channel.unary_unary(
                '/MtibZephyr/GpioSetPin',
                request_serializer=mtib__zephyr__pb2.GpioSetPinRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.GpioSetPinResponse.FromString,
                )
        self.GpioReadPin = channel.unary_unary(
                '/MtibZephyr/GpioReadPin',
                request_serializer=mtib__zephyr__pb2.GpioReadPinRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.GpioReadPinResponse.FromString,
                )
        self.AdcReadChannel = channel.unary_unary(
                '/MtibZephyr/AdcReadChannel',
                request_serializer=mtib__zephyr__pb2.AdcReadChannelRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.AdcReadChannelResponse.FromString,
                )
        self.AdcReadAllChannels = channel.unary_unary(
                '/MtibZephyr/AdcReadAllChannels',
                request_serializer=mtib__zephyr__pb2.AdcReadAllChannelsRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.AdcReadAllChannelsResponse.FromString,
                )
        self.DutEnablePower = channel.unary_unary(
                '/MtibZephyr/DutEnablePower',
                request_serializer=mtib__zephyr__pb2.DutEnablePowerRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.DutEnablePowerResponse.FromString,
                )
        self.DutEnableCharger = channel.unary_unary(
                '/MtibZephyr/DutEnableCharger',
                request_serializer=mtib__zephyr__pb2.DutEnableChargerRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.DutEnableChargerResponse.FromString,
                )
        self.DutSetOutputVoltage = channel.unary_unary(
                '/MtibZephyr/DutSetOutputVoltage',
                request_serializer=mtib__zephyr__pb2.DutSetOutputVoltageRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.DutSetOutputVoltageResponse.FromString,
                )
        self.Ina219ReadCurrent = channel.unary_unary(
                '/MtibZephyr/Ina219ReadCurrent',
                request_serializer=mtib__zephyr__pb2.Ina219ReadCurrentRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.Ina219ReadCurrentResponse.FromString,
                )
        self.Ina219ReadVoltage = channel.unary_unary(
                '/MtibZephyr/Ina219ReadVoltage',
                request_serializer=mtib__zephyr__pb2.Ina219ReadVoltageRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.Ina219ReadVoltageResponse.FromString,
                )
        self.Ina219ReadPower = channel.unary_unary(
                '/MtibZephyr/Ina219ReadPower',
                request_serializer=mtib__zephyr__pb2.Ina219ReadPowerRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.Ina219ReadPowerResponse.FromString,
                )
        self.Bmp390ReadValues = channel.unary_unary(
                '/MtibZephyr/Bmp390ReadValues',
                request_serializer=mtib__zephyr__pb2.Bmp390ReadValuesRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.Bmp390ReadValuesResponse.FromString,
                )
        self.Lis2de12ReadValues = channel.unary_unary(
                '/MtibZephyr/Lis2de12ReadValues',
                request_serializer=mtib__zephyr__pb2.Lis2de12ReadValuesRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.Lis2de12ReadValuesResponse.FromString,
                )
        self.Lis2de12ReadMaxForce = channel.unary_unary(
                '/MtibZephyr/Lis2de12ReadMaxForce',
                request_serializer=mtib__zephyr__pb2.Lis2de12ReadMaxForceRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.Lis2de12ReadMaxForceResponse.FromString,
                )
        self.EepromReadFromMem = channel.unary_unary(
                '/MtibZephyr/EepromReadFromMem',
                request_serializer=mtib__zephyr__pb2.EepromReadFromMemRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.EepromReadFromMemResponse.FromString,
                )
        self.EepromWriteToMem = channel.unary_unary(
                '/MtibZephyr/EepromWriteToMem',
                request_serializer=mtib__zephyr__pb2.EepromWriteToMemRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.EepromWriteToMemResponse.FromString,
                )
        self.SigmaToPiMessage = channel.unary_unary(
                '/MtibZephyr/SigmaToPiMessage',
                request_serializer=mtib__zephyr__pb2.UartMessageRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.UartMessageResponse.FromString,
                )
        self.PiToSigmaMessage = channel.unary_unary(
                '/MtibZephyr/PiToSigmaMessage',
                request_serializer=mtib__zephyr__pb2.UartMessageRequest.SerializeToString,
                response_deserializer=mtib__zephyr__pb2.UartMessageResponse.FromString,
                )


class MtibZephyrServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GpioConfigurePin(self, request, context):
        """Gpio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GpioSetPin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GpioReadPin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdcReadChannel(self, request, context):
        """Adc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdcReadAllChannels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutEnablePower(self, request, context):
        """Power
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutEnableCharger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutSetOutputVoltage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ina219ReadCurrent(self, request, context):
        """Power Monitor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ina219ReadVoltage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ina219ReadPower(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Bmp390ReadValues(self, request, context):
        """Altimeter 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lis2de12ReadValues(self, request, context):
        """Accelerometer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lis2de12ReadMaxForce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EepromReadFromMem(self, request, context):
        """Memory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EepromWriteToMem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SigmaToPiMessage(self, request, context):
        """DUT -> Orange Pi
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PiToSigmaMessage(self, request, context):
        """Orange Pi -> Sigma
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MtibZephyrServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GpioConfigurePin': grpc.unary_unary_rpc_method_handler(
                    servicer.GpioConfigurePin,
                    request_deserializer=mtib__zephyr__pb2.GpioConfigurePinRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.GpioConfigurePinResponse.SerializeToString,
            ),
            'GpioSetPin': grpc.unary_unary_rpc_method_handler(
                    servicer.GpioSetPin,
                    request_deserializer=mtib__zephyr__pb2.GpioSetPinRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.GpioSetPinResponse.SerializeToString,
            ),
            'GpioReadPin': grpc.unary_unary_rpc_method_handler(
                    servicer.GpioReadPin,
                    request_deserializer=mtib__zephyr__pb2.GpioReadPinRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.GpioReadPinResponse.SerializeToString,
            ),
            'AdcReadChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.AdcReadChannel,
                    request_deserializer=mtib__zephyr__pb2.AdcReadChannelRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.AdcReadChannelResponse.SerializeToString,
            ),
            'AdcReadAllChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.AdcReadAllChannels,
                    request_deserializer=mtib__zephyr__pb2.AdcReadAllChannelsRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.AdcReadAllChannelsResponse.SerializeToString,
            ),
            'DutEnablePower': grpc.unary_unary_rpc_method_handler(
                    servicer.DutEnablePower,
                    request_deserializer=mtib__zephyr__pb2.DutEnablePowerRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.DutEnablePowerResponse.SerializeToString,
            ),
            'DutEnableCharger': grpc.unary_unary_rpc_method_handler(
                    servicer.DutEnableCharger,
                    request_deserializer=mtib__zephyr__pb2.DutEnableChargerRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.DutEnableChargerResponse.SerializeToString,
            ),
            'DutSetOutputVoltage': grpc.unary_unary_rpc_method_handler(
                    servicer.DutSetOutputVoltage,
                    request_deserializer=mtib__zephyr__pb2.DutSetOutputVoltageRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.DutSetOutputVoltageResponse.SerializeToString,
            ),
            'Ina219ReadCurrent': grpc.unary_unary_rpc_method_handler(
                    servicer.Ina219ReadCurrent,
                    request_deserializer=mtib__zephyr__pb2.Ina219ReadCurrentRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.Ina219ReadCurrentResponse.SerializeToString,
            ),
            'Ina219ReadVoltage': grpc.unary_unary_rpc_method_handler(
                    servicer.Ina219ReadVoltage,
                    request_deserializer=mtib__zephyr__pb2.Ina219ReadVoltageRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.Ina219ReadVoltageResponse.SerializeToString,
            ),
            'Ina219ReadPower': grpc.unary_unary_rpc_method_handler(
                    servicer.Ina219ReadPower,
                    request_deserializer=mtib__zephyr__pb2.Ina219ReadPowerRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.Ina219ReadPowerResponse.SerializeToString,
            ),
            'Bmp390ReadValues': grpc.unary_unary_rpc_method_handler(
                    servicer.Bmp390ReadValues,
                    request_deserializer=mtib__zephyr__pb2.Bmp390ReadValuesRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.Bmp390ReadValuesResponse.SerializeToString,
            ),
            'Lis2de12ReadValues': grpc.unary_unary_rpc_method_handler(
                    servicer.Lis2de12ReadValues,
                    request_deserializer=mtib__zephyr__pb2.Lis2de12ReadValuesRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.Lis2de12ReadValuesResponse.SerializeToString,
            ),
            'Lis2de12ReadMaxForce': grpc.unary_unary_rpc_method_handler(
                    servicer.Lis2de12ReadMaxForce,
                    request_deserializer=mtib__zephyr__pb2.Lis2de12ReadMaxForceRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.Lis2de12ReadMaxForceResponse.SerializeToString,
            ),
            'EepromReadFromMem': grpc.unary_unary_rpc_method_handler(
                    servicer.EepromReadFromMem,
                    request_deserializer=mtib__zephyr__pb2.EepromReadFromMemRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.EepromReadFromMemResponse.SerializeToString,
            ),
            'EepromWriteToMem': grpc.unary_unary_rpc_method_handler(
                    servicer.EepromWriteToMem,
                    request_deserializer=mtib__zephyr__pb2.EepromWriteToMemRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.EepromWriteToMemResponse.SerializeToString,
            ),
            'SigmaToPiMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SigmaToPiMessage,
                    request_deserializer=mtib__zephyr__pb2.UartMessageRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.UartMessageResponse.SerializeToString,
            ),
            'PiToSigmaMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PiToSigmaMessage,
                    request_deserializer=mtib__zephyr__pb2.UartMessageRequest.FromString,
                    response_serializer=mtib__zephyr__pb2.UartMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MtibZephyr', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MtibZephyr(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GpioConfigurePin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/GpioConfigurePin',
            mtib__zephyr__pb2.GpioConfigurePinRequest.SerializeToString,
            mtib__zephyr__pb2.GpioConfigurePinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GpioSetPin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/GpioSetPin',
            mtib__zephyr__pb2.GpioSetPinRequest.SerializeToString,
            mtib__zephyr__pb2.GpioSetPinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GpioReadPin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/GpioReadPin',
            mtib__zephyr__pb2.GpioReadPinRequest.SerializeToString,
            mtib__zephyr__pb2.GpioReadPinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AdcReadChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/AdcReadChannel',
            mtib__zephyr__pb2.AdcReadChannelRequest.SerializeToString,
            mtib__zephyr__pb2.AdcReadChannelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AdcReadAllChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/AdcReadAllChannels',
            mtib__zephyr__pb2.AdcReadAllChannelsRequest.SerializeToString,
            mtib__zephyr__pb2.AdcReadAllChannelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DutEnablePower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/DutEnablePower',
            mtib__zephyr__pb2.DutEnablePowerRequest.SerializeToString,
            mtib__zephyr__pb2.DutEnablePowerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DutEnableCharger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/DutEnableCharger',
            mtib__zephyr__pb2.DutEnableChargerRequest.SerializeToString,
            mtib__zephyr__pb2.DutEnableChargerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DutSetOutputVoltage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/DutSetOutputVoltage',
            mtib__zephyr__pb2.DutSetOutputVoltageRequest.SerializeToString,
            mtib__zephyr__pb2.DutSetOutputVoltageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ina219ReadCurrent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/Ina219ReadCurrent',
            mtib__zephyr__pb2.Ina219ReadCurrentRequest.SerializeToString,
            mtib__zephyr__pb2.Ina219ReadCurrentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ina219ReadVoltage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/Ina219ReadVoltage',
            mtib__zephyr__pb2.Ina219ReadVoltageRequest.SerializeToString,
            mtib__zephyr__pb2.Ina219ReadVoltageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ina219ReadPower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/Ina219ReadPower',
            mtib__zephyr__pb2.Ina219ReadPowerRequest.SerializeToString,
            mtib__zephyr__pb2.Ina219ReadPowerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Bmp390ReadValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/Bmp390ReadValues',
            mtib__zephyr__pb2.Bmp390ReadValuesRequest.SerializeToString,
            mtib__zephyr__pb2.Bmp390ReadValuesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Lis2de12ReadValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/Lis2de12ReadValues',
            mtib__zephyr__pb2.Lis2de12ReadValuesRequest.SerializeToString,
            mtib__zephyr__pb2.Lis2de12ReadValuesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Lis2de12ReadMaxForce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/Lis2de12ReadMaxForce',
            mtib__zephyr__pb2.Lis2de12ReadMaxForceRequest.SerializeToString,
            mtib__zephyr__pb2.Lis2de12ReadMaxForceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EepromReadFromMem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/EepromReadFromMem',
            mtib__zephyr__pb2.EepromReadFromMemRequest.SerializeToString,
            mtib__zephyr__pb2.EepromReadFromMemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EepromWriteToMem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/EepromWriteToMem',
            mtib__zephyr__pb2.EepromWriteToMemRequest.SerializeToString,
            mtib__zephyr__pb2.EepromWriteToMemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SigmaToPiMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/SigmaToPiMessage',
            mtib__zephyr__pb2.UartMessageRequest.SerializeToString,
            mtib__zephyr__pb2.UartMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PiToSigmaMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MtibZephyr/PiToSigmaMessage',
            mtib__zephyr__pb2.UartMessageRequest.SerializeToString,
            mtib__zephyr__pb2.UartMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
