# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protocols.test_case.test_case_pb2 as test__case__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in test_case_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TestCaseRuntimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/test_case.TestCaseRuntimeService/HealthCheck',
                request_serializer=test__case__pb2.Empty.SerializeToString,
                response_deserializer=test__case__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetTestInfo = channel.unary_unary(
                '/test_case.TestCaseRuntimeService/GetTestInfo',
                request_serializer=test__case__pb2.Empty.SerializeToString,
                response_deserializer=test__case__pb2.GetTestInfoResponse.FromString,
                _registered_method=True)
        self.Run = channel.unary_stream(
                '/test_case.TestCaseRuntimeService/Run',
                request_serializer=test__case__pb2.RunRequest.SerializeToString,
                response_deserializer=test__case__pb2.RunResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/test_case.TestCaseRuntimeService/Stop',
                request_serializer=test__case__pb2.StopRequest.SerializeToString,
                response_deserializer=test__case__pb2.StopResponse.FromString,
                _registered_method=True)
        self.GetAssets = channel.unary_unary(
                '/test_case.TestCaseRuntimeService/GetAssets',
                request_serializer=test__case__pb2.Empty.SerializeToString,
                response_deserializer=test__case__pb2.GetAssetsResponse.FromString,
                _registered_method=True)
        self.GetAsset = channel.unary_unary(
                '/test_case.TestCaseRuntimeService/GetAsset',
                request_serializer=test__case__pb2.GetAssetRequest.SerializeToString,
                response_deserializer=test__case__pb2.GetAssetRequest.FromString,
                _registered_method=True)


class TestCaseRuntimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTestInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Run(self, request, context):
        """Runs a specific test case.

        The test is a series of individual steps, that
        can run serially or in parallel
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stops a test that is currently executing. 

        Test will stop no matter what. either that
        or something went terribly wrong, and you are
        panicking. dont worry, i am too.    :)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssets(self, request, context):
        """Gets all the assets generated by the test, such as captures,
        logs, and any additional results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAsset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestCaseRuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=test__case__pb2.Empty.FromString,
                    response_serializer=test__case__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetTestInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTestInfo,
                    request_deserializer=test__case__pb2.Empty.FromString,
                    response_serializer=test__case__pb2.GetTestInfoResponse.SerializeToString,
            ),
            'Run': grpc.unary_stream_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=test__case__pb2.RunRequest.FromString,
                    response_serializer=test__case__pb2.RunResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=test__case__pb2.StopRequest.FromString,
                    response_serializer=test__case__pb2.StopResponse.SerializeToString,
            ),
            'GetAssets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssets,
                    request_deserializer=test__case__pb2.Empty.FromString,
                    response_serializer=test__case__pb2.GetAssetsResponse.SerializeToString,
            ),
            'GetAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAsset,
                    request_deserializer=test__case__pb2.GetAssetRequest.FromString,
                    response_serializer=test__case__pb2.GetAssetRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test_case.TestCaseRuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('test_case.TestCaseRuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TestCaseRuntimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/test_case.TestCaseRuntimeService/HealthCheck',
            test__case__pb2.Empty.SerializeToString,
            test__case__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTestInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/test_case.TestCaseRuntimeService/GetTestInfo',
            test__case__pb2.Empty.SerializeToString,
            test__case__pb2.GetTestInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/test_case.TestCaseRuntimeService/Run',
            test__case__pb2.RunRequest.SerializeToString,
            test__case__pb2.RunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/test_case.TestCaseRuntimeService/Stop',
            test__case__pb2.StopRequest.SerializeToString,
            test__case__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/test_case.TestCaseRuntimeService/GetAssets',
            test__case__pb2.Empty.SerializeToString,
            test__case__pb2.GetAssetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/test_case.TestCaseRuntimeService/GetAsset',
            test__case__pb2.GetAssetRequest.SerializeToString,
            test__case__pb2.GetAssetRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
