apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shared-couchdb.fullname" . }}-config
  labels:
    {{- include "shared-couchdb.labels" . | nindent 4 }}
data:
  local.ini: |
    [couchdb]
    single_node=true
    max_document_size = 50000000

    [chttpd]
    require_valid_user = true
    max_http_request_size = 4294967296
    enable_cors = true
    bind_address = 0.0.0.0
    port = 5984

    [chttpd_auth]
    require_valid_user = true
    authentication_redirect = /_utils/session.html

    [httpd]
    WWW-Authenticate = Basic realm="couchdb"
    bind_address = 0.0.0.0

    {{- if .Values.cors.enabled }}
    [cors]
    origins = {{ .Values.cors.origins }}
    credentials = true
    methods = {{ .Values.cors.methods }}
    headers = {{ .Values.cors.headers }}
    {{- end }}

    [log]
    level = warn
