apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shared-couchdb.fullname" . }}-credentials
  labels:
    {{- include "shared-couchdb.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.auth.adminUser | quote }}
  admin-password: {{ .Values.auth.adminPassword | quote }}
