{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: concord-frontend
  labels:
    {{- include "concord.labels" . | nindent 4 }}
    {{- include "concord.frontend.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "concord.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
{{- end }}
