/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "mtib-pi-stm.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GpioConfigurePinRequest, GpioConfigurePinRequest, AUTO)


PB_BIND(GpioConfigurePinResponse, GpioConfigurePinResponse, AUTO)


PB_BIND(GpioSetPinRequest, GpioSetPinRequest, AUTO)


PB_BIND(GpioSetPinResponse, GpioSetPinResponse, AUTO)


PB_BIND(GpioReadPinRequest, GpioReadPinRequest, AUTO)


PB_BIND(GpioReadPinResponse, GpioReadPinResponse, AUTO)


PB_BIND(AdcReadChannelRequest, AdcReadChannelRequest, AUTO)


PB_BIND(AdcReadChannelResponse, AdcReadChannelResponse, AUTO)


PB_BIND(AdcReadAllChannelsRequest, AdcReadAllChannelsRequest, AUTO)


PB_BIND(AdcReadAllChannelsResponse, AdcReadAllChannelsResponse, AUTO)


PB_BIND(Bmp390ReadValuesRequest, Bmp390ReadValuesRequest, AUTO)


PB_BIND(Bmp390ReadValuesResponse, Bmp390ReadValuesResponse, AUTO)


PB_BIND(Lis2de12ReadValuesRequest, Lis2de12ReadValuesRequest, AUTO)


PB_BIND(Lis2de12ReadValuesResponse, Lis2de12ReadValuesResponse, AUTO)


PB_BIND(Lis2de12ReadMaxForceRequest, Lis2de12ReadMaxForceRequest, AUTO)


PB_BIND(Lis2de12ReadMaxForceResponse, Lis2de12ReadMaxForceResponse, AUTO)


PB_BIND(EepromWriteToMemRequest, EepromWriteToMemRequest, AUTO)


PB_BIND(EepromWriteToMemResponse, EepromWriteToMemResponse, AUTO)


PB_BIND(EepromReadFromMemRequest, EepromReadFromMemRequest, AUTO)


PB_BIND(EepromReadFromMemResponse, EepromReadFromMemResponse, 2)


PB_BIND(Ina219ReadCurrentRequest, Ina219ReadCurrentRequest, AUTO)


PB_BIND(Ina219ReadCurrentResponse, Ina219ReadCurrentResponse, AUTO)


PB_BIND(Ina219ReadVoltageRequest, Ina219ReadVoltageRequest, AUTO)


PB_BIND(Ina219ReadVoltageResponse, Ina219ReadVoltageResponse, AUTO)


PB_BIND(Ina219ReadPowerRequest, Ina219ReadPowerRequest, AUTO)


PB_BIND(Ina219ReadPowerResponse, Ina219ReadPowerResponse, AUTO)


PB_BIND(UartMessageRequest, UartMessageRequest, AUTO)


PB_BIND(UartMessageResponse, UartMessageResponse, AUTO)


PB_BIND(DutEnablePowerRequest, DutEnablePowerRequest, AUTO)


PB_BIND(DutEnablePowerResponse, DutEnablePowerResponse, AUTO)


PB_BIND(DutEnableChargerRequest, DutEnableChargerRequest, AUTO)


PB_BIND(DutEnableChargerResponse, DutEnableChargerResponse, AUTO)


PB_BIND(DutSetOutputVoltageRequest, DutSetOutputVoltageRequest, AUTO)


PB_BIND(DutSetOutputVoltageResponse, DutSetOutputVoltageResponse, AUTO)







#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

