
# CONFIG_THREAD_ANALYZER=y
# CONFIG_THREAD_ANALYZER_USE_PRINTK=y
# CONFIG_THREAD_ANALYZER_AUTO=y
# CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=5

# CoreKinect VSM driver
CONFIG_CK_MODULES_VSM=y
CONFIG_CK_MODULES_VSM_BLE_SERVER=n
CONFIG_CK_MODULES_VSM_THREADS_DEBUG_LEVEL=3
CONFIG_CK_MODULES_VSM_SENSOR_DEBUG_LEVEL=3
CONFIG_CK_MODULES_VSM_TESTS_ENABLED=n
CONFIG_CK_MODULES_VSM_I2C_METRICS_ENABLED=n

# Logging
CONFIG_LOG=y
CONFIG_MAIN_STACK_SIZE=20000
CONFIG_LOG_BUFFER_SIZE=20000
CONFIG_LOG_MODE_DEFERRED=n
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_CBPRINTF_FP_SUPPORT=y


# System
CONFIG_RING_BUFFER=y
CONFIG_POLL=y
CONFIG_ASSERT=y
CONFIG_POLL=y
CONFIG_FPU=y
CONFIG_NEWLIB_LIBC=y

# Debugging
CONFIG_HW_STACK_PROTECTION=y
CONFIG_THREAD_MONITOR=y
CONFIG_INIT_STACKS=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_NAME=y
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_EXCEPTION_STACK_TRACE=y
CONFIG_DEBUG_INFO=y

# Shell
CONFIG_SHELL=n
CONFIG_I2C_SHELL=n

# Peripherals
CONFIG_I2C=y
CONFIG_I2C_GPIO=y
CONFIG_SPI=y

# Sensor
CONFIG_SENSOR=y
CONFIG_SENSOR_LOG_LEVEL_DBG=n