# CONFIG_HAVE_CUSTOM_LINKER_SCRIPT=y
# CONFIG_CUSTOM_LINKER_SCRIPT="boards/linker_psp.ld"

# Logging
CONFIG_LOG=y
# CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BUFFER_SIZE=20000
CONFIG_CBPRINTF_FP_SUPPORT=y

# System
CONFIG_RING_BUFFER=y
CONFIG_POLL=y
CONFIG_NUM_PREEMPT_PRIORITIES=121
CONFIG_ASSERT=y
CONFIG_POLL=y
CONFIG_FPU=y
CONFIG_NEWLIB_LIBC=y
CONFIG_MAIN_STACK_SIZE=20000
CONFIG_HEAP_MEM_POOL_SIZE=40000

# Debugging
CONFIG_THREAD_MONITOR=y
CONFIG_INIT_STACKS=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_NAME=y
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_EXCEPTION_STACK_TRACE=y
CONFIG_DEBUG_INFO=y

# # Thread analyzer
# CONFIG_THREAD_ANALYZER=y
# CONFIG_THREAD_ANALYZER_AUTO=y
# CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=5
# CONFIG_THREAD_ANALYZER_USE_PRINTK=y

# # Shell
# CONFIG_SHELL=y
# CONFIG_I2C_SHELL=y

# Peripherals
CONFIG_I2C=y
CONFIG_SPI=y

# Sensor 
CONFIG_SENSOR=y
CONFIG_SENSOR_LOG_LEVEL_DBG=n

# PPG Sensor
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_PAH8151=y
CONFIG_PAH8151_TRIGGER=y
CONFIG_LSM6DSO_TRIGGER_OWN_THREAD=y
CONFIG_LSM6DSO_THREAD_PRIORITY=110
