stepping:
  dir_delay_us: 0
  disable_delay_us: 0
  engine: RMT
  idle_ms: 250
  pulse_us: 2
  
axes:
  x:
    acceleration_mm_per_sec2: '300.0'
    homing:
      allow_single_axis: true
      cycle: 1
      feed_mm_per_min: 8000.0
      feed_scaler: 1.1
      mpos_mm: 0.0
      positive_direction: false
      seek_mm_per_min: 8000.0
      seek_scaler: 1.1
      settle_ms: 250
    max_rate_mm_per_min: 20000.0
    max_travel_mm: 500
    motor0:
      limit_neg_pin: gpio.33:low
      limit_pos_pin: gpio.32:low
      pulloff_mm: 5.0
      stepstick:
        direction_pin: gpio.4
        disable_pin: gpio.18:high
        ms1_pin: gpio.27:high
        ms2_pin: gpio.14:high
        ms3_pin: gpio.12:high
        reset_pin: gpio.13:high
        step_pin: gpio.5
    soft_limits: true
    steps_per_mm: 80
  # y:
  #   homing: 
  #     cycle: 1
  #     settle_ms: 250
  #     mpos_mm: 0.000
  #     seek_mm_per_min: 8000.000
  #     feed_mm_per_min: 8000.000
  #     seek_scaler: 1.100
  #     feed_scaler: 1.100
  #     allow_single_axis: true
  #     positive_direction: false
  #   steps_per_mm: 40.000
  #   max_rate_mm_per_min: 20000.000    
  #   acceleration_mm_per_sec2: 340.000
  #   max_travel_mm: 520
  #   soft_limits: true
  #   motor0:
  #     limit_pos_pin: gpio.32:low
  #     limit_neg_pin: gpio.33:low
  #     stepstick:
  #       step_pin: gpio.21
  #       direction_pin: gpio.19
  #       disable_pin: gpio.23:high
  #       reset_pin: gpio.22:high
  #       ms1_pin: gpio.15:high
  #       ms2_pin: gpio.9:high
  #       ms3_pin: gpio.10:low
