# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseProduct(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Product']] = 'Product'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ProductActions[_PrismaModelT]':
        from .client import get_client

        return actions.ProductActions[_PrismaModelT](client or get_client(), cls)


class BaseTestPackage(_PrismaModel):
    __prisma_model__: ClassVar[Literal['TestPackage']] = 'TestPackage'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TestPackageActions[_PrismaModelT]':
        from .client import get_client

        return actions.TestPackageActions[_PrismaModelT](client or get_client(), cls)


class BaseProductTarget(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ProductTarget']] = 'ProductTarget'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ProductTargetActions[_PrismaModelT]':
        from .client import get_client

        return actions.ProductTargetActions[_PrismaModelT](client or get_client(), cls)


class BaseBoard(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Board']] = 'Board'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BoardActions[_PrismaModelT]':
        from .client import get_client

        return actions.BoardActions[_PrismaModelT](client or get_client(), cls)


class BaseBoardRevision(_PrismaModel):
    __prisma_model__: ClassVar[Literal['BoardRevision']] = 'BoardRevision'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BoardRevisionActions[_PrismaModelT]':
        from .client import get_client

        return actions.BoardRevisionActions[_PrismaModelT](client or get_client(), cls)


class BaseFirmwareSet(_PrismaModel):
    __prisma_model__: ClassVar[Literal['FirmwareSet']] = 'FirmwareSet'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.FirmwareSetActions[_PrismaModelT]':
        from .client import get_client

        return actions.FirmwareSetActions[_PrismaModelT](client or get_client(), cls)


class BaseFirmwareBuild(_PrismaModel):
    __prisma_model__: ClassVar[Literal['FirmwareBuild']] = 'FirmwareBuild'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.FirmwareBuildActions[_PrismaModelT]':
        from .client import get_client

        return actions.FirmwareBuildActions[_PrismaModelT](client or get_client(), cls)


class BaseProductStageConfig(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ProductStageConfig']] = 'ProductStageConfig'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ProductStageConfigActions[_PrismaModelT]':
        from .client import get_client

        return actions.ProductStageConfigActions[_PrismaModelT](client or get_client(), cls)


class BaseValidationQueueEntry(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ValidationQueueEntry']] = 'ValidationQueueEntry'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ValidationQueueEntryActions[_PrismaModelT]':
        from .client import get_client

        return actions.ValidationQueueEntryActions[_PrismaModelT](client or get_client(), cls)


class BaseBuildRun(_PrismaModel):
    __prisma_model__: ClassVar[Literal['BuildRun']] = 'BuildRun'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BuildRunActions[_PrismaModelT]':
        from .client import get_client

        return actions.BuildRunActions[_PrismaModelT](client or get_client(), cls)


class BaseBuildJob(_PrismaModel):
    __prisma_model__: ClassVar[Literal['BuildJob']] = 'BuildJob'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BuildJobActions[_PrismaModelT]':
        from .client import get_client

        return actions.BuildJobActions[_PrismaModelT](client or get_client(), cls)


class BaseBuildArtifact(_PrismaModel):
    __prisma_model__: ClassVar[Literal['BuildArtifact']] = 'BuildArtifact'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BuildArtifactActions[_PrismaModelT]':
        from .client import get_client

        return actions.BuildArtifactActions[_PrismaModelT](client or get_client(), cls)


class BaseSession(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Session']] = 'Session'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SessionActions[_PrismaModelT]':
        from .client import get_client

        return actions.SessionActions[_PrismaModelT](client or get_client(), cls)


class BaseDevice(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Device']] = 'Device'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.DeviceActions[_PrismaModelT]':
        from .client import get_client

        return actions.DeviceActions[_PrismaModelT](client or get_client(), cls)


class BaseFixtureDesign(_PrismaModel):
    __prisma_model__: ClassVar[Literal['FixtureDesign']] = 'FixtureDesign'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.FixtureDesignActions[_PrismaModelT]':
        from .client import get_client

        return actions.FixtureDesignActions[_PrismaModelT](client or get_client(), cls)


class BaseFixture(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Fixture']] = 'Fixture'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.FixtureActions[_PrismaModelT]':
        from .client import get_client

        return actions.FixtureActions[_PrismaModelT](client or get_client(), cls)


class BaseFixtureSlot(_PrismaModel):
    __prisma_model__: ClassVar[Literal['FixtureSlot']] = 'FixtureSlot'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.FixtureSlotActions[_PrismaModelT]':
        from .client import get_client

        return actions.FixtureSlotActions[_PrismaModelT](client or get_client(), cls)


class BaseNode(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Node']] = 'Node'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.NodeActions[_PrismaModelT]':
        from .client import get_client

        return actions.NodeActions[_PrismaModelT](client or get_client(), cls)


class BaseIcleDevice(_PrismaModel):
    __prisma_model__: ClassVar[Literal['IcleDevice']] = 'IcleDevice'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.IcleDeviceActions[_PrismaModelT]':
        from .client import get_client

        return actions.IcleDeviceActions[_PrismaModelT](client or get_client(), cls)


class BaseIclePendingCommand(_PrismaModel):
    __prisma_model__: ClassVar[Literal['IclePendingCommand']] = 'IclePendingCommand'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.IclePendingCommandActions[_PrismaModelT]':
        from .client import get_client

        return actions.IclePendingCommandActions[_PrismaModelT](client or get_client(), cls)


class BaseIcleLog(_PrismaModel):
    __prisma_model__: ClassVar[Literal['IcleLog']] = 'IcleLog'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.IcleLogActions[_PrismaModelT]':
        from .client import get_client

        return actions.IcleLogActions[_PrismaModelT](client or get_client(), cls)


class BaseDeployment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Deployment']] = 'Deployment'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.DeploymentActions[_PrismaModelT]':
        from .client import get_client

        return actions.DeploymentActions[_PrismaModelT](client or get_client(), cls)


class BaseTest(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Test']] = 'Test'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TestActions[_PrismaModelT]':
        from .client import get_client

        return actions.TestActions[_PrismaModelT](client or get_client(), cls)


class BaseTestExecution(_PrismaModel):
    __prisma_model__: ClassVar[Literal['TestExecution']] = 'TestExecution'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TestExecutionActions[_PrismaModelT]':
        from .client import get_client

        return actions.TestExecutionActions[_PrismaModelT](client or get_client(), cls)


class BaseTestStep(_PrismaModel):
    __prisma_model__: ClassVar[Literal['TestStep']] = 'TestStep'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TestStepActions[_PrismaModelT]':
        from .client import get_client

        return actions.TestStepActions[_PrismaModelT](client or get_client(), cls)


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class BasePermissionSet(_PrismaModel):
    __prisma_model__: ClassVar[Literal['PermissionSet']] = 'PermissionSet'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.PermissionSetActions[_PrismaModelT]':
        from .client import get_client

        return actions.PermissionSetActions[_PrismaModelT](client or get_client(), cls)


class BaseApiKey(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ApiKey']] = 'ApiKey'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ApiKeyActions[_PrismaModelT]':
        from .client import get_client

        return actions.ApiKeyActions[_PrismaModelT](client or get_client(), cls)


class BaseAuditLog(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AuditLog']] = 'AuditLog'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AuditLogActions[_PrismaModelT]':
        from .client import get_client

        return actions.AuditLogActions[_PrismaModelT](client or get_client(), cls)


class BaseSecret(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Secret']] = 'Secret'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SecretActions[_PrismaModelT]':
        from .client import get_client

        return actions.SecretActions[_PrismaModelT](client or get_client(), cls)


class BaseSetting(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Setting']] = 'Setting'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SettingActions[_PrismaModelT]':
        from .client import get_client

        return actions.SettingActions[_PrismaModelT](client or get_client(), cls)


class BaseLog(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Log']] = 'Log'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.LogActions[_PrismaModelT]':
        from .client import get_client

        return actions.LogActions[_PrismaModelT](client or get_client(), cls)


class BasePollCache(_PrismaModel):
    __prisma_model__: ClassVar[Literal['PollCache']] = 'PollCache'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.PollCacheActions[_PrismaModelT]':
        from .client import get_client

        return actions.PollCacheActions[_PrismaModelT](client or get_client(), cls)


class BaseRecipeVersion(_PrismaModel):
    __prisma_model__: ClassVar[Literal['RecipeVersion']] = 'RecipeVersion'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.RecipeVersionActions[_PrismaModelT]':
        from .client import get_client

        return actions.RecipeVersionActions[_PrismaModelT](client or get_client(), cls)


class BaseRecipeTemplate(_PrismaModel):
    __prisma_model__: ClassVar[Literal['RecipeTemplate']] = 'RecipeTemplate'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.RecipeTemplateActions[_PrismaModelT]':
        from .client import get_client

        return actions.RecipeTemplateActions[_PrismaModelT](client or get_client(), cls)


