# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template enums.py.jinja --
from ._compat import StrEnum


class NodeStatus(StrEnum):
    ONLINE = 'ONLINE'
    OFFLINE = 'OFFLINE'
    MAINTENANCE = 'MAINTENANCE'
    ERROR = 'ERROR'

class NodeType(StrEnum):
    MANUFACTURING = 'MANUFACTURING'
    VALIDATION = 'VALIDATION'

class DeploymentStatus(StrEnum):
    PENDING = 'PENDING'
    RUNNING = 'RUNNING'
    STOPPED = 'STOPPED'
    FAILED = 'FAILED'

class SessionType(StrEnum):
    MANUFACTURING = 'MANUFACTURING'
    VALIDATION = 'VALIDATION'

class SessionStatus(StrEnum):
    PENDING = 'PENDING'
    ACTIVE = 'ACTIVE'
    PASSED = 'PASSED'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'

class DeviceStatus(StrEnum):
    PENDING = 'PENDING'
    IN_PROGRESS = 'IN_PROGRESS'
    PASSED = 'PASSED'
    FAILED = 'FAILED'

class TestExecutionStatus(StrEnum):
    QUEUED = 'QUEUED'
    RUNNING = 'RUNNING'
    PASSED = 'PASSED'
    FAILED = 'FAILED'
    SKIPPED = 'SKIPPED'
    CANCELLED = 'CANCELLED'
    ERROR = 'ERROR'

class LogLevel(StrEnum):
    DEBUG = 'DEBUG'
    INFO = 'INFO'
    WARN = 'WARN'
    ERROR = 'ERROR'
    FATAL = 'FATAL'

class LifecycleStatus(StrEnum):
    DRAFT = 'DRAFT'
    ACTIVE = 'ACTIVE'
    DEPRECATED = 'DEPRECATED'
    EOL = 'EOL'

class FixtureStatus(StrEnum):
    AVAILABLE = 'AVAILABLE'
    LOCKED = 'LOCKED'
    OFFLINE = 'OFFLINE'
    MAINTENANCE = 'MAINTENANCE'

class IcleDeviceStatus(StrEnum):
    ONLINE = 'ONLINE'
    OFFLINE = 'OFFLINE'
    LOGGING = 'LOGGING'
    CONFIG = 'CONFIG'
    BOOT = 'BOOT'
    OTA = 'OTA'

class BuildJobStatus(StrEnum):
    QUEUED = 'QUEUED'
    BLOCKED = 'BLOCKED'
    CLONING = 'CLONING'
    BUILDING = 'BUILDING'
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'
    CACHED = 'CACHED'

class QueueEntryStatus(StrEnum):
    QUEUED = 'QUEUED'
    ASSIGNED = 'ASSIGNED'
    RUNNING = 'RUNNING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'

class TestPackageStatus(StrEnum):
    DEVELOPMENT = 'DEVELOPMENT'
    RELEASED = 'RELEASED'

class BuildRunStatus(StrEnum):
    PENDING = 'PENDING'
    BUILDING = 'BUILDING'
    BUILD_FAILED = 'BUILD_FAILED'
    VALIDATING = 'VALIDATING'
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'

class Role(StrEnum):
    ADMIN = 'ADMIN'
    MAINTAINER = 'MAINTAINER'
    DEVELOPER = 'DEVELOPER'
    OPERATOR = 'OPERATOR'

