from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Product',
    'Board',
    'BoardRevision',
    'BoardRevisionChipset',
    'Chipset',
    'FirmwareBuild',
    'ProductStageConfig',
    'ValidationQueueEntry',
    'PipelineRun',
    'BuildJob',
    'BuildJobArtifact',
    'Session',
    'Device',
    'FixtureDesign',
    'Fixture',
    'FixtureSlot',
    'Node',
    'IcleDevice',
    'IclePendingCommand',
    'IcleLog',
    'Deployment',
    'Test',
    'TestExecution',
    'TestStep',
    'User',
    'PermissionSet',
    'ApiKey',
    'AuditLog',
    'Setting',
    'Log',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Product': {
        'boards': 'Board',
        'firmwareBuilds': 'FirmwareBuild',
        'fixtures': 'Fixture',
        'tests': 'Test',
        'sessions': 'Session',
        'buildJobs': 'BuildJob',
        'pipelineRuns': 'PipelineRun',
        'deployments': 'Deployment',
        'stageConfigs': 'ProductStageConfig',
    },
    'Board': {
        'product': 'Product',
        'revisions': 'BoardRevision',
    },
    'BoardRevision': {
        'board': 'Board',
        'chipsets': 'BoardRevisionChipset',
    },
    'BoardRevisionChipset': {
        'boardRevision': 'BoardRevision',
        'chipset': 'Chipset',
    },
    'Chipset': {
        'boardRevisionChipsets': 'BoardRevisionChipset',
        'firmwareBuilds': 'FirmwareBuild',
    },
    'FirmwareBuild': {
        'product': 'Product',
        'chipset': 'Chipset',
    },
    'ProductStageConfig': {
        'product': 'Product',
        'pipelineRuns': 'PipelineRun',
        'queueEntries': 'ValidationQueueEntry',
    },
    'ValidationQueueEntry': {
        'pipelineRun': 'PipelineRun',
        'stageConfig': 'ProductStageConfig',
        'fixture': 'Fixture',
        'session': 'Session',
    },
    'PipelineRun': {
        'product': 'Product',
        'stageConfig': 'ProductStageConfig',
        'builds': 'BuildJob',
        'sessions': 'Session',
        'queueEntries': 'ValidationQueueEntry',
    },
    'BuildJob': {
        'pipelineRun': 'PipelineRun',
        'product': 'Product',
        'artifacts': 'BuildJobArtifact',
        'reusedFrom': 'BuildJob',
        'reusedBy': 'BuildJob',
    },
    'BuildJobArtifact': {
        'buildJob': 'BuildJob',
    },
    'Session': {
        'product': 'Product',
        'fixture': 'Fixture',
        'pipeline': 'PipelineRun',
        'createdBy': 'User',
        'devices': 'Device',
        'queueEntry': 'ValidationQueueEntry',
    },
    'Device': {
        'session': 'Session',
        'executions': 'TestExecution',
    },
    'FixtureDesign': {
        'fixtures': 'Fixture',
    },
    'Fixture': {
        'product': 'Product',
        'design': 'FixtureDesign',
        'slots': 'FixtureSlot',
        'sessions': 'Session',
        'queueEntries': 'ValidationQueueEntry',
    },
    'FixtureSlot': {
        'fixture': 'Fixture',
        'node': 'Node',
        'testExecutions': 'TestExecution',
    },
    'Node': {
        'fixtureSlot': 'FixtureSlot',
        'testExecutions': 'TestExecution',
    },
    'IcleDevice': {
        'commands': 'IclePendingCommand',
        'logs': 'IcleLog',
    },
    'IclePendingCommand': {
        'device': 'IcleDevice',
    },
    'IcleLog': {
        'device': 'IcleDevice',
    },
    'Deployment': {
        'product': 'Product',
        'createdBy': 'User',
    },
    'Test': {
        'product': 'Product',
        'executions': 'TestExecution',
    },
    'TestExecution': {
        'test': 'Test',
        'node': 'Node',
        'device': 'Device',
        'slot': 'FixtureSlot',
        'triggeredBy': 'User',
        'steps': 'TestStep',
        'logs': 'Log',
    },
    'TestStep': {
        'execution': 'TestExecution',
    },
    'User': {
        'permissionSet': 'PermissionSet',
        'apiKeys': 'ApiKey',
        'sessions': 'Session',
        'deployments': 'Deployment',
        'testExecutions': 'TestExecution',
        'auditLogs': 'AuditLog',
    },
    'PermissionSet': {
        'users': 'User',
    },
    'ApiKey': {
        'user': 'User',
    },
    'AuditLog': {
        'user': 'User',
    },
    'Setting': {
    },
    'Log': {
        'execution': 'TestExecution',
    },
}

# fmt: on